done
done
done
done
done
done
done
done
done
(id=1, name='aaa', age=18, address=NULL, state='DB', zip=NULL)
(id=2, name='dsa', age=40, address=NULL, state='DB', zip=NULL)
(id=3, name='afd', age=65, address=NULL, state='DB', zip=NULL)
(id=4, name='rte', age=34, address=NULL, state='DB', zip=NULL)
(id=5, name='anh', age=21, address=NULL, state='DB', zip=NULL)
(id=6, name='bda', age=23, address=NULL, state='DB', zip=NULL)
(id=7, name='aer', age=56, address=NULL, state='DB', zip=NULL)
(id=8, name='jyf', age=33, address=NULL, state='DB', zip=NULL)
(id=9, name='try', age=20, address=NULL, state='DB', zip=NULL)
(id=10, name='htr', age=54, address=NULL, state='DB', zip=NULL)
(id=99, name='ytu', age=8, address=NULL, state='DB', zip=NULL)
done
done
done
done
(id=1, name='aaa', age=18, address=NULL, state='DB', zip=NULL)
(id=2, name='dsa', age=40, address=NULL, state='DB', zip=NULL)
(id=3, name='afd', age=65, address=NULL, state='DB', zip=NULL)
(id=4, name='rte', age=34, address=NULL, state='DB', zip=NULL)
(id=5, name='anh', age=21, address=NULL, state='DB', zip=NULL)
(id=6, name='bda', age=23, address=NULL, state='DB', zip=NULL)
(id=7, name='aer', age=56, address=NULL, state='DB', zip=NULL)
(id=8, name='jyf', age=33, address=NULL, state='DB', zip=NULL)
(id=9, name='try', age=20, address=NULL, state='DB', zip=NULL)
(id=10, name='htr', age=54, address=NULL, state='DB', zip=NULL)
(id=99, name='ytu', age=8, address=NULL, state='DB', zip=NULL)
done
done
[commit] failed with rc 230 transaction is not serializable
done
[commit] failed with rc 230 transaction is not serializable
done
done
