#!/usr/bin/env bash
bash -n "$0" | exit 1

source ${TESTSROOTDIR}/tools/runit_common.sh


gen() {
    IN=$SECONDS
    while [ $((SECONDS-IN)) -lt 30 ] ; do
        echo "begin"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "commit"
    done
}

export -f gen
cluster=`cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default 'exec procedure sys.cmd.send("bdb cluster")' | grep lsn | cut -f1 -d':' `

cnt=0

# one min less than the TEST_TIMEOUT
MAXDURATION=`echo "(${TEST_TIMEOUT%%m}-1)*60" | bc`
while [ $SECONDS -lt $MAXDURATION ] ; do
    let cnt=$cnt+1
    cdb2sql ${CDB2_OPTIONS} $DBNAME default "truncate t"
    for node in $cluster; do
        cdb2sql ${CDB2_OPTIONS} $DBNAME --host $node "exec procedure sys.cmd.send('delfiles t')"
    done
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out1.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out2.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out3.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &

    wait

    do_verify t
    echo "done with run $cnt"
done
