#!/usr/bin/env bash

# Test replication stats
#
# Force replication delay on a replicant and then do a pushnext on the master
# We should be seeing the replicant is behind the master in master's
# comdb2_repl_stats table.

bash -n "$0" | exit 1

[ -z "${CLUSTER}" ] && { echo "skipping, it's a cluster test"; exit 0; }

set -e

dbnm=$1

master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'select host from comdb2_cluster where is_master="Y"'`
rep=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'select host from comdb2_cluster where is_master="N" limit 1'`

cdb2sql ${CDB2_OPTIONS} $dbnm --host $rep 'exec procedure sys.cmd.send("rep_delay 1")' >/dev/null 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm --host $master 'exec procedure sys.cmd.send("pushnext")' >/dev/null 2>&1

sleep 5

cdb2sql ${CDB2_OPTIONS} $dbnm --host $master 'select * from comdb2_repl_stats'
cnt=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm --host $master "select count(*) from comdb2_repl_stats where host = \"$rep\" and lsn_bytes_behind_master > 0"`
[ "$cnt" != "1" ] && { echo $cnt; } || { exit 0; }

bytes_written=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm --host $master "select bytes_written from comdb2_repl_stats where host = \"$rep\""`
[ "$bytes_written" != "0" ] && { echo $bytes_written; exit 1; } || { exit 0; }

