#!/usr/bin/env bash
bash -n "$0" | exit 1
set -e
dbnm=$1
mach=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'select comdb2_host()'`
for c in $CLUSTER; do
    if [ "$c" -ne "$mach" ]; then
        cdb2sql --tabs ${CDB2_OPTIONS} $dbnm --host "$c" 'exec procedure sys.cmd.send("memstat net")' | grep "$mach"
    fi
done
