#!/usr/bin/env bash
bash -n "$0" | exit 1

source ${TESTSROOTDIR}/tools/runit_common.sh

##################################################################
# Verify that analyze works correctly under high rate insertion. #
##################################################################

bash -n "$0" | exit 1
dbnm=$1

cdb2sql ${CDB2_OPTIONS} $dbnm default 'CREATE TABLE t (i INT)'
cdb2sql ${CDB2_OPTIONS} $dbnm default 'CREATE INDEX t_i ON t(i)'

nsamples=$(cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'SELECT cast(value as INT) + 24 FROM comdb2_tunables WHERE name = "stat4_extra_samples"')

echo nSamples is $nsamples

cat << EOF > in.sql
BEGIN
$(for i in `seq 1 $nsamples`; do echo 'INSERT INTO t values('$i')'; done)
COMMIT
EOF

while true; do
    cdb2sql ${CDB2_OPTIONS} $dbnm default -f in.sql > out.txt 2>&1 || failexit 'failure to insert, see out.txt'
done &

keep_inserting=$!

for i in {1..500}; do
  echo iteration $i >> out2.txt
  echo 'truncate table t'
  echo 'analyze t'
done | cdb2sql ${CDB2_OPTIONS} $dbnm default >> out2.txt || { kill -9 $keep_inserting; failexit "Please see out2.txt"; }

kill -9 $keep_inserting || true
