#!/usr/bin/env bash
bash -n "$0" | exit 1

# Test fdb push write from Lua stored procedures
################################################################################

echo "main db vars"
vars="TESTCASE DBNAME DBDIR TESTSROOTDIR TESTDIR CDB2_OPTIONS CDB2_CONFIG SECONDARY_DBNAME SECONDARY_DBDIR SECONDARY_CDB2_CONFIG SECONDARY_CDB2_OPTIONS"
for required in $vars; do
    q=${!required}
    echo "$required=$q"
    if [[ -z "$q" ]]; then
        echo "$required not set" >&2
        exit 1
    fi
done

#run tests
echo "Starting tests"
echo ./test_fdb_push_lua.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBDIR $TESTDIR
./test_fdb_push_lua.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBDIR $TESTDIR
result=$?

if (( $result != 0 )) ; then
   echo "Failure"
   exit 1
fi

echo "Success"
