#!/bin/bash

DB=$2
default=default
cdb2sql=cdb2sql

# wait for other connections to go away
sleep 30

export CDB2_DISABLE_SOCKPOOL=1

for i in $(seq 1 10); do $cdb2sql ${CDB2_OPTIONS} $DB $default 'select 1'; done; $cdb2sql ${CDB2_OPTIONS} $DB $default 'select total_sql, sql_since_reset, num_resets from comdb2_connections'

(
for i in $(seq 1 10); do
    echo "select 1"
done 
echo "select total_sql, sql_since_reset, num_resets from comdb2_connections"
) | $cdb2sql ${CDB2_OPTIONS} $DB $default -
