#!/usr/bin/env bash
bash -n "$0" | exit 1

. ${TESTSROOTDIR}/tools/cluster_utils.sh
. ${TESTSROOTDIR}/tools/runit_common.sh

set -x
set -e

function run_test
{
    typeset -l j=0
    typeset -l master=$(get_master)
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "create table t1 (a int)"

    while [[ "$j" -lt 10 ]] ; do
        $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "truncate t1"
        let j=j+1
    done

    sleep 10

    # Dump output into the .testcase file
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "select * from comdb2_unused_files"

    cnt=$($CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME --host $master "select count(*) from comdb2_unused_files")
    [[ "$cnt" == "10" ]] || failexit "Incorrect number of unused files: $cnt"
    namecnt=$($CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME --host $master "select count(*) from comdb2_unused_files where filename like 'XXX.t1%datas0'")
    [[ "$namecnt" == "10" ]] || failexit "Incorrect number of unused files for t1: $namecnt"
}

run_test
echo "Success!"
