#!/usr/bin/env bash
bash -n "$0" | exit 1

# Grab my database name.
dbnm=$1

# Insert some records
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t1 (a) values ('0 02:00:00.000')"
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t1 (a) values ('0 02:00:00.000')"
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t1 (a) values ('0 02:00:00.000')"
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t1 (a) values ('0 02:00:00.000')"
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t1 (a) values ('0 02:00:00.000')"

# Analyze
cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure sys.cmd.analyze('t1')"

# Select with a where clause
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t1 where a='0 02:00:00'"
r=$?
if [[ $r != 0 ]]; then 
    echo "Bad rcode $r from select"
    exit 1
fi

echo "Success"
