#!/usr/bin/env bash
bash -n "$0" | exit 1

set -x
dbname=$1

if [[ $DBNAME == *"snapshotgenerated"* ]] ; then
    lvl=$(cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default "select value from comdb2_tunables where name='sql_tranlevel_default'")
    if [ "$lvl" != "SNAPSHOT ISOLATION" ] ; then
       echo "FAILURE: DB is not running in snapshot isolation mode"
       exit 1
    fi
fi



echo "Starting tests"
echo "Using SP_OPTIONS: $SP_OPTIONS"
./test.sh $dbname
rc=$?
if (( $rc != 0 )) ; then
   echo "FAILURE"
   exit 1
fi

echo "SUCCESS"
