#!/usr/bin/env bash
bash -n "$0" | exit 1

source ${TESTSROOTDIR}/tools/runit_common.sh

INITNUMREC=100

if [ "x${DBNAME}" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

if [ -z $COMDB2_EXE ] ; then
   failexit '$COMDB2_EXE is not set'
fi

nout=0  # file extension counter


assert_vers()
{
    tbl=$1
    target=$2
    newver=$(cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default "select table_version('$tbl')")
    if [[ $newver != $target ]] ; then
        failexit "newver is now $newver but should be $target"
    fi
    tblver=$newver
}

assert_schema()
{
    tbl=$1
    schema=$2

    echo "make sure that the current schema is $schema"
    cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default "select csc2 from sqlite_master where name='$tbl'" | sed 's/ \(schema\)/\1/;s/} /}/' > schema.out

    if ! diff -Bw schema.out $schema ; then 
        cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default 'select * from sqlite_master' > sqlite_master.out
        failexit "final schema is not same as $schema: diff schema.out $schema"
    fi
}

insert_records()
{
    echo "Entering insert_records()"
    j=$1
    nstop=$2
    let nout=nout+1
    insfl=insert${nout}.out
    echo "Inserting $((nstop-j+1)) records ($j to $nstop)."

    while [[ $j -le $nstop ]]; do 
        echo "insert into t1(alltypes_short, alltypes_u_short, alltypes_int, alltypes_u_int, alltypes_longlong, alltypes_float, alltypes_double, alltypes_byte, alltypes_cstring, alltypes_pstring, alltypes_blob, alltypes_datetime, alltypes_datetimeus, alltypes_vutf8, alltypes_intervalym, alltypes_intervalds, alltypes_intervaldsus, alltypes_decimal32, alltypes_decimal64, alltypes_decimal128) values ( $((1-2*(j%2)))$j ,$j ,$((1-2*(j%2)))0000$j ,10000$j ,$((1-2*(j%2)))000000000$j ,$((1-2*(j%2)))00.00$j ,$((1-2*(j%2)))0000$j.0000$j ,x'aabbccddeeffaabb$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))' ,'mycstring$j' ,'mypstring$j' ,x'$((j%2))$((j%3))$((j%4))$((j%5))' ,'$(date +'%Y-%m-%dT%H:%M:%S')' ,'$(date +'%Y-%m-%dT%H:%M:%S')' ,'myvutf8$j' ,$((1-2*(j%2)))$j ,$((1-2*(j%2)))0000$j , $((1-2*(j%2)))0000$j , $((1-2*(j%2)))0000$j , $((1-2*(j%2)))00000000$j , $((1-2*(j%2)))000000000000000$j )"
        # use for compare? echo "a=$j, b='test1$j', c='$j'" >> rows.out
        let j=j+1
    done | cdb2sql ${CDB2_OPTIONS} ${DBNAME} default &> $insfl || failexit "insert_records error"
    echo "done inserting round $nout"
}

insert_records_with_bind()
{
    echo "Entering insert_records_with_bind()"
    j=$1
    nstop=$2
    let nout=nout+1
    insfl=insert${nout}.out
    echo "Inserting $((nstop-j+1)) records ($j to $nstop)."
    echo "" > $insfl
#{ CDB2_INTEGER = 1, CDB2_REAL = 2, CDB2_CSTRING = 3, CDB2_BLOB = 4, CDB2_DATETIME = 6, CDB2_INTERVALYM = 7, CDB2_INTERVALDS = 8, CDB2_DATETIMEUS = 9, CDB2_INTERVALDSUS = 10 }
    while [[ $j -le $nstop ]]; do 
        echo "
@bind CDB2_INTEGER v_alltypes_short $(((1-2*(j%2))*$j))
@bind CDB2_INTEGER v_alltypes_u_short $j
@bind CDB2_INTEGER v_alltypes_int $((1-2*(j%2)))0000$j
@bind CDB2_INTEGER v_alltypes_u_int 10000$j
@bind CDB2_INTEGER v_alltypes_longlong $((1-2*(j%2)))000000000$j
@bind CDB2_REAL    v_alltypes_float $((1-2*(j%2)))00.00$j
@bind CDB2_REAL    v_alltypes_double $((1-2*(j%2)))0000$j.0000$j
@bind CDB2_CSTRING v_alltypes_cstring my cstring $j
@bind CDB2_CSTRING v_alltypes_pstring my pstring $j
@bind CDB2_CSTRING v_alltypes_datetime $(date +'%Y-%m-%dT%H:%M:%S')
@bind CDB2_CSTRING v_alltypes_datetimeus $(date +'%Y-%m-%dT%H:%M:%S')
@bind CDB2_CSTRING v_alltypes_vutf8 my vutf8 $j
@bind CDB2_CSTRING v_alltypes_intervalym $((1-2*(j%2)))$j
@bind CDB2_CSTRING v_alltypes_intervalds $((1-2*(j%2)))0000$j
@bind CDB2_CSTRING v_alltypes_decimal32 $((1-2*(j%2)))0000$j
@bind CDB2_CSTRING v_alltypes_decimal64 $((1-2*(j%2)))0000000$j
@bind CDB2_CSTRING v_alltypes_decimal128 $((1-2*(j%2)))000000000000000$j
insert into t1(alltypes_short, alltypes_u_short, alltypes_int, alltypes_u_int, alltypes_longlong, alltypes_float, alltypes_double, alltypes_cstring, alltypes_pstring, alltypes_datetime, alltypes_datetimeus, alltypes_vutf8, alltypes_intervalym, alltypes_intervalds, alltypes_decimal32, alltypes_decimal64, alltypes_decimal128) values (@v_alltypes_short, @v_alltypes_u_short, @v_alltypes_int, @v_alltypes_u_int, @v_alltypes_longlong, @v_alltypes_float, @v_alltypes_double, @v_alltypes_cstring, @v_alltypes_pstring, @v_alltypes_datetime, @v_alltypes_datetimeus, @v_alltypes_vutf8, @v_alltypes_intervalym, @v_alltypes_intervalds, @v_alltypes_decimal32, @v_alltypes_decimal64, @v_alltypes_decimal128)" | cdb2sql ${CDB2_OPTIONS} ${DBNAME} default - &>> $insfl
        assertres $? 0
        let j=j+1
    done
    echo "done inserting with bind round $nout"
}

update_records()
{
    echo "Entering update_records()"
    j=$1
    nstop=$2
    let nout=nout+1
    updfl=update${nout}.out
    echo "Updating $((nstop-j+1)) records ($j to $nstop)."

    while [[ $j -le $nstop ]]; do 
        echo "update t1 set alltypes_short=alltypes_short+1, alltypes_int=alltypes_int+1,alltypes_u_int=alltypes_u_int+1,alltypes_longlong=alltypes_longlong+1,alltypes_float=alltypes_float=1,alltypes_double=alltypes_double+1,alltypes_decimal32=alltypes_decimal32+1,alltypes_decimal64=alltypes_decimal64+1,alltypes_decimal128=alltypes_decimal128+1 where alltypes_u_short=$j"
        let j=j+1
    done | cdb2sql ${CDB2_OPTIONS} ${DBNAME} default &> $updfl || failexit "update_records error"
    echo "done updating round $nout"
}

update_records_with_bind()
{
    echo "Entering update_records_with_bind()"
    j=$1
    nstop=$2
    let nout=nout+1
    updfl=update${nout}.out
    echo "Updating $((nstop-j+1)) records ($j to $nstop)."
    echo "" > $updfl

    while [[ $j -le $nstop ]]; do 
       let jpone=$j+1
       # update will effectively make col v_alltypes_int+2
       echo "
@bind CDB2_INTEGER v_alltypes_u_short $j
@bind CDB2_INTEGER v_alltypes_int $jpone
update t1 set alltypes_u_int=1+@v_alltypes_int where alltypes_u_short=@v_alltypes_u_short" | cdb2sql ${CDB2_OPTIONS} ${DBNAME} default - &>> $updfl
        assertres $? 0
        let j=j+1
    done
    echo "done updating round $nout"
}

update_records_with_bind_index()
{
    j=$1
    nstop=$2
    let nout=nout+1
    updfl=update${nout}.out
    echo "Updating $((nstop-j+1)) records ($j to $nstop)."
    echo "" > $updfl
    let k=0

    while [[ $j -le $nstop ]]; do 
       let jpone=$j+1
       let k=$k+1
       # update will increase alltypes_u_int by 1,2,3...N
       echo "
@bind CDB2_INTEGER 1 $k
@bind CDB2_INTEGER 2 $j
update t1 set alltypes_u_int=alltypes_u_int+? where alltypes_u_short=?" | cdb2sql ${CDB2_OPTIONS} ${DBNAME} default - &>> $updfl
        assertres $? 0
        let j=j+1
    done
    echo "done updating round $nout"
}

delete_records()
{
    j=$1
    nstop=$2
    let nout=nout+1
    delfl=delete${nout}.out
    echo "Updating $((nstop-j+1)) records ($j to $nstop)."

    while [[ $j -le $nstop ]]; do 
        echo "delete from t1 where alltypes_u_short=$j"
        let j=j+1
        sleep 0.01
    done | cdb2sql ${CDB2_OPTIONS} ${DBNAME} default   &> $delfl || failexit "delete_records error"
    echo "done updating round $nout"
}


insert_rollback_tran()
{
    echo "Entering insert_rollback_tran()"
    j=$1
    nstop=$2
    let nout=nout+1
    insfl=insert${nout}.out
    echo "Inserting $((nstop-j+1)) records ($j to $nstop)."
    echo "" > $insfl

    echo "begin" > in.sql
    while [[ $j -le $nstop ]]; do 
        echo "insert into t1(alltypes_short, alltypes_u_short, alltypes_int, alltypes_u_int, alltypes_longlong, alltypes_float, alltypes_double, alltypes_byte, alltypes_cstring, alltypes_pstring, alltypes_blob, alltypes_datetime, alltypes_datetimeus, alltypes_vutf8, alltypes_intervalym, alltypes_intervalds, alltypes_intervaldsus, alltypes_decimal32, alltypes_decimal64, alltypes_decimal128) values ( $((1-2*(j%2)))$j ,$j ,$((1-2*(j%2)))0000$j ,10000$j ,$((1-2*(j%2)))000000000$j ,$((1-2*(j%2)))00.00$j ,$((1-2*(j%2)))0000$j.0000$j ,x'aabbccddeeffaabb$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))' ,'mycstring$j' ,'mypstring$j' ,x'$((j%2))$((j%3))$((j%4))$((j%5))' ,'$(date +'%Y-%m-%dT%H:%M:%S')' ,'$(date +'%Y-%m-%dT%H:%M:%S')' ,'myvutf8$j' ,$((1-2*(j%2)))$j ,$((1-2*(j%2)))0000$j , $((1-2*(j%2)))0000$j , $((1-2*(j%2)))0000$j , $((1-2*(j%2)))00000000$j , $((1-2*(j%2)))000000000000000$j )"  >> in.sql
        let j=j+1
    done
    echo "rollback" >> in.sql
    cdb2sql ${CDB2_OPTIONS} ${DBNAME} default -f in.sql &>> $insfl
    assertres $? 0
    echo "done rollback round $nout"
}

insert_commit_tran()
{
    echo "Entering insert_commit_tran()"
    j=$1
    nstop=$2
    let nout=nout+1
    insfl=insert${nout}.out
    echo "Inserting $((nstop-j+1)) records ($j to $nstop)."
    echo "" > $insfl

    echo "begin" > in.sql
    while [[ $j -le $nstop ]]; do 
        echo "insert into t1(alltypes_short, alltypes_u_short, alltypes_int, alltypes_u_int, alltypes_longlong, alltypes_float, alltypes_double, alltypes_byte, alltypes_cstring, alltypes_pstring, alltypes_blob, alltypes_datetime, alltypes_datetimeus, alltypes_vutf8, alltypes_intervalym, alltypes_intervalds, alltypes_intervaldsus, alltypes_decimal32, alltypes_decimal64, alltypes_decimal128) values ( $((1-2*(j%2)))$j ,$j ,$((1-2*(j%2)))0000$j ,10000$j ,$((1-2*(j%2)))000000000$j ,$((1-2*(j%2)))00.00$j ,$((1-2*(j%2)))0000$j.0000$j ,x'aabbccddeeffaabb$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))$((j%2))$((j%3))$((j%4))$((j%5))' ,'mycstring$j' ,'mypstring$j' ,x'$((j%2))$((j%3))$((j%4))$((j%5))' ,'$(date +'%Y-%m-%dT%H:%M:%S')' ,'$(date +'%Y-%m-%dT%H:%M:%S')' ,'myvutf8$j' ,$((1-2*(j%2)))$j ,$((1-2*(j%2)))0000$j , $((1-2*(j%2)))0000$j , $((1-2*(j%2)))0000$j , $((1-2*(j%2)))00000000$j , $((1-2*(j%2)))000000000000000$j )"  >> in.sql
        let j=j+1
    done
    echo "commit" >> in.sql
    cdb2sql ${CDB2_OPTIONS} ${DBNAME} default -f in.sql &>> $insfl
    assertres $? 0
    echo "done commit round $nout"
}

cluster=`cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default 'exec procedure sys.cmd.send("bdb cluster")' | grep lsn | cut -f1 -d':' `
for node in $cluster ; do
    cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} --host $node 'exec procedure sys.cmd.send("reql events roll")'
done

cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "create table t1  { `cat alltypes.csc2 ` }"
cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "create table carray1 (a int, b double, c cstring(32), d longlong, e blob)"
cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "create table carray2 (a int, b double, c cstring(32), d longlong, e blob)"

# following is an error because t2 does not exist, resulting in a 
# fingerprint of 00000 so will not ba replayed
cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "select * from t2"

assert_vers t1 0
assert_schema t1 alltypes.csc2

let NEWNUMREC=$((2*INITNUMREC))
insert_records 1 $NEWNUMREC
assertcnt t1 $NEWNUMREC

update_records 1 $NEWNUMREC
assertcnt t1 $NEWNUMREC

delete_records $((INITNUMREC+1)) $NEWNUMREC
assertcnt t1 $INITNUMREC

let NEWSTRT=$((INITNUMREC+1))
insert_records_with_bind $NEWSTRT $NEWNUMREC
assertcnt t1 $NEWNUMREC

update_records_with_bind $NEWSTRT $((NEWSTRT+9))
assertcnt t1 $NEWNUMREC

#insert_records_with_bind $NEWSTRT $NEWNUMREC
#cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "select * from t1 order by alltypes_u_short" > a1.txt
#assertcnt t1 $NEWNUMREC

update_records_with_bind_index $((NEWSTRT+10)) $((NEWSTRT+19))
assertcnt t1 $NEWNUMREC

insert_rollback_tran $((NEWNUMREC+1)) $((NEWNUMREC+10))
assertcnt t1 $NEWNUMREC

insert_commit_tran $((NEWNUMREC+1)) $((NEWNUMREC+10))
assertcnt t1 $((NEWNUMREC+10))

${TESTSBUILDDIR}/cdb2api_caller ${DBNAME} t1 > /dev/null
${TESTSBUILDDIR}/carray_insert ${DBNAME}

cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "select * from t1 order by alltypes_u_short" > orig.txt
cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "select * from carray1 order by 1" >> orig.txt
cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "select * from carray2 order by 1" >> orig.txt

logflunziped=events.unzipped
if [[ -z "$CLUSTER" ]]; then
    logfl=`cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "exec procedure sys.cmd.send('reql stat')"  | grep Eventlog | sed "s/[^:]*:\(.*\)')/\1/g"`
    cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default 'exec procedure sys.cmd.send("flush")'
    cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default 'exec procedure sys.cmd.send("reql events roll")'

    zcat $logfl | grep --text -v 'sys.cmd.send' | sort -n > $logflunziped

else

    for node in $CLUSTER ; do
        logfl=`cdb2sql ${CDB2_OPTIONS} ${DBNAME} --host $node "exec procedure sys.cmd.send('reql stat')"  | grep Eventlog | sed "s/[^:]*:\(.*\)')/\1/g"`
        cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} --host $node 'exec procedure sys.cmd.send("flush")'
        cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} --host $node 'exec procedure sys.cmd.send("reql events roll")'
        ssh -o StrictHostKeyChecking=no $node "zcat $logfl" | grep --text -v 'sys.cmd.send' > ${node}.events.unzipped
    done
    sort -n *.events.unzipped > $logflunziped
fi

echo "Make sure that the data we expect is in the event log file"
echo $logflunziped
jq -r 'if (.type == "sql") and has("fingerprint") then "\(.fingerprint) \(.sql[0:24])" else empty end' < $logflunziped | sort | uniq -c > fingerprints_only.out
if ! diff fingerprints_only.out fingerprints_freq.exp ; then
    echo "Failed diff $PWD/fingerprints_only.out $PWD/fingerprints_freq.exp"
    failexit "fingerprints_only.out contains different fingerprint data expected"
fi

echo "working with secondary db"
cluster=`cdb2sql --tabs ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default 'exec procedure sys.cmd.send("bdb cluster")' | grep lsn | cut -f1 -d':' `
for node in $cluster ; do
    cdb2sql --tabs ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME --host $node 'exec procedure sys.cmd.send("reql events roll")'
done

echo running "CDB2_CONFIG=\"${SECONDARY_CDB2_CONFIG}\" $CDB2_SQLREPLAY_EXE $SECONDARY_DBNAME $logflunziped > sqlreplay.out"
CDB2_CONFIG="${SECONDARY_CDB2_CONFIG}" $CDB2_SQLREPLAY_EXE $SECONDARY_DBNAME $logflunziped > sqlreplay.out

echo "Get the secondary db event logs"
slogflunziped=secondary_events.unzipped
if [[ -z "$CLUSTER" ]]; then
    logfl=`cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "exec procedure sys.cmd.send('reql stat')"  | grep Eventlog | sed "s/[^:]*:\(.*\)')/\1/g"`
    cdb2sql --tabs ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default 'exec procedure sys.cmd.send("flush")'
    cdb2sql --tabs ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default 'exec procedure sys.cmd.send("reql events roll")'
    zcat $logfl | sort -n | egrep -v 'sys.cmd.send|comdb2_prevquerycost' > $slogflunziped
else
    for node in $CLUSTER ; do
        logfl=`cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME --host $node "exec procedure sys.cmd.send('reql stat')"  | grep Eventlog | sed "s/[^:]*:\(.*\)')/\1/g"`
        cdb2sql --tabs ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME --host $node 'exec procedure sys.cmd.send("flush")'
        cdb2sql --tabs ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME --host $node 'exec procedure sys.cmd.send("reql events roll")'
        ssh -o StrictHostKeyChecking=no $node "zcat $logfl" > ${node}.events.unzipped
    done
    sort -n *.events.unzipped | egrep -v 'sys.cmd.send|comdb2_prevquerycost' > $slogflunziped
fi

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "select * from t1 order by alltypes_u_short" > replayed.txt
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "select * from carray1 order by 1" >> replayed.txt
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "select * from carray2 order by 1" >> replayed.txt

success=1

if ! diff orig.txt replayed.txt ; then
    success=0
fi

if [ $success != 1 ] ; then
    failexit "replayed.txt content is not the same as orig.txt"
fi

jq 'if (.type == "sql") and (.fingerprint != "00000000000000000000000000000000") then [.fingerprint, .sql] | @csv else empty end' < $logflunziped > 1.out
jq 'if (.type == "sql") then [.fingerprint, .sql] | @csv else empty end' < $slogflunziped > 2.out
if ! diff 1.out 2.out ; then
    failexit "fingerprint and sql content is not same (1.out vs 2.out)"
fi

echo "Testing datetime binding replay"
cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "CREATE TABLE t_datetime (c datetime)"
cdb2sql ${CDB2_OPTIONS} ${DBNAME} default - <<'EOF'
@bind CDB2_DATETIME a 2024-01-01T00:00:00
SELECT * FROM t_datetime where c>@a
EOF

logflunziped=datetime_events.unzipped
if [[ -z "$CLUSTER" ]]; then
    logfl=`cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "exec procedure sys.cmd.send('reql stat')"  | grep Eventlog | sed "s/[^:]*:\(.*\)')/\1/g"`
    cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default 'exec procedure sys.cmd.send("flush")'
    cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} default 'exec procedure sys.cmd.send("reql events roll")'

    zcat $logfl | grep --text -i 'from t_datetime where' >>$logflunziped
else
    for node in $CLUSTER ; do
        logfl=`cdb2sql ${CDB2_OPTIONS} ${DBNAME} --host $node "exec procedure sys.cmd.send('reql stat')"  | grep Eventlog | sed "s/[^:]*:\(.*\)')/\1/g"`
        cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} --host $node 'exec procedure sys.cmd.send("flush")'
        cdb2sql --tabs ${CDB2_OPTIONS} ${DBNAME} --host $node 'exec procedure sys.cmd.send("reql events roll")'
        ssh -o StrictHostKeyChecking=no $node "zcat $logfl" | grep --text -i 'from t_datetime where' >> $logflunziped
    done
fi

cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "INSERT INTO t_datetime VALUES(now())"

${CDB2_SQLREPLAY_EXE} --diff --threshold 0 ${DBNAME} $logflunziped 2>/dev/null | sed 's/tranid 0//' | cdb2sql ${CDB2_OPTIONS} ${DBNAME} default -
if [ $? != 0 ]; then
    failexit "failed to execute replay diff"
fi

if [ "$CLEANUPDBDIR" != "0" ] ; then
    #delete files now that test is successful
    rm 1.out 2.out orig.txt replayed.txt sqlreplay.out $logflunziped $slogflunziped
fi

echo "Success"
