#!/usr/bin/env bash

# Runs the register linearizability test
[[ "$debug" == 1 ]] && set -x
#debug_trace="-D"
db=$1

regtest=${TESTSBUILDDIR}/register

if [[ -z "$CLUSTER" ]]; then
    echo "This test is only relevant for a CLUSTERED installation."
    exit 1
fi

if [[ -z "$stage" ]]; then
    echo "Setting stage to 'default' (set 'stage' var to override)."
    stage="default"
fi

function createtables
{
    [[ "$debug" == 1 ]] && set -x
    cdb2sql ${CDB2_OPTIONS} $db $stage "create table register {schema{int id int val null=yes longlong uid null=yes} keys{ \"id\" = id }}" >/dev/null 2>&1
}

function checkforerrors
{
    [[ "$debug" == 1 ]] && set -x
    clojout=$1
    knosout=$2
    (
        cd ${TESTSROOTDIR}/tools/linearizable/filetest
        lein run $clojout > $knosout 2>&1 < /dev/null
    )

    egrep "^{:valid\? false" $knosout >/dev/null 2>&1 
    if [[ $? == 0 ]]; then
        echo "INVALID KNOSSOS ANALYSIS FOR REGISTER TEST: see $clojout/$knosout"
        exit 1
    fi

    return 0
}

function heal
{
    [[ "$debug" == 1 ]] && set -x
    machs=$(cdb2sql -showports $db $stage "select 1" 2>&1 >/dev/null | while read mach xxx ; do echo $mach ; done)
    ports=$(cdb2sql -showports $db $stage "select 1" 2>&1 >/dev/null)
    for mach in $machs ; do 
        echo "$ports" | while read m p ; do 
	        ssh $mach "sudo iptables -D INPUT -s $m -p tcp --destination-port $p -j DROP -w" < /dev/null >/dev/null 2>&1
	        ssh $mach "sudo iptables -D INPUT -s $m -p udp --destination-port $p -j DROP -w" < /dev/null >/dev/null 2>&1
	        ssh $mach "sudo kill -CONT \$(cat /tmp/$db.pid)" < /dev/null >/dev/null 2>&1
        done
    done
}

function waitforcoherency
{
    [[ "$debug" == 1 ]] && set -x
    heal
    ma=$(cdb2sql -tabs $db $stage "exec procedure sys.cmd.send('bdb cluster')" | egrep MASTER | egrep lsn) 
    m=${ma%%:*}
    c=$(ssh $m "/opt/bb/bin/cdb2sql -tabs $db @localhost \"exec procedure sys.cmd.send('bdb cluster')\"")
    echo "$c"
    echo "$c" | egrep COHERENT
    r=$?
    while [[ $r == 0 ]] ; do
        echo "$(date) waiting for $db cluster to become coherent"
        heal
        sleep 1
        ma=$(cdb2sql -tabs $db $stage "exec procedure sys.cmd.send('bdb cluster')" | egrep MASTER | egrep lsn) 
        m=${ma%%:*}
        c=$(ssh $m "/opt/bb/bin/cdb2sql -tabs $db @localhost \"exec procedure sys.cmd.send('bdb cluster')\"")
        echo "$c"
        echo "$c" | egrep COHERENT
        r=$?
    done
}

function runtestwithoptions
{
    [[ "$debug" == 1 ]] && set -x
    dt=$(date +%Y%m%d%H%M%S)
    outfile=register.$db.$dt.out
    clojout=register.$db.$dt.cloj
    knosout=register.$db.$dt.knossos
    echo "$regtest -d $db -c ${CDB2_CONFIG} -t stage $debug_trace -r 20 -j $clojout $*" > $outfile
    $regtest -d $db -c ${CDB2_CONFIG} -t stage $debug_trace -r 20 -j $clojout $* >> $outfile 2>&1
    checkforerrors $(pwd)/$clojout $(pwd)/$knosout
    echo "OUTFILE" ; cat $outfile
    echo "clojout" ; cat $clojout
    echo "knosout" ; cat $knosout
    rm $outfile $clojout $knosout
}

function longtest
{
    [[ "$debug" == 1 ]] && set -x
    runtestwithoptions -G parition
    runtestwithoptions -G sigstop
    runtestwithoptions -G sigstop -G partition
}

function normaltest
{
    [[ "$debug" == 1 ]] && set -x
    runtestwithoptions -G sigstop -G partition
}

function runtest
{
    [[ "$debug" == 1 ]] && set -x
    if [[ -z "$CONTINUOUS" ]]; then
        normaltest
    else
        longtest
    fi
}

createtables
runtest

echo "Success"
exit 0
