FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    bc \
    bison \
    build-essential \
    cmake \
    flex \
    gawk \
    gdb \
    iproute2 \
    iputils-ping \
    libevent-dev \
    liblz4-dev \
    liblz4-tool \
    libprotobuf-c1 \
    libprotobuf-c-dev \
    libreadline-dev \
    libsqlite3-0 \
    libsqlite3-dev \
    libssl-dev \
    libunwind-dev \
    libuuid1 \
    libz1 \
    libz-dev \
    make \
    ncurses-dev \
    netcat-openbsd \
    net-tools \
    openssh-server \
    protobuf-c-compiler \
    psmisc \
    socat \
    strace \
    tcl \
    tcl-dev \
    time \
    tzdata \
    valgrind \
    vim \
    uuid-dev && \
  ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
  dpkg-reconfigure --frontend noninteractive tzdata

COPY . /comdb2

RUN cd /comdb2 &&  \
    rm -rf build && \
    mkdir build && \
    cd build && \
    cmake -DWITH_TCL=1 -DCMAKE_BUILD_TYPE="Debug" -DDEBUG_ABORT_ON_RECOVERY_FAILURE=1 -DCOMDB2_PER_THREAD_MALLOC=0 .. && \
    make -j4 && \
    make -j4 test-tools && \
    make install &&  \
    cd /comdb2/pgdump && \
    make -j4 && \
    make install && \
    cp /comdb2/tests/docker/client / && \
    cp /comdb2/tests/docker/server / && \
    apt-get clean

ENV PATH      $PATH:/opt/bb/bin
ENV CLUSTER   "n1 n2 n3"
ENV SKIPSSL   1
