(rows deleted=0)
[delete from t2 where 1] rc 0
(rows inserted=1)
[insert into t2 values(3)] rc 0
[set transaction read committed] rc 0
[begin] rc 0
[insert into t2 values(1)] rc 0
[insert into t2 values(2)] rc 0
[insert into t2 values(3)] rc 0
[insert into t2 values(3)] rc 0
[insert into t2 values(4)] rc 0
[select * from t2 where a = 0] rc 0
[select * from t2 where a = 0 order by a desc] rc 0
[select * from t2 where a = 0 order by a asc] rc 0
(a=1)
[select * from t2 where a = 1] rc 0
(a=1)
[select * from t2 where a = 1 order by a desc] rc 0
(a=1)
[select * from t2 where a = 1 order by a asc] rc 0
(a=2)
[select * from t2 where a = 2] rc 0
(a=2)
[select * from t2 where a = 2 order by a desc] rc 0
(a=2)
[select * from t2 where a = 2 order by a asc] rc 0
(a=3)
(a=3)
(a=3)
[select * from t2 where a = 3] rc 0
(a=3)
(a=3)
(a=3)
[select * from t2 where a = 3 order by a desc] rc 0
(a=3)
(a=3)
(a=3)
[select * from t2 where a = 3 order by a asc] rc 0
(a=4)
[select * from t2 where a = 4] rc 0
(a=4)
[select * from t2 where a = 4 order by a desc] rc 0
(a=4)
[select * from t2 where a = 4 order by a asc] rc 0
[select * from t2 where a = 5] rc 0
[select * from t2 where a = 5 order by a desc] rc 0
[select * from t2 where a = 5 order by a asc] rc 0
[select * from t2 where a < 0] rc 0
[select * from t2 where a < 0 order by a desc] rc 0
[select * from t2 where a < 0 order by a asc] rc 0
[select * from t2 where a < 1] rc 0
[select * from t2 where a < 1 order by a desc] rc 0
[select * from t2 where a < 1 order by a asc] rc 0
(a=1)
[select * from t2 where a < 2] rc 0
(a=1)
[select * from t2 where a < 2 order by a desc] rc 0
(a=1)
[select * from t2 where a < 2 order by a asc] rc 0
(a=1)
(a=2)
[select * from t2 where a < 3] rc 0
(a=2)
(a=1)
[select * from t2 where a < 3 order by a desc] rc 0
(a=1)
(a=2)
[select * from t2 where a < 3 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
[select * from t2 where a < 4] rc 0
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a < 4 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
[select * from t2 where a < 4 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a < 5] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a < 5 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a < 5 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a > 0] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a > 0 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a > 0 order by a asc] rc 0
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a > 1] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
[select * from t2 where a > 1 order by a desc] rc 0
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a > 1 order by a asc] rc 0
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a > 2] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
[select * from t2 where a > 2 order by a desc] rc 0
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a > 2 order by a asc] rc 0
(a=4)
[select * from t2 where a > 3] rc 0
(a=4)
[select * from t2 where a > 3 order by a desc] rc 0
(a=4)
[select * from t2 where a > 3 order by a asc] rc 0
[select * from t2 where a > 4] rc 0
[select * from t2 where a > 4 order by a desc] rc 0
[select * from t2 where a > 4 order by a asc] rc 0
[select * from t2 where a > 5] rc 0
[select * from t2 where a > 5 order by a desc] rc 0
[select * from t2 where a > 5 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 0] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a >= 0 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 0 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 1] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a >= 1 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 1 order by a asc] rc 0
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 2] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
[select * from t2 where a >= 2 order by a desc] rc 0
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 2 order by a asc] rc 0
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 3] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
[select * from t2 where a >= 3 order by a desc] rc 0
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a >= 3 order by a asc] rc 0
(a=4)
[select * from t2 where a >= 4] rc 0
(a=4)
[select * from t2 where a >= 4 order by a desc] rc 0
(a=4)
[select * from t2 where a >= 4 order by a asc] rc 0
[select * from t2 where a >= 5] rc 0
[select * from t2 where a >= 5 order by a desc] rc 0
[select * from t2 where a >= 5 order by a asc] rc 0
[select * from t2 where a <= 0] rc 0
[select * from t2 where a <= 0 order by a desc] rc 0
[select * from t2 where a <= 0 order by a asc] rc 0
(a=1)
[select * from t2 where a <= 1] rc 0
(a=1)
[select * from t2 where a <= 1 order by a desc] rc 0
(a=1)
[select * from t2 where a <= 1 order by a asc] rc 0
(a=1)
(a=2)
[select * from t2 where a <= 2] rc 0
(a=2)
(a=1)
[select * from t2 where a <= 2 order by a desc] rc 0
(a=1)
(a=2)
[select * from t2 where a <= 2 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
[select * from t2 where a <= 3] rc 0
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a <= 3 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
[select * from t2 where a <= 3 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a <= 4] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a <= 4 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a <= 4 order by a asc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a <= 5] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a <= 5 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a <= 5 order by a asc] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a != 0 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a != 0 order by a asc] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
[select * from t2 where a != 1 order by a desc] rc 0
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a != 1 order by a asc] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=1)
[select * from t2 where a != 2 order by a desc] rc 0
(a=1)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a != 2 order by a asc] rc 0
(a=4)
(a=2)
(a=1)
[select * from t2 where a != 3 order by a desc] rc 0
(a=1)
(a=2)
(a=4)
[select * from t2 where a != 3 order by a asc] rc 0
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a != 4 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
[select * from t2 where a != 4 order by a asc] rc 0
(a=4)
(a=3)
(a=3)
(a=3)
(a=2)
(a=1)
[select * from t2 where a != 5 order by a desc] rc 0
(a=1)
(a=2)
(a=3)
(a=3)
(a=3)
(a=4)
[select * from t2 where a != 5 order by a asc] rc 0
[rollback] rc 0
