DROP TABLE IF EXISTS t1;
CREATE TABLE t1(i INT PRIMARY KEY) $$

BEGIN;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(2);
COMMIT;

START TRANSACTION;
INSERT INTO t1 VALUES(3);
INSERT INTO t1 VALUES(4);
COMMIT;

SELECT COUNT(*)=4 FROM t1;

START TRANSACTION;
INSERT INTO t1 VALUES(3);
COMMIT;

SELECT COUNT(*)=4 FROM t1;

DROP TABLE t1;
