#!/bin/sh

bash -n "$0" | exit 1
dbnm=$1

master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'exec procedure sys.cmd.send("bdb cluster")' | grep MASTER | awk '{print $1}' | cut -d':' -f1`

cat << EOF | cdb2sql --host $master $dbnm -
drop table t
create table t options blobfield none {schema {int id blob b}}\$\$
insert into t values(1, x'DEADBEEF')
insert into t values(2, x'DEADBEEF')
insert into t values(3, x'DEADBEEF')
exec procedure sys.cmd.send('on logical_live_sc')
exec procedure sys.cmd.send('scdelay 2000')
PUT SCHEMACHANGE COMMITSLEEP 3
PUT SCHEMACHANGE CONVERTSLEEP 3
EOF

cdb2sql --host $master $dbnm 'rebuild t' &
rebuildpid=$!

sleep 4

cdb2sql --host $master $dbnm "insert into t values(4, x'')"
wait $rebuildpid
