#!/usr/bin/env bash
bash -n "$0" | exit 1

# This test case is a collection of queries reported in various 
# DRQS tickets. As such each one will have different schemas.
# The driver will just add/alter tables as required.

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

# Execute all .req files.
${TESTSROOTDIR}/tools/compare_results.sh -s -d $dbname -r req
[ $? -eq 0 ] || exit 1

# This test checks that master host returned in dbinforesponse matches with
# one in comdb2_cluster system table. List of nodes in dbinforesponse gets
# printed to stderr in debug mode.
master_host=$(CDB2_DEBUG=1 cdb2sql --tabs ${CDB2_OPTIONS} $dbname default "select host from comdb2_cluster where is_master='Y'" 2> cdb2_debug.log)
master_host_dbinfo=$(cat cdb2_debug.log | grep "(master)" | cut -d' ' -f1)
if [[ "${master_host}" == "${master_host_dbinfo}" ]] ; then
    echo "passed"
else
    echo "failed .. master hosts do not match! expected: ${master_host}, got: ${master_host_dbinfo}"
    exit 1
fi

echo
exit 0
