#!/bin/bash

db=$1
${CDB2SQL_EXE} ${CDB2_OPTIONS} $db 'create table testtable1(a int)'

ls -l ${DBDIR}/testtable1* | cut -d' ' -f1 | grep -v -- '-rw-rw---'
if [[ $? -ne 1 ]]; then 
    echo "Incorrect perms, expected -rw-rw---, got:" 
    ls -l ${DBDIR}/testtable1*
    exit 1
fi

${CDB2SQL_EXE} ${CDB2_OPTIONS} $db 'put tunable file_perms 0664'
${CDB2SQL_EXE} ${CDB2_OPTIONS} $db 'create table testtable2(a int)'

ls -l ${DBDIR}/testtable2* | cut -d' ' -f1 | grep -v -- '-rw-rw-r-'
if [[ $? -ne 1 ]]; then 
    echo "Incorrect perms, expected -rw-rw-r-, got:" 
    ls -l ${DBDIR}/testtable2*
    exit 1
fi
