set transaction mode read committed;
set transaction mode blocksql;
set transaction chunk blah;
set transaction chunk 10;
set timeout 200;
set maxquerytime 200;
set timezone UTC;
set datetime precision m;
set user 'mohit';
set password 'blahblah';
set spversion sp1 1;
set prepare_only on;
set readonly on;
set expert on;
set sptrace on;
set spdebug on;
set hasql on;
set cursordebug all;
set verifyretry on;
set queryeffects statement;
set getcost on;
set explain on;
set explain verbose 2;
set maxtransize 10;
set groupconcatmemlimit 100;
set plannereffort 9;
set intransresults on;
set admin on;
set querylimit warn; 
set rowbuffer on;
set remote read;
select 1
