#!/usr/bin/env bash
bash -n "$0" | exit 1

set -e
dbnm=$1

# Make sure we talk to the same host

mach=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "SELECT comdb2_host()"`

if [ "$mach" = "" ]; then
   echo could not retrieve hostname >&2
   exit 1
fi


cdb2sql ${CDB2_OPTIONS} $dbnm default - >/dev/null <<EOF
DROP TABLE IF EXISTS t
CREATE TABLE t (i INTEGER UNIQUE)\$\$
INSERT INTO t (i) SELECT value FROM generate_series(1, 1000)
CREATE PROCEDURE sp {
local function main()
    db:exec("SELECT i FROM t WHERE i > 0 AND i <= 10"):emit();
    db:exec("SELECT i FROM t WHERE i > 10 AND i <= 20"):emit();
end }\$\$
EXEC PROCEDURE sp()
EOF

# Redirect longreqs to standard out
cdb2sql --host $mach $dbnm "EXEC PROCEDURE sys.cmd.send('reql longreqfile <stdout>')" >/dev/null
cdb2sql --host $mach $dbnm "EXEC PROCEDURE sys.cmd.send('reql longsqlrequest 0')" >/dev/null
cdb2sql --host $mach $dbnm "EXEC PROCEDURE sp()" >/dev/null

if [ -n "$CLUSTER" ] ; then
    logfile="$TESTDIR/logs/$dbnm.$mach.db"
else
    logfile="$TESTDIR/logs/$dbnm.db"
fi

# give time for .db file to flush
sleep 1

# ensure we see individual plans from these 2 queries
cnt=`grep -c 'index 0 on table t finds 1 next/prev 10' $logfile`
echo $cnt
if [ $cnt -ne 2 ]; then
    echo 'missing cursor stats???' >&2
    exit 1
fi
grep 'sp_sql=SELECT i FROM t WHERE i > 0 AND i <= 10' $logfile
grep 'sp_sql=SELECT i FROM t WHERE i > 10 AND i <= 20' $logfile

# ensure we have a total plan of the sp
grep 'index 0 on table t finds 2 next/prev 20' $logfile
grep 'rowcount=20, cost=40' $logfile

# Verify that bound paramters are logged correctly
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<EOF
DROP TABLE IF EXISTS t_all_lua_types
CREATE TABLE t_all_lua_types (
    i INTEGER,
    r REAL,
    b BLOB,
    t TEXT,
    dt DATETIME,
    dtus DATETIMEUS,
    ds INTERVALDS,
    dsus INTERVALDSUS,
    ym INTERVALYM
)\$\$
CREATE PROCEDURE alltypes {
local function main()
    declare i    "int";
    declare r    "real";
    declare b    "blob"
    declare t    "cstring"
    declare dt   "datetime"
    declare dtus "datetime"
    declare ds   "intervalds"
    declare dsus "intervalds"
    declare ym   "intervalym"

    i    := 1
    r    := 3.14
    b    := x'CDB2'
    t    := "HELLO WORLD"
    dt   := "1970-01-01T12:34:56.789Z"
    dtus := "1970-01-01T12:34:56.000789Z"
    ds   := 1.234
    dsus := 1.234567
    ym   := 12

    local insert = db:prepare("INSERT INTO t_all_lua_types VALUES(@i, @r, @b, @t, @dt, @dtus, @ds, @dsus, @ym)");
    insert:bind("i", i);
    insert:bind("r", r);
    insert:bind("b", b);
    insert:bind("t", t);
    insert:bind("dt", dt);
    insert:bind("dtus", dtus);
    insert:bind("ds", ds);
    insert:bind("dsus", dsus);
    insert:bind("ym", ym);
    insert:exec();
end }\$\$
EOF


cdb2sql --host $mach $dbnm "EXEC PROCEDURE alltypes()" >/dev/null
grep "param0.*type=int.*len=8.*name=@i.*value=1" $logfile
grep "param1.*type=real.*len=8.*name=@r.*value=3.14" $logfile
grep "param2.*type=blob.*len=2.*name=@b.*value=x'cdb2'" $logfile
grep "param3.*type=cstr.*len=11.*name=@t.*value='HELLO WORLD'" $logfile
grep "param4.*type=datetime.*len=16.*name=@dt.*value=1970-01-01T073456.789 America/New_York" $logfile
grep "param5.*type=datetimeus.*len=16.*name=@dtus.*value=1970-01-01T073456.000789 America/New_York" $logfile
grep "param6.*type=intervalds.*len=32.*name=@ds.*value=0 00:00:01.234" $logfile
grep "param7.*type=intervaldsus.*len=32.*name=@dsus.*value=0 00:00:01.234567" $logfile
grep "param8.*type=intervalym.*len=32.*name=@ym.*value=1-00" $logfile

# Verify that carray paramters are logged correctly
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<EOF
CREATE PROCEDURE sp_carray {
local function main()
    local numbers = {0,1,2,3,4}
    db:column_type('text', 1)
    local stmt = db:prepare('select * from carray(@arr)')
    stmt:bind('arr', numbers)
    stmt:emit()
end }\$\$
EOF
cdb2sql --host $mach $dbnm "EXEC PROCEDURE sp_carray()" >/dev/null
grep "param0.*type=real.*len=40.*name=@arr.*value=carray of length 5" $logfile

exit 0
