#!/usr/bin/env bash
bash -n "$0" | exit 1

set -e

db=$1
echo $db
leader=`cdb2sql --tabs ${CDB2_OPTIONS} $db default 'SELECT host FROM comdb2_cluster WHERE is_master="Y"'`

cdb2sql $db --host $leader "CREATE TABLE t_load_cache_race (i INT)"
cdb2sql $db --host $leader "EXEC PROCEDURE sys.cmd.send('dump_cache')"
cdb2sql $db --host $leader "EXEC PROCEDURE sys.cmd.send('load_cache_delay 1')"
cdb2sql $db --host $leader "EXEC PROCEDURE sys.cmd.send('load_cache')" &
sleep 2
cdb2sql $db --host $leader "TRUNCATE TABLE t_load_cache_race"
wait
