DROP TABLE IF EXISTS t4;
DROP TABLE IF EXISTS t5;

CREATE TABLE t4(x1 SMALLINT, x2 BIGINT, x3 INT, x4 LARGEINT);$$
CREATE TABLE t5(x1 SMALLFLOAT, x2 FLOAT, x3 DOUBLE);$$

SELECT sql FROM sqlite_master WHERE name = 't4';
SELECT sql FROM sqlite_master WHERE name = 't5';

DROP TABLE t4;
DROP TABLE t5;
