#!/usr/bin/env bash
bash -n "$0" | exit 1

dbnm=$1

set -e

# Make sure that all queries go to the same node.
mach=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'select comdb2_host()'`

{ echo 'begin'; sleep 2; echo 'rollback'; } | cdb2sql -s --host $mach ${CDB2_OPTIONS} $dbnm - &
pid=$!

sleep 1
cdb2sql -s --host $mach $dbnm 'select sleep(5)' >/dev/null &
cdb2sql -s --host $mach $dbnm 'select sleep(5)' >/dev/null &

wait $pid
