#!/usr/bin/env bash
bash -n "$0" | exit 1

#set -e
debug=1
[[ "$debug" != 0 ]] && set -x
source ${TESTSROOTDIR}/tools/runit_common.sh

# Testcase variables
unset CLUSTER
DBNAME=ttsz$TESTID
DBDIR=$TESTDIR/$DBNAME
CDB2_CONFIG=$DBDIR/comdb2db.cfg
CDB2_OPTIONS="--cdb2cfg $CDB2_CONFIG"
export dbpid=""

function call_unsetup()
{
    local successful=$1
    COMDB2_UNITTEST=0 $TESTSROOTDIR/unsetup $successful &> $TESTDIR/logs/$DBNAME.unsetup
}

function setup_db()
{
    COMDB2_UNITTEST=0 $TESTSROOTDIR/setup &> $TESTDIR/logs/$DBNAME.setup
}

function create_table()
{
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "create table if not exists t1(a int, b blob)"
    [[ $? != 0 ]] && failexit "Failed to create table t1"
}

function low_size()
{
    echo "Creating an osql/bplog schedule which will allow the temptable to be recycled"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "insert into t1 (a, b) values(1, randomblob(1024*256)), (1, randomblob(1024*256))"
    [[ $? != 0 ]] && failexit "Failed to insert into table t1"

    lsofout=$(lsof -p $dbpid | egrep deleted | awk '{print $7}')
    for sz in $lsofout ; do
        [[ "$sz" -eq "65536" ]] && failexit "recreated small temptable"
        [[ "$sz" -gt "1048576" ]] && failexit "large temptable persisted"
    done
    echo "Temptable system correctly retained small temptables"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "exec procedure sys.cmd.send('temptable_clear')"
}

function high_size()
{
    echo "Creating an osql/bplog schedule which will recreate the temptable"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "insert into t1 (a, b) values(1, randomblob(1024*1024)), (1, randomblob(1024*1024))"
    [[ $? != 0 ]] && failexit "Failed to insert into table t1"

    lsofout=$(lsof -p $dbpid | egrep deleted | awk '{print $7}')
    for sz in $lsofout ; do
        [[ "$sz" -gt "1048576" ]] && failexit "large temptable persisted"
        [[ "$sz" -ne "65536" ]] && failexit "Failed to recreate temptable"
    done
    echo "Temptable system correctly recreated large temptables"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "exec procedure sys.cmd.send('temptable_clear')"
}

function analyze_leak()
{
    echo "Maybe there are open temptables going into this test?"
    lsofout=$(lsof -p $dbpid | egrep deleted)
    [[ -n "$lsofout" ]] && failexit "Found open temptables before analyze leak test"

    echo "Creating an index with ulonglong so analyze will fail"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "put tunable forbid_ulonglong = 'off'"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "create table ull { schema { u_longlong u blob b }}"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "create index idx on ull(u)"
    j=0
    while [[ $j -lt 100 ]]; do
        $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "insert into ull (u, b) select *, randomblob(16) from generate_series(1, 1000)"
        [[ $? != 0 ]] && failexit "Failed to insert into table ull"
        let j=j+1
    done
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME - << 'EOF'
@bind CDB2_INTEGER a -1
insert into ull (u, b) values (@a, randomblob(16));
EOF
    sleep 2

    echo "This would have created temptables - clear them now"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "exec procedure sys.cmd.send('temptable_clear')"

    echo "Make sure we don't any open temptables"
    lsofout=$(lsof -p $dbpid | egrep deleted)

    if [[ -n "$lsofout" ]] ; then
        while :; do 
            echo "Waiting for temptables to be cleared"
            $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "exec procedure sys.cmd.send('temptable_clear')"
            sleep 1
            lsofout=$(lsof -p $dbpid | egrep deleted)
            [[ -z "$lsofout" ]] && break
        done
    fi
    
    echo "Analyze should fail, but we should not leak a temptable"
    x=$($CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "analyze ull 100")
    [[ $? == 0 ]] && failexit "Analyze worked against high ulonglong"

    echo "We should STILL not have any open temptables"
    lsofout=$(lsof -p $dbpid | egrep deleted)

    if [[ -n "$lsofout" ]] ; then
        while :; do 
            echo "Waiting for temptables to be cleared"
            $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME "exec procedure sys.cmd.send('temptable_clear')"
            sleep 1
            lsofout=$(lsof -p $dbpid | egrep deleted)
            [[ -z "$lsofout" ]] && break
        done
    fi

    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME - << 'EOF'
put tunable forbid_ulonglong = 'on'
EOF
}

function run_test()
{
    analyze_leak
    low_size
    high_size
}

# Trap to call_unsetup if the test exits
trap "call_unsetup \"0\"" INT EXIT

setup_db
dbpid=$(cat ${TMPDIR}/${DBNAME}.pid)
create_table
run_test
call_unsetup 1

echo "Success"
