#!/usr/bin/env bash
set -x
for t in *.req; do
    cdb2sql --tabs --script --cdb2cfg ${CDB2_CONFIG} ${1} default - 2> ${t}.output 1>&2 < ${t}
    set -e
    diff ${t}.expected ${t}.output
    set +e
done
