SET TIMEZONE UTC
CREATE TABLE lhs (i INTEGER)$$
CREATE TABLE rhs (i INTEGER, dt DATETIME)$$
INSERT INTO lhs VALUES (1), (2), (3)
INSERT INTO rhs VALUES (2, '2021-03-05')
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
SELECT CASE WHEN dt IS NULL THEN '1970-01-01' ELSE dt END AS dt FROM lhs LEFT JOIN rhs ON lhs.i = rhs.i ORDER BY dt DESC
