#!/usr/bin/env bash
bash -n "$0" | exit 1

#export debug=1
[[ $debug == "1" ]] && set -x

export STOPFILE=stopfile.txt

. ${TESTSROOTDIR}/tools/write_prompt.sh
. ${TESTSROOTDIR}/tools/ddl.sh

function select_from_t
{
    timeout 8m yes "select * from t limit 1" | $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default>/dev/null 2>&1
}

function select_from_metrics
{
    timeout 8m yes "select name, type, value, collection_type from comdb2_metrics order by case when name = 'start_time' then 0 else 1 end" | $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default>/dev/null 2>&1
}

function schema_change_loop
{
    while [[ ! -f $STOPFILE ]]; do
        $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default "rebuild t" >/dev/null 2>&1
        $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default "create table t2(a int)" >/dev/null 2>&1
        $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default "drop table t2" >/dev/null 2>&1
    done
}

function run_test
{
    rm $STOPFILE 2>/dev/null
    create_table t
    $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default "insert into t select value from generate_series(1, 1000)"

    j=0
    while [[ $j -lt 15 ]]; do
        select_from_t &
        let j=j+1
    done

    j=0
    while [[ $j -lt 3 ]]; do
        select_from_metrics &
        let j=j+1
    done

    sleep 500
    touch $STOPFILE
    wait
}

run_test
$CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default "select 1"
