1 [create table test1 (i int primary key, j int)]
done
2 [create table test2 (i int primary key, j int)]
done
1 [insert into test1 values (1, 1)]
(rows inserted=1)
done
2 [insert into test2 values (1, 1)]
(rows inserted=1)
done
1 [begin]
done
1 [update test1 set j = j + 1]
done
2 [update test1 set j = j + 1]
(rows updated=1)
done
1 [commit]
[commit] failed with rc 2 find old record failed unable to update record rc = 4
done
1 [select * from test1]
(i=1, j=2)
done
1 [begin]
done
1 [update test1 set j = j + 1]
done
2 [update test1 set j = j + 1]
(rows updated=1)
done
1 [truncate test2]
done
1 [commit]
[commit] failed with rc 2 find old record failed unable to update record rc = 4
done
1 [select * from test1]
(i=1, j=3)
done
1 [select * from test2]
(i=1, j=1)
done
2 [update test1 set j = j - 1]
(rows updated=1)
done
1 [begin]
done
1 [truncate test2]
done
1 [update test1 set j = j + 1]
done
2 [update test1 set j = j + 1]
(rows updated=1)
done
1 [commit]
[commit] failed with rc 2 find old record failed unable to update record rc = 4
done
1 [select * from test1]
(i=1, j=3)
done
1 [select * from test2]
(i=1, j=1)
done
1 [begin]
done
1 [update test1 set j = j + 1]
done
2 [update test1 set j = j + 1]
(rows updated=1)
done
1 [commit]
[commit] failed with rc 2 find old record failed unable to update record rc = 4
done
1 [select * from test1]
(i=1, j=4)
done
1 [begin]
done
1 [update test1 set j = j + 1]
done
1 [truncate test2]
done
2 [create index idx on test2(j)]
done
1 [commit]
[commit] failed with rc 240 stale version for table:test2 master:1 replicant:0
done
1 [select * from test1]
(i=1, j=4)
done
1 [select * from test2]
(i=1, j=1)
done
