#!/usr/bin/env bash
bash -n "$0" | exit 1

dbnm=$1
echo adding table
cdb2sql -s ${CDB2_OPTIONS} $dbnm default "drop table t" &> /dev/null
cdb2sql -s ${CDB2_OPTIONS} $dbnm default "create table t  { `cat t.csc2 ` }" > /dev/null

yes 'insert into t values(1)' | head -2000 > insert.sql
 
echo inserting 2000 records
cdb2sql -s ${CDB2_OPTIONS} -f insert.sql $dbnm default &> insert.out1 &
cdb2sql -s ${CDB2_OPTIONS} -f insert.sql $dbnm default &> insert.out2 &

wait
cdb2sql ${CDB2_OPTIONS} $dbnm default "select count(*) from t" >output.actual
diff output.actual output.expect
if [[  $? -ne 0 ]]
then
echo "Failed."
exit 1
fi
echo "Passed."
