Creating comdb2_logical_cron table
Creating partition 1 and 2
[
 {
  "NAME"      : "testpart1",
  "PERIOD"    : "manual",
  "RETENTION" : 2,
  "START"     : "1",
  "SHARD0NAME": "t1",
  "TABLES"    :
  [
  {
   "TABLENAME"    : "t1",
  }
  ]
 }
],
 {
  "NAME"      : "testpart2",
  "PERIOD"    : "manual",
  "RETENTION" : 2,
  "START"     : "10",
  "SHARD0NAME": "t2",
  "TABLES"    :
  [
  {
   "TABLENAME"    : "t2",
  }
  ]
 }
]
(name='testpart1', period='manual', retention=2, nshards=1, version=0, shard0name='t1')
(name='testpart2', period='manual', retention=2, nshards=1, version=0, shard0name='t2')
(name='testpart1', shardname='t1')
(name='testpart2', shardname='t2')
(name='timepart_cron', type='WALLTIME', running=0, nevents=0, description='Time partition scheduler')
(name='Global Job Scheduler', type='WALLTIME', running=0, nevents=0, description='Default cron scheduler')
(name='testpart1', type='LOGICAL', running=0, nevents=1, description='Logical cron testpart1 clock 0')
(name='testpart2', type='LOGICAL', running=0, nevents=1, description='Logical cron testpart2 clock 0')
(name='AddShard', type='testpart1', epoch=1, arg1='testpart1', arg2=NULL, arg3=NULL)
(name='AddShard', type='testpart2', epoch=10, arg1='testpart2', arg2=NULL, arg3=NULL)
[
 {
  "NAME"      : "testpart1",
  "PERIOD"    : "manual",
  "RETENTION" : 2,
  "START"     : "1",
  "SHARD0NAME": "t1",
  "TABLES"    :
  [
  {
   "TABLENAME"    : "t1",
  }
  ]
 }
],
 {
  "NAME"      : "testpart2",
  "PERIOD"    : "manual",
  "RETENTION" : 2,
  "START"     : "10",
  "SHARD0NAME": "t2",
  "TABLES"    :
  [
  {
   "TABLENAME"    : "t2",
  }
  ]
 }
]
(name='testpart1', period='manual', retention=2, nshards=1, version=0, shard0name='t1')
(name='testpart2', period='manual', retention=2, nshards=1, version=0, shard0name='t2')
(name='testpart1', shardname='t1')
(name='testpart2', shardname='t2')
(name='timepart_cron', type='WALLTIME', running=0, nevents=0, description='Time partition scheduler')
(name='Global Job Scheduler', type='WALLTIME', running=0, nevents=0, description='Default cron scheduler')
(name='testpart1', type='LOGICAL', running=0, nevents=1, description='Logical cron testpart1 clock 0')
(name='testpart2', type='LOGICAL', running=0, nevents=1, description='Logical cron testpart2 clock 0')
(name='AddShard', type='testpart1', epoch=1, arg1='testpart1', arg2=NULL, arg3=NULL)
(name='AddShard', type='testpart2', epoch=10, arg1='testpart2', arg2=NULL, arg3=NULL)
(name='testpart1', value=0)
