ifeq ($(MAKEFILE_COMMON_INCLUDED),)
export BUILDSFX?=build
export BUILDDIR?=$(shell readlink -f $(SRCHOME)/$(BUILDSFX))
export TESTSBUILDDIR?=$(BUILDDIR)/tests/tools/
export TESTID?=$(shell $(TESTSROOTDIR)/tools/get_random.sh)
export TESTDIRPFX?=$(TESTSROOTDIR)
export TESTDIR?=$(TESTDIRPFX)/test_$(TESTID)
export COMDB2AR_EXE?=${BUILDDIR}/tools/comdb2ar/comdb2ar
export COMDB2_EXE?=${BUILDDIR}/db/comdb2
export CDB2SQL_EXE?=${BUILDDIR}/tools/cdb2sql/cdb2sql
export COPYCOMDB2_EXE?=${BUILDDIR}/db/copycomdb2
export CDB2DUMP_EXE?=${BUILDDIR}/db/cdb2_dump
export CDB2_SQLREPLAY_EXE?=${BUILDDIR}/tools/cdb2_sqlreplay/cdb2_sqlreplay
export PMUX_EXE?=${BUILDDIR}/tools/pmux/pmux
export pmux_port?=5105
export MAKEFILE_COMMON_INCLUDED=1

# See logic in setup
ifeq ($(PMUXPORT),)
export pmux_cmd="${PMUX_EXE} -l"
else
export pmux_socket=/tmp/pmux.socket.$PMUXPORT
export pmux_port_range="-r $((pmux_port+1)):$((pmux_port+200))"
export pmux_cmd="${PMUX_EXE} -l -p ${PMUXPORT} -b ${pmux_socket} ${pmux_port_range}"
endif
endif
