#!/usr/bin/env bash
bash -n "$0" | exit 1

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

run_test() {
    local test_input_file_name=$1 output_file_extension=$2 extra_cdb2sql_opts=$3

    local test_name
    test_name=$(echo ${test_input_file_name} | cut -d "." -f 1)

    local exp_output_file_name=${test_name}${output_file_extension}.expected
    local output_file_name=${test_name}${output_file_extension}.output

    local cmd="cdb2sql -s -f ${test_input_file_name} ${CDB2_OPTIONS} ${extra_cdb2sql_opts} ${dbname} default "
    echo $cmd "> ${output_file_name}"
    $cmd 2>&1 | perl -pe "s/.n_writeops_done=([0-9]+)/rows inserted='\1'/; s/BLOCK2_SEQV2\(824\)/BLOCK_SEQ(800)/; s/OP #2 BLOCK_SEQ/OP #3 BLOCK_SEQ/;" > ${output_file_name}

    cmd="diff ${exp_output_file_name} ${output_file_name}"
    ${cmd} > /dev/null

    if [[  $? -eq 0 ]]; then
        echo "passed ${test_name}"
    else
        echo "failed ${test_name}"
        echo "see diffs here: ${HOSTNAME}"
        echo "> diff -u ${PWD}/{${exp_output_file_name},${output_file_name}}"
        echo
        exit 1
    fi
}

main() {
    local test_input_file_name

    for test_input_file_name in `find . -name 't[0-9][0-9].sql' -exec basename {} \;` ; do
        run_test "${test_input_file_name}"
    done

    for test_input_file_name in `find . -name 't[0-9][0-9].tab.sql' -exec basename {} \;` ; do
        run_test "${test_input_file_name}" ".tab" "-tabular"
    done

    for test_input_file_name in `find . -name 't[0-9][0-9].multiline.sql' -exec basename {} \;` ; do
        run_test "${test_input_file_name}" ".multiline" "-l"
    done
}

main
exit 0
