#!/usr/bin/env bash
bash -n "$0" | exit 1

set -e
#set -x

dbnm=$1

if [ "x$dbnm" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

failexit()
{
    echo "Failed $1"
    exit -1
}


output=run.log

echo "create t1"
cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t1 (a int) "

cdb2sql -s ${CDB2_OPTIONS} $dbnm default "explain insert into t1 values (1)" > ${output} 2>&1

testcase_output=$(cat $output)
expected_output=$(cat $output.exp)

# verify 
if [[ "$testcase_output" != "$expected_output" ]]; then

    echo "  ^^^^^^^^^^^^"
    echo "The test has failed!!!"
    echo " "
    echo "Use 'diff <expected-output> <my-output>' to see why:"
    echo "> diff ${PWD}/{$output.exp,$output}"
    echo " "
    diff $output.exp $output
    echo " "
    exit 1

fi

