#!/usr/bin/env bash
bash -n "$0" | exit 1

export CDB2_OPTIONS="${CDB2_OPTIONS} --cost"
export CDB2SQL_EXE="stdbuf -oL $CDB2SQL_EXE" # force unbuffered stdout

${TESTSROOTDIR}/tools/compare_results.sh -d $1
[ $? -eq 0 ] || exit 1
exit 0
