#!/bin/bash

dbname=$1
n_cyc=$2

a_scale=3
b_scale=7
c_scale=17
d_scale=29

n_uniq=$(($a_scale * b_scale * c_scale * d_scale))
n_recs=$(($n_uniq * n_cyc))

function addrecs {
    table=$1
    st=0

    a=$((st % a_scale))
    b=$((st % b_scale))
    c=$((st % c_scale))
    d=$((st % d_scale))

    i=0
    trancount=0

    echo "BEGIN"
    while [[ $i -lt $n_recs ]]; do
        echo "insert into t${table} values($a, $b, $c, $d)"
        a=$(((a+1) % a_scale))
        b=$(((b+1) % b_scale))
        c=$(((c+1) % c_scale))
        d=$(((c+1) % d_scale))
        i=$(($i+1))
        trancount=$((trancount+1))
        if [[ $trancount -gt 2000 ]] ; then
            echo "COMMIT"
            echo "BEGIN"
            trancount=0
        fi
    done
    echo "COMMIT"
}

for table in 1 2 3; do 
    addrecs $table | $CDB2SQL_EXE ${CDB2_OPTIONS} $dbname default - >/dev/null 2>&1 &
done
wait
