#!/bin/bash
bash -n "$0" | exit 1

set -x
################################################################################

# debug=1

# args
a_dbn=$1

TMPDIR=${TMPDIR:-/tmp}
export PATH=${PATH}:.

# find input files
files=$( find . -type f -name \*.req | sort )

# counter 
nfiles=0

# last batch
last_batch=

# post-process
pproc=cat

# testcase output
testcase_output=

# expected output
expected_output=

# fastinit
function fastinit
{
    # print debug trace
    [[ "$debug" == "1" ]] && set -x

    # args
    typeset db=$1
    typeset iter=$2
    typeset tbl

    # flagged?
    if [[ ! -f $iter.fastinit ]]; then
        return 0
    fi

    # fastinit
    for tbl in $(cat $iter.fastinit) ; do
        echo "$CDB2SQL_EXE ${CDB2_OPTIONS} $db default \"truncate $tbl\""
        $CDB2SQL_EXE ${CDB2_OPTIONS} $db default "truncate $tbl"
    done

    return 0
}


# run tool
function runtool
{
    # print debug trace
    [[ "$debug" == "1" ]] && set -x

    # args
    typeset tool=$1
    typeset args=$2
    typeset db=$3
    typeset log=$4

    # run
    echo "> $tool \"$args\" $db > $log 2>&1"
    $tool "$args" $db > $log 2>&1
}

# runstepper
function runstepper
{
    # print debug trace
    [[ "$debug" == "1" ]] && set -x

    # args
    typeset db=$1
    typeset tcs=$2
    typeset log=$3

    # teststepper
    typeset stp=${TESTSROOTDIR}/tools/stepper

    # echo
    echo "> $stp $db $tcs $log"

    # execute
    $stp $db $tcs $log
}

function comdb2dumpcsc {
    $CDB2SQL_EXE --tabs ${CDB2_OPTIONS} $a_dbn default "select name from sqlite_master where type='table' and name not like '%sqlite_stat%'"
}

function init {
    for table in $(comdb2dumpcsc ); do
        $CDB2SQL_EXE ${CDB2_OPTIONS} $a_dbn default "drop table $table"
    done
    $CDB2SQL_EXE ${CDB2_OPTIONS} $a_dbn default 'create table t1 {
schema 
{
        int a
        int b
        int c
        int d
}

keys 
{
dup     "a" = a
dup     "b" = b
dup     "c" = c
dup     "d" = d
}
}
'
$CDB2SQL_EXE ${CDB2_OPTIONS} $a_dbn default 'create table t2 {
schema 
{
    int a
    int b
    int c
    int d
}

keys 
{
    dup     "ab" = a + b
    dup     "bc" = b + c
    dup     "cd" = c + d
}
}
'
$CDB2SQL_EXE ${CDB2_OPTIONS} $a_dbn default 'create table t3 {
schema 
{
    int a
    int b
    int c
    int d
}

keys 
{
    dup     "abc" = a + b + c
    dup     "bcd" = b + c + d
}
}
'
}


init


# Iterate through input files
for testcase in $files ; do

    # increment counter
    let nfiles=nfiles+1

    # cleanup testcase
    testcase=${testcase##*/}
    
    # see if the prefix has changed
    new_batch=${testcase%%_*}

    # set output
    output=$testcase.res
    
    # fastinit if requested
    if [[ $new_batch != $last_batch ]] ; then

        fastinit $a_dbn $new_batch
        last_batch=$new_batch

    fi

    # Check for run-stepper
    if [[ -f $new_batch.runstepper ]] ; then

        runstepper $a_dbn $testcase $output

    elif [[ -f $new_batch.tool ]] ; then

        tool=$( cat $new_batch.tool )
        args=$( cat $new_batch.args )
        runtool $tool "$args" $a_dbn $output

    else

        # Be verbose
        cmd="$CDB2SQL_EXE ${CDB2_OPTIONS} $a_dbn default - < $testcase > $output 2>&1"
        echo $cmd

        # run command
        eval $cmd

    fi

    # post-process
    if [[ -f $new_batch.post ]]; then

        # zap file
        > $output.postprocess

        # collect post-processing tool
        pproc=$(cat $new_batch.post)

        # post-process output
        $pproc $output >> $output.postprocess

        # copy post-processed output to original
        mv $output.postprocess $output
    fi

    # get testcase output
    testcase_output=$(cat $output)

    # get expected output
    expected_output=$(cat $testcase.out)

    # verify 
    if [[ "$testcase_output" != "$expected_output" ]]; then
        # print message 
        echo "  ^^^^^^^^^^^^"
        echo "The above testcase (${testcase}) has failed!!!" 
        echo " "
        echo "Use 'diff <expected-output> <my-output>' to see why:"
        echo "> diff ${PWD}/{$testcase.out,$output}"
        echo " "
        diff $testcase.out $output
        echo " "
        exit 1
        
    fi

done

echo "Testcase passed."
