#!/usr/bin/env bash
bash -n "$0" | exit 1

# Remote cursor moves testcase for comdb2
################################################################################


# we rely on the following global variables to be set
echo "main db vars"
vars="TESTCASE DBNAME DBDIR TESTSROOTDIR TESTDIR CDB2_OPTIONS CDB2_CONFIG SECONDARY_DB SECONDARY_DBDIR SECONDARY_DB_CDB2_CONFIG SECONDARY_DB_CDB2_OPTIONS"
for required in $vars; do
    q=${!required}
    echo "$required=$q" 
    if [[ -z "$q" ]]; then
        echo "$required not set" >&2
        exit 1
    fi
done

#generate testscripts in new files
files=`ls *.req.src`
for file in $files ; do
   newfile=${file%%.src}
   sed "/^insert /!s/ t$/ LOCAL_$DBNAME.t/g" $file > $newfile.tmp
   sed "/^insert /!s/ t / LOCAL_$DBNAME.t /g" $newfile.tmp > $newfile
   rm $newfile.tmp
done


#run tests
echo "Starting tests"
./remsql_curmoves.sh $DBNAME $CDB2_CONFIG $SECONDARY_DB $SECONDARY_DBDIR $TESTDIR 
result=$?

if (( $result != 0 )) ; then
   echo "FAILURE"
   exit 1
fi


echo "SUCCESS"
