#!/usr/bin/env bash
bash -n "$0" | exit 1

if [[ -z "$CLUSTER" ]]; then
    echo "Skipping for non-clustered"
    exit 0
fi

if [[ $# -ne 1 ]]; then
    echo Usage: dbname
    exit 1
fi

TMPDIR=${TMPDIR:-/tmp}
dbname=$1

host=$(cdb2sql -tabs -s ${CDB2_OPTIONS} $dbname default "select host from comdb2_cluster where is_master='N' limit 1")


(
sleep 5
if [[ $myhost = $host ]]; then
    cdb2sql -s ${CDB2_OPTIONS} $dbname local "exec procedure sys.cmd.send('exit')" >/dev/null
else
    ssh $host "$(which cdb2sql) -s ${CDB2_OPTIONS} $dbname local \"exec procedure sys.cmd.send('exit')\"" >/dev/null
fi
) &

cdb2sql --host $host -s ${CDB2_OPTIONS} $dbname default <<'EOF'
drop table if exists t;
create table t(a int);$$
begin;
insert into t values(1);
select sleep(15);
insert into t values(1);
commit;
EOF

count=$(cdb2sql -s ${CDB2_OPTIONS} -tabs $dbname default "select count(*) from t")
if [[ $count -eq 2 ]]; then
    echo Passed
    exit 0
else
    echo "Failed: count $count, expected 2"
    exit 1
fi
