#!/usr/bin/env bash
bash -n "$0" | exit 1

# Grab my database name.
dbnm=$1

cdb2sql ${CDB2_OPTIONS} $dbnm default "truncate t1"

echo "Testing serial"
${TESTSBUILDDIR}/serial -d $dbnm -s

ret=$?

if [[ $ret != 0 ]] ; then

    echo "Serializable failed, ret=$ret."
    exit $ret

fi

echo "Serial passed"
