#!/bin/sh

bash -n "$0" | exit 1
dbnm=$1

pgrep cdb2sockpool
if [ $? -ne 0 ]; then
    echo 'SOCKPOOL IS REQUIRED TO RUN THE TEST.' >&2
    echo 'TRY TO BRING UP SOCKPOOL'
    ${BUILDDIR}/tools/cdb2sockpool/cdb2sockpool
    sleep 1
    pgrep cdb2sockpool
    if [ $? -ne 0 ]; then
        echo 'FAILED THE ATTEMPT.' >&2
        exit 1
    fi
fi
${TESTSBUILDDIR}/nowritetimeout $dbnm
rc=$?
pkill cdb2sockpool
exit $rc
