#!/usr/bin/env bash

# Remote cursor moves testcase for comdb2
################################################################################

# args
# <dbname> <dbdir> <testdir> <autodbname> <autodbnum> <cluster>
echo "main db vars"
vars="TESTCASE DBNAME DBDIR TESTSROOTDIR TESTDIR CDB2_OPTIONS CDB2_CONFIG SECONDARY_DBNAME SECONDARY_DBDIR SECONDARY_CDB2_CONFIG SECONDARY_CDB2_OPTIONS"
for required in $vars; do
    q=${!required}
    echo "$required=$q" 
    if [[ -z "$q" ]]; then
        echo "$required not set" >&2
        exit 1
    fi
done

#run tests
echo "Starting tests"
echo ./writes_remsql_names.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $DBDIR $TESTDIR
./writes_remsql_names.sh $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $DBDIR $TESTDIR
#echo ./writes_remsql_names.sh $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBNAME $SECONDARY_DBDIR $TESTDIR
#./writes_remsql_names.sh $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG $DBNAME $SECONDARY_DBDIR $TESTDIR
result=$?

if (( $result == 0 )) ; then
   successful=1
fi

if (( $result != 0 )) ; then
   echo "FAILURE"
   exit 1
fi


echo "SUCCESS"
