#!/usr/bin/env bash

# Remote cursor moves testcase for comdb2
################################################################################

# args
# <dbname> <dbdir> <testdir> <autodbname> <autodbnum> <cluster>
echo "main db vars"
vars="TESTCASE DBNAME DBDIR TESTSROOTDIR TESTDIR CDB2_OPTIONS CDB2_CONFIG"
for required in $vars; do
    q=${!required}
    echo "$required=$q" 
    if [[ -z "$q" ]]; then
        echo "$required not set" >&2
        exit 1
    fi
done

dbname=$1
srcdbname=srcdb$DBNAME
dbdir=$DBDIR
testdir=$TESTDIR
cdb2config=$CDB2_CONFIG

DBNAME=$srcdbname
DBDIR=$TESTDIR/$DBNAME
#effectively srcdb config -- needed to setup srcdb
CDB2_CONFIG=$DBDIR/comdb2db.cfg
CDB2_OPTIONS="--cdb2cfg $CDB2_CONFIG"


#setup remote db
$TESTSROOTDIR/setup &> $TESTDIR/logs/$DBNAME.setup


#run tests
echo "Starting tests"
echo ./writes_remsql_names.sh $dbname $cdb2config $srcdbname $dbdir $testdir
./writes_remsql_names.sh $dbname $cdb2config $srcdbname $dbdir $testdir
result=$?

if (( $result == 0 )) ; then
   successful=1
fi

$TESTSROOTDIR/unsetup $successful &> $TESTDIR/logs/$DBNAME.unsetup



if (( $result != 0 )) ; then
   echo "FAILURE"
   exit 1
fi


echo "SUCCESS"
DBNAME=$
SRCDBNAME=srcdb$DBNAME
DBDIR=srcdb$DBDIR
