#!/usr/bin/env bash
bash -n "$0" | exit 1

# This test demonstrates a case where ufid_hash would hold an open
# DB handle to an outdated btree file, after schema change, hence prevent
# the file from being deleted.
#
# 1. send flush
# 2. write to table
# 3. bounce a replicant
#   3.1. replicant will start matching from the LSN in step 1
#   3.2. replicant will run recovery to apply transaction from step 2
#   3.3. ufid-hash will need to open a DB handle on the btree file
# 4. truncate table, this creates new btree file
# 5. delfiles now will create "deleted" file on this replicant;
#    alternatively, if we upgrade master to this replicant and then run delfiles,
#    we'll get "DB_FILEOPEN: Rename or remove while file is open"

source ${TESTSROOTDIR}/tools/cluster_utils.sh

[ -z "${CLUSTER}" ] && { echo "Test requires a cluster"; exit 0; }

dbnm=$1

replicant=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select comdb2_host()"`
master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select host from comdb2_cluster where is_master='Y'"`

cdb2sql ${CDB2_OPTIONS} $dbnm default "CREATE TABLE t1 (i integer, b blob)"
sleep 2 # wait for the checkpoint thread to do its 1st checkpoint
cdb2sql $dbnm --host $master "EXEC PROCEDURE sys.cmd.send('bdb checkpoint')"
sleep 2 # wait for the async checkpoint to finish

cdb2sql ${CDB2_OPTIONS} $dbnm default "TRUNCATE TABLE t1"
cdb2sql $dbnm --host $master "EXEC PROCEDURE sys.cmd.send('bdb checkpoint')"
sleep 2 # wait for the async checkpoint to finish

cdb2sql ${CDB2_OPTIONS} $dbnm default "INSERT INTO t1 VALUES(1, x'CDB2BABE')"
sleep 2

echo "Restarting node $replicant ..."
kill_restart_node $replicant 10 1
cdb2sql $dbnm --host $replicant "SELECT 1"
if [ $? -ne 0 ]; then
    echo 'db not up?' >&2
    exit 1
fi

echo 'Before truncate ...'
cdb2sql $dbnm --host $replicant "EXEC PROCEDURE sys.cmd.send('bdb cachestatall')" | grep -A1 blobs0
cdb2sql $dbnm --host $master "TRUNCATE TABLE t1"
echo 'After truncate ...'
cdb2sql $dbnm --host $replicant "EXEC PROCEDURE sys.cmd.send('bdb cachestatall')" | grep -A1 blobs0

echo "Waiting for $replicant to become new master"
while true; do
    is_replicant_new_master=`cdb2sql --tabs $dbnm --host $replicant "SELECT comdb2_host() = (select host from comdb2_cluster where is_master='Y')"`
    if [ "$is_replicant_new_master" = "1" ]; then
        master=$replicant
        break
    fi

    master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select host from comdb2_cluster where is_master='Y'"`
    cdb2sql $dbnm --host $master "EXEC PROCEDURE sys.cmd.send('upgrade $replicant')"
    sleep 5
    master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select host from comdb2_cluster where is_master='Y'"`
    echo "Master swung to $master"

    while true; do
        cdb2sql $dbnm --host $replicant "SELECT 1" >/dev/null
        if [ $? -eq 0 ]; then
            break;
        fi
        sleep 1
    done
done

cdb2sql -tabs $dbnm --host $master "EXEC PROCEDURE sys.cmd.send('delfiles t1')" | grep 'DB_FILEOPEN: Rename or remove while file is open'
if [ $? -eq 0 ]; then
    echo "DB handles leaked" >&2
    exit 1
fi

echo "Success!"
exit 0
