#!/usr/bin/env bash
bash -n "$0" | exit 1

# This test case is a collection of queries reported in various 
# DRQS tickets. As such each one will have different schemas.
# The driver will just add/alter tables as required.

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

echo $CLUSTER

if [[ -z "$CLUSTER" ]]; then
   cdb2sql -s ${CDB2_OPTIONS} -f sleep20.req $dbname default &
else
	for node in $CLUSTER; do
           cdb2sql -s ${CDB2_OPTIONS} --host $node -f sleep20.req $dbname &
	done
fi

sleep 1

testname='t00'
echo preparing db for $testname
cdb2sql -s ${CDB2_OPTIONS} -f t00.req $dbname default > $testname.output 2>&1
echo "diff $testname.expected $testname.output >/dev/null"
diff $testname.expected $testname.output >/dev/null
if [[  $? -eq 0 ]]; then
    echo "passed $testname"
else
    echo "failed $testname"
    exit 1
fi

sleep 20

echo $CLUSTER

if [[ -z "$CLUSTER" ]]; then
    cdb2sql -s ${CDB2_OPTIONS} -f sleep5.req $dbname default &
else
	for node in $CLUSTER; do
            cdb2sql -s ${CDB2_OPTIONS} --host $node -f sleep5.req $dbname &
	done
fi

sleep 2

testname='t10'
echo preparing db for $testname
cdb2sql -s ${CDB2_OPTIONS} -f t10.req $dbname default > $testname.output 2>&1
echo "diff $testname.expected $testname.output >/dev/null"
diff $testname.expected $testname.output >/dev/null
if [[  $? -eq 0 ]]; then
    echo "passed $testname"
else
    echo "failed $testname"
    exit 1
fi

exit 0
