#!/usr/bin/env bash
bash -n "$0" | exit 1

# remote db config
REM_CDB2_OPTIONS="--cdb2cfg ${SECONDARY_CDB2_CONFIG}"

output=run.log
echo "Populating remote database" >> $output 
cdb2sql --tabs ${REM_CDB2_OPTIONS} $SECONDARY_DBNAME default - >> $output 2>&1 << EOF
create table t1(a int)\$\$
insert into t1 select * from generate_series(1,10)
EOF

echo "Creating aliases" >> $output
cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default - >> $output 2>&1 << EOF
put alias t1_alias1 'LOCAL_${SECONDARY_DBNAME}.t1'
put alias t1_alias2 'LOCAL_${SECONDARY_DBNAME}.t1'
put alias t1_alias3 'LOCAL_${SECONDARY_DBNAME}.t1'
exec procedure sys.cmd.send('stat alias')
EOF

echo "Trying to overwrite alias should fail" >> $output
cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default - >> $output 2>&1 << EOF
put alias t1_alias1 'LOCAL_${SECONDARY_DBNAME}.blah'
EOF

echo "Create alias to non-existent remote table should succeed" >> $output
cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default - >> $output 2>&1 << EOF
put alias invalid_alias 'LOCAL_${SECONDARY_DBNAME}.blah'
select * from invalid_alias
EOF

echo "Select using alias name" >> $output
cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default - >> $output 2>&1 << EOF
select * from t1_alias1
select * from t1_alias2
select * from t1_alias3
EOF


echo "Dropping an alias" >> $output
cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default - >> $output 2>&1 << EOF
put alias t1_alias1 ''
exec procedure sys.cmd.send('stat alias')
EOF

echo "Select using deleted alias" >> $output
cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default - >> $output 2>&1 << EOF
select * from t1_alias1
EOF

#get rid of remdb name
sed "s/${SECONDARY_DBNAME}/remdb/g" $output > run.log.actual

testcase_output=$(cat run.log.actual)
expected_output=$(cat output.log.actual)
if [[ "$testcase_output" != "$expected_output" ]]; then

   # print message 
   echo "  ^^^^^^^^^^^^"
   echo "The above testcase (${testcase}) has failed!!!" 
   echo " "
   echo "Use 'diff <expected-output> <my-output>' to see why:"
   echo "> diff ${PWD}/{output.log.actual,run.log.actual}"
   echo " "
   diff output.log.actual run.log.actual
   echo " "

   # quit
   exit 1
fi

echo "Testcase passed."
