CREATE TABLE t1(i INT) $$
BEGIN;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
COMMIT;

SET maxtransize 5;
BEGIN;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
COMMIT;

SELECT COUNT(*) FROM t1;
