CREATE TABLE t1(i INT) $$

SET maxtransize 2;
BEGIN;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
COMMIT;

BEGIN;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
COMMIT;

SELECT COUNT(*)=2 FROM t1;

TRUNCATE TABLE t1;

SET TRANSACTION READ COMMITTED;
BEGIN;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
COMMIT;

BEGIN;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(1);
COMMIT;

SELECT COUNT(*)=2 FROM t1;

DROP TABLE t1;
