#!/usr/bin/env bash
bash -n "$0" | exit 1

dbnm=$1

# Know where we'll be connecting to
host=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'SELECT comdb2_host()'`
echo "host is $host"
# Turn on test switch
cdb2sql $dbnm --host $host 'EXEC PROCEDURE sys.cmd.send("get_tmp_dir_sleep 1")'
cdb2sql $dbnm --host $host 'SELECT randomblob(1024*512) AS b FROM generate_series(1,1024) ORDER BY b' >/dev/null 2>actual &
sleep 6
cdb2sql $dbnm --host $host 'SELECT randomblob(1024*512) AS b FROM generate_series(1,1024) ORDER BY b' >/dev/null 2>actual
diff actual expected
