#!/usr/bin/env bash
bash -n "$0" | exit 1

set -x
source ${TESTSROOTDIR}/tools/runit_common.sh

# Debug variable
debug=0

dbnm=$1

if [ "x$dbnm" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

# Number of insert_records function calls
nins=0


assert_vers()
{
    local loc_tbl=$1
    local target=$2
    local newver=$(cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select table_version('$loc_tbl')")
    if [[ $newver != $target ]] ; then
        failexit "newver is now $newver but should be $target"
    fi
}

assert_schema()
{
    tbl=$1
    schema=$2

    echo "make sure that the current schema is $schema"
    cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select csc2 from sqlite_master where name='$tbl'" | sed 's/ \(schema\)/\1/;s/} /}/' > schema.out

    if ! diff -Bw schema.out $schema ; then 
        cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'select * from sqlite_master' > sqlite_master.out
        failexit "final schema is not same as $schema: diff schema.out $schema"
    fi
}

cdb2sql ${CDB2_OPTIONS} $dbnm default "@send debg 10000"
cdb2sql ${CDB2_OPTIONS} $dbnm default "@send ndebg 10000"

cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t2 (i int primary key, upd_count int default 0, data blob, orig_i int)"

max=10000
strt=1
end=0
delta=10
while [ $end -lt $max ] ; do
    let end=strt+$delta-1
    cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t2(i) select * from generate_series($strt,$end)" > ins.out
    rc=$?
    if [ $rc -ne 0 ] ; then
        failexit "Failure from insert "
    fi
    echo "(rows inserted=$delta)" > ins.exp
    if ! diff ins.out ins.exp ; then
        failexit "Error with the insert"
    fi
    let strt=$end+1

    res=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select count(*) from t2"`
    assertres $res $end
done

#set orig_i column before updating colum i values
cdb2sql ${CDB2_OPTIONS} $dbnm default "update t2 set orig_i=i where 1"

strt=1
end=0
delta=10
while [ $end -lt $max ] ; do
    let end=strt+$delta-1
    cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t2 where i >=$strt and i<= $end" > sel.out

    res=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select count(*) from t2 where i >=$strt and i<= $end"`
    assertres $res $delta

    cdb2sql ${CDB2_OPTIONS} $dbnm default "update t2 set i=i-1, upd_count=upd_count+1, data = randomblob(16) where i >=$strt and i<= $end" > upd.out
    rc=$?
    if [ $rc -ne 0 ] ; then
        failexit "Failure from update "
    fi


    echo "(rows updated=$delta)" > upd.exp
    if ! diff upd.out upd.exp ; then
        cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t2 where orig_i >=$strt and orig_i<= $end" > sel_orig_i.out
        failexit "Error with the insert see sel_orig_i.out"
    fi
    let strt=$end+1
done


cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t2 where upd_count!=1" > sel2.out

if [ `wc -c sel2.out | cut -f1 -d' '` -ne 0 ] ; then 
    failexit "Some rows were not updated once, see sel2.out"
fi


echo "Success"
