#!/usr/bin/env bash
bash -n "$0" | exit 1

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi


for testreq in `ls t*.req` ; do
    # Setup all the tables this test case needs :-
    # First drop the table (its ok if this fails,
    # the table probably doesn't exist).
    # Then add the table.
    testname=`echo $testreq | cut -d "." -f 1`
    echo preparing db for $testname
    for schema in `ls $testname.*.csc2 2> /dev/null` ; do
        table=`echo $schema | cut -d "." -f2`

        cmd="cdb2sql ${CDB2_OPTIONS} $dbname default \"drop $table\""
        echo $cmd
        $cmd > /dev/null 2>&1

        cmd="cdb2sql ${CDB2_OPTIONS} $dbname default \"create table $table { `cat $schema` }\" "
        echo $cmd
        eval $cmd > create.log
    done

    cmd="cdb2sql -s -f $testreq ${CDB2_OPTIONS} $dbname default "
    echo $cmd "> $testname.output"
    $cmd 2>&1 | perl -pe "s/.n_writeops_done=([0-9]+)/rows inserted='\1'/; s/BLOCK2_SEQV2\(824\)/BLOCK_SEQ(800)/; s/OP #2 BLOCK_SEQ/OP #3 BLOCK_SEQ/;" > $testname.output
    cmd="diff $testname.expected $testname.output"
    $cmd > /dev/null

    if [[  $? -eq 0 ]]; then
        echo "passed $testname"
    else
        echo "failed $testname"
        echo "see diffs here: $HOSTNAME"
        echo "> diff ${PWD}/{$testname.expected,$testname.output}"
        echo
        exit 1
    fi
done
echo
exit 0
