#!/usr/bin/env bash
bash -n "$0" | exit 1

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

for testreq in `ls t*.sql` ; do
    testname=`echo $testreq | cut -d "." -f 1`
    #cmd="cdb2sql --tabs -s -f $testreq ${CDB2_OPTIONS} $dbname default "
    cmd="cdb2sql -s -f $testreq ${CDB2_OPTIONS} $dbname default "
    echo $cmd "> $testname.output"
    $cmd 2>&1 | perl -pe "s/.n_writeops_done=([0-9]+)/rows inserted='\1'/; s/BLOCK2_SEQV2\(824\)/BLOCK_SEQ(800)/; s/OP #2 BLOCK_SEQ/OP #3 BLOCK_SEQ/;" > $testname.output

    cmd="diff $testname.expected $testname.output"
    $cmd > /dev/null

    if [[  $? -eq 0 ]]; then
        echo "passed $testname"
    else
        echo "failed $testname"
        echo "see diffs here: $HOSTNAME"
        echo "> diff ${PWD}/{$testname.expected,$testname.output}"
        diff ${PWD}/{$testname.expected,$testname.output}
        echo
        exit 1
    fi
done
echo
exit 0
