#!/usr/bin/env bash
bash -n "$0" | exit 1

[[ $debug == "1" ]] && set -x

export background_writer_pid=0
export sleeptime=5

# Grab my database name.
dbnm=$1

function write_prompt
{
    typeset func=$1
    echo "[$func] $2"
}

function kill_background_writer
{
    [[ $debug == "1" ]] && set -x
    typeset func="kill_background_writer"
    [[ "$background_writer_pid" -gt 0 ]] && kill -9 $background_writer_pid
}

function failexit
{
    [[ $debug == "1" ]] && set -x
    typeset func="failexit"
    typeset f=$1
    kill_background_writer
    write_prompt $func "$f failed: $2"
    exit -1
}

function get_master
{
    [[ $debug == "1" ]] && set -x
    typeset func="get_master"
    typeset tries=$total_tries
    $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default "exec procedure sys.cmd.send(\"bdb cluster\")" | grep MASTER | cut -f1 -d":" | tr -d '[:space:]'
}

function create_table
{
    [[ $debug == "1" ]] && set -x
    typeset func="create_table"
    typeset tbl=$1
    typeset cmd="create table $tbl(a int, b blob)"
    write_prompt $func "executing $func"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "create table $tbl(a int, b blob)" 
    write_prompt $func "$cmd"
}

function background_writer
{
    [[ $debug == "1" ]] && set -x
    typeset func="background_writer"
    write_prompt $func "executing $func"
    while :; do 
        x=$($CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "insert into t1 select *, x'11' from generate_series limit 1000" 2>&1)
        write_prompt $func "$x"
        sleep 1
    done
}

function start_background_writer
{
    [[ $debug == "1" ]] && set -x
    typeset func="start_background_writer"
    write_prompt $func "executing $func"
    background_writer &
    export background_writer_pid=$!
    sleep $sleeptime
}

function blobstripe
{
    [[ $debug == "1" ]] && set -x
    typeset func="blobstripe"
    typeset master=$(get_master)
    write_prompt $func "executing $func"
    $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME -host $master "exec procedure sys.cmd.send('morestripe blobstripe')"
    sleep $sleeptime
}

function morestripe
{
    [[ $debug == "1" ]] && set -x
    typeset func="morestripe"
    typeset master=$(get_master)
    write_prompt $func "executing $func $1"
    $CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME -host $master "exec procedure sys.cmd.send('morestripe $1')"
    sleep $sleeptime
}

function count
{
    [[ $debug == "1" ]] && set -x
    typeset func="count"
    typeset tbl=${1:-t1}
    #write_prompt $func "executing $func"
    x=$($CDB2SQL_EXE -tabs $CDB2_OPTIONS $DBNAME default "select count(*) from $tbl")
    #write_prompt $func "$x"
    echo "$x"
}

function run_blobstripe_test
{
    [[ $debug == "1" ]] && set -x
    typeset func="run_blobstripe_test"
    write_prompt $func "executing $func"
    create_table bstripe
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "insert into bstripe select *, x'11' from generate_series limit 1000" 2>/dev/null
    blobstripe
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "insert into bstripe select *, x'11' from generate_series limit 1000" 2>/dev/null
    x=$(count bstripe)
    [[ "$x" == "2000" ]] || failexit "incorrect count for bstripe, $x"
    x=$($CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "select * from bstripe" | egrep -c -v 11)
    [[ "$x" == "0" ]] || failexit "incorrect blobs for blobstripe"
}

function run_test
{
    [[ $debug == "1" ]] && set -x
    typeset func="run_test"
    write_prompt $func "executing $func"
    create_table t1
    start_background_writer
    count >/dev/null
    morestripe 2
    count >/dev/null
    morestripe 4
    count >/dev/null
    morestripe 8
    count >/dev/null
    morestripe 16
    count >/dev/null
    kill_background_writer
}

run_blobstripe_test
run_test
echo "Success"
