#!/usr/bin/env bash

dbnm=$1

# Get a host for DIRECT_CPU mode.
host=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'SELECT comdb2_host()'`
echo $host

# Make sure sockpool is running.
pgrep cdb2sockpool
if [ $? -ne 0 ]; then
    echo 'SOCKPOOL IS REQUIRED TO RUN THE TEST BUT IS NOT RUNNING.' >&2
    echo 'TRYING TO BRING IT UP'
    ${BUILDDIR}/tools/cdb2sockpool/cdb2sockpool
    sleep 1
    pgrep cdb2sockpool
    if [ $? -ne 0 ]; then
        echo 'FAILED BRINGING UP SOCKPOOL' >&2
        exit 1
    fi
fi

# Give sockpool a bit time to bootstrap.
sleep 2

echo 'closeall' >/tmp/msgtrap.sockpool

# Make sure we don't read garbage config file.
strace cdb2sql $dbnm --host $host 'SELECT 1' 2>&1 | grep 'null.*cfg'
if [ $? -eq 0 ]; then
    echo 'SHOULD NOT READ GARBAGE CONFIG FILE.' >&2
    exit 1
fi

# Make sure we don't query pmux if using a cached connection.
strace cdb2sql $dbnm --host $host 'SELECT 1' 2>&1 | grep '\<5105\>'
if [ $? -eq 0 ]; then
    echo 'SHOULD NOT QUERY PMUX IF USING A CACHED CONNECTION.' >&2
    echo "IS THE SOCKPOOL TYPESTR comdb2/$dbnm/$host/cdb2sql/dc TOO LONG?" >&2
    exit 1
fi
