#!/usr/bin/env bash
bash -n "$0" | exit 1

################################################################################

# args
a_dbn=$1

set -e

cdb2sql ${CDB2_OPTIONS} $a_dbn default "create table t1 { `cat t1.csc2 ` }"

./decimal.sh ${a_dbn}

echo "No index test was successful"

cdb2sql ${CDB2_OPTIONS} $a_dbn default "drop table t1"
cdb2sql ${CDB2_OPTIONS} $a_dbn default "create table t1 {`cat t1ix.csc2` }"

./decimal.sh ${a_dbn}

echo "Index test was successful"

echo "Testcase passed."
