(rows inserted=1)
[insert into t1 (id, d32) values (1, "0.0")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (2, "-0.0")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (3, "0e0")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (4, "-0e0")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (5, "1")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (6, "-1")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (7, "1.0")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (8, "10e-1")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (9, "0.1e10")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (10, NULL)] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (11, "12.345e56")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (12, "9999999e89")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (13, "-9999999e89")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (14, "0.000001e-95")] rc 0
(rows inserted=1)
[insert into t1 (id, d32) values (15, "-0.000001e-95")] rc 0
(id=10, d32=NULL, d64=NULL, d128=NULL)
(id=13, d32='-9.999999E+95', d64=NULL, d128=NULL)
(id=6, d32='-1', d64=NULL, d128=NULL)
(id=15, d32='-1E-101', d64=NULL, d128=NULL)
(id=1, d32='0.0', d64=NULL, d128=NULL)
(id=2, d32='-0.0', d64=NULL, d128=NULL)
(id=3, d32='0', d64=NULL, d128=NULL)
(id=4, d32='-0', d64=NULL, d128=NULL)
(id=14, d32='1E-101', d64=NULL, d128=NULL)
(id=5, d32='1', d64=NULL, d128=NULL)
(id=7, d32='1.0', d64=NULL, d128=NULL)
(id=8, d32='1.0', d64=NULL, d128=NULL)
(id=9, d32='1E+9', d64=NULL, d128=NULL)
(id=11, d32='1.2345E+57', d64=NULL, d128=NULL)
(id=12, d32='9.999999E+95', d64=NULL, d128=NULL)
[select * from t1 order by d32,id] rc 0
