#!/usr/bin/env bash
$CDB2SQL_EXE $SP_OPTIONS - <<'EOF'
CREATE TABLE IF NOT EXISTS t (i INT)$$
CREATE TABLE IF NOT EXISTS u (i INT)$$
CREATE TABLE IF NOT EXISTS v (i INT)$$
CREATE TABLE IF NOT EXISTS w (i INT)$$
CREATE PROCEDURE lox VERSION 'test' {
local function check_table_locks()
    local sql = "select count(*) c from comdb2_locks where "..
                "locktype like 'TABLELOCK%' and "..
                "object in ('t', 'u', 'v', 'w')"
    local c = db:exec(sql):fetch().c
    db:emit(c)
    return c
end
local function main()
    local t = db:prepare("select * from t")
    local uv = db:prepare("select * from u, v")
    local w = db:prepare("select * from w")
    if check_table_locks() ~= 4 then return -201 end

    db:recover_ddlk()
    if check_table_locks() ~= 4 then return -202 end

    w:close()
    if check_table_locks() ~= 4 then return -203 end

    -- only active stmts will acquire table locks
    db:recover_ddlk()
    if check_table_locks() ~= 3 then return -204 end

    w = db:prepare("select * from w")
    if check_table_locks() ~= 4 then return -205 end

    db:recover_ddlk()
    if check_table_locks() ~= 4 then return -206 end

    t:close()
    uv:close()
    w:close()
    if check_table_locks() ~= 4 then return -207 end

    db:recover_ddlk()
    if check_table_locks() ~= 0 then return -208 end

    return 0
end}$$
EXEC PROCEDURE lox()
EOF
