#!/bin/sh
bash -n "$0" | exit 1

set -e
dbnm=$1

# Make sure we talk to the same host
mach=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "SELECT comdb2_host()"`

if [ "$mach" = "" ]; then
   echo could not retrieve hostname >&2
   exit 1
fi

# Setting long request threshold to 0 so we can easily get queries in longreqs.
cdb2sql --host $mach $dbnm "EXEC PROCEDURE sys.cmd.send('reql longreqfile <stdout>')"
cdb2sql --host $mach $dbnm "EXEC PROCEDURE sys.cmd.send('reql longrequest 0')"
cdb2sql --host $mach $dbnm "EXEC PROCEDURE sys.cmd.send('reql longsqlrequest 0')"

# Run queries
cdb2sql --host $mach $dbnm "SELECT 1" >/dev/null
cdb2sql --host $mach $dbnm "SELECT 1+1" >/dev/null

logfile=
if [ -n "$CLUSTER" ] ; then
    logfile="$TESTDIR/logs/$dbnm.$mach.db"
else
    logfile="$TESTDIR/logs/$dbnm.db"
fi

# These change every time sqlite changes: just regenerate
cat $logfile

#grep 'dcb8d104a3fd67913c7d509dbdbe2051' $logfile # SELECT 1
#grep 'f628909f02fd3d8f69c90bcd77c732a5' $logfile # SELECT 1+1

grep '57d3bf4a162583e33381d79f2deac343' $logfile # SELECT 1
grep 'fdf53d1d2812dbce0f56bf5b10369c1a' $logfile # SELECT 1+1


# Compare results with pre-calculated hashes
echo "Passed."
exit 0 
