#!/usr/bin/env bash

bash -n "$0" | exit 1
dbnm=$1

nrecs=10000

host=`cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'SELECT comdb2_host()'`

cdb2sql ${CDB2_OPTIONS} --host $host $dbnm "create table t (i int)"
cdb2sql ${CDB2_OPTIONS} --host $host $dbnm "exec procedure sys.cmd.send('debug tcmtest nettest enable osql queuefull')"
cdb2sql ${CDB2_OPTIONS} --host $host $dbnm "insert into t select * from generate_series limit $nrecs"

cnt=$(cdb2sql -tabs ${CDB2_OPTIONS} $dbnm default "select count(*) from t")

if [[ $cnt != $nrecs ]] ; then
    echo "count is now $cnt but should be $nrecs"
    echo "Failed"
    exit -1
fi

echo "Success"
