#!/usr/bin/env bash
bash -n "$0" | exit 1

set -e
PATH=.:${PATH}

set -x

# Grab my database name.
dbnm=$1

# Verify that the user at least supplied a dbname
if [[ -z "$dbnm" ]]; then

    echo "Testcase requires <dbname> argument."
    exit 1

fi

# Tasks
numtasks=${2:-15}

# Iterations
iterations=${3:-25000}

# Send error pragma
if [[ -n "$4" ]] ; then
    errpragma='-e'
else
    errpragma=''
fi


cdb2sql ${CDB2_OPTIONS} $dbnm default "truncate book"

# Driver 
driver=${TESTSBUILDDIR}/sirace

i=0

function errquit
{
    typeset msg=$1
    typeset cnt=0

    echo "ERROR: $msg"
    echo "Testcase failed."

    while [[ $cnt -lt $numtasks ]]; do

        [[ ${bkpid[$cnt]} != "-1" ]] && kill -9 ${bkpid[$cnt]} >/dev/null 2>&1
        bkpid[$cnt]=-1
        let cnt=cnt+1

    done
}

trap "errquit \"Cancelling test\"" INT EXIT

# Run tasks
while (( i < numtasks )) ; do
    $driver -d $dbnm -i $i -m $iterations $errpragma &
    bkpid[$i]=$!
    let i=i+1
done

running=1

while (( $running > 0 )) ; do

    running=0
    i=0

    while (( i < numtasks )) ; do

        pid=${bkpid[$i]}
        if [[ $pid != -1 ]]; then
            if ps -p $pid >/dev/null 2>&1 ; then
                let running=running+1
            else
                wait $pid
                if [[ $? != 0 ]]; then
                    errquit "Failed snapshot race test."
                    return 1
                fi
                bkpid[$i]=-1
            fi
        fi
        let i=i+1
    done
    sleep 1
done

trap - INT EXIT

echo "Success!"
