#!/usr/bin/env bash
bash -n "$0" | exit 1

dbname=$1
j0=0 ; j1=0 ; j2=0 ; err=0

# fastinit
echo "Fastinit"
cdb2sql ${CDB2_OPTIONS} $dbname default "truncate t1"
sleep 1

# Start test
echo "Start insert loop 1"
while [[ $j0 -lt 6000 ]]; do
    cdb2sql ${CDB2_OPTIONS} $dbname default "insert into t1(a) values ($j0)" >> insert.loop1.out 2>&1 
    r=$? ; if [[ $r != 0 ]]; then echo "Error on insert iteration $j0, rc=$r" ; exit 1 ; fi
    let j0=j0+1
done &
j0p=$!

sleep 5

echo "Start update loop 1"
while [[ $j1 -lt 1000 ]]; do
    cdb2sql ${CDB2_OPTIONS} $dbname default "update t1 set a = a + 1 limit 100" >> update.loop1.out 2>&1 
    r=$? ; if [[ $r != 0 ]]; then echo "Error on update loop 1 iteration $j1, rc=$r" ; exit 1 ; fi
    let j1=j1+1
done &
j1p=$!

sleep 5

echo "Start update loop 2"
while [[ $j2 -lt 1000 ]]; do
    cdb2sql ${CDB2_OPTIONS} $dbname default "update t1 set a = a + 1 limit 100" >> update.loop2.out 2>&1 
    r=$? ; if [[ $r != 0 ]]; then echo "Error on update loop 2 iteration $j2, rc=$r" ; exit 1 ; fi
    let j2=j2+1
done &
j2p=$!

wait $j0p ; let err=err+$?
wait $j1p ; let err=err+$?
wait $j2p ; let err=err+$?

if [[ "$err" != 0 ]]; then
    echo "Testcase failed"
    exit 1
fi

echo "Success"
