(rows inserted=1)
[insert into t1 values (1234, 1234, 1234, 1234)] rc 0
(rows inserted=1)
[insert into t1 values (4321, 4321, 1234, 1234)] rc 0
(rows inserted=1)
[insert into t1 values (1321, 1321, 1234, null) -- Non default, no NULL contraint.] rc 0
[insert into t1 values (1121, 1121, null, null) --  NULL constraint, column 3 can not be NULL.] failed with rc 4 Null constraint violation for column 'dup_value' on table 't1'. null constraint error data .ONDISK->.ONDISK 'null constraint violation from bint4 field 'dup_value' to bint4 field 'dup_value' for table 't1'' unable to add record rc = 318
(uuid=1234, value=1234, dup_value=1234, allowed_null_value=1234)
(uuid=1321, value=1321, dup_value=1234, allowed_null_value=NULL)
(uuid=4321, value=4321, dup_value=1234, allowed_null_value=1234)
[select * from t1 order by uuid] rc 0
