(rows inserted=1)
[insert into t1 values (1234, 1234, 1234, 1234)] rc 0
(rows inserted=1)
[insert into t1 values (4321, 4321, 1234, 1234)] rc 0
(rows inserted=1)
[insert into t1 values (1321, 1321, 1234, null) -- Non default, no NULL contraint.] rc 0
(rows inserted=1)
[insert into t3 values (1234, 1121)] rc 0
(rows deleted=1)
[delete from t1 where value = 1234 -- Foreign key contraint, cascade delete.] rc 0
(uid=1321, value=1321, dup_value=1234, allowed_null_value=NULL)
(uid=4321, value=4321, dup_value=1234, allowed_null_value=1234)
[select * from t1 order by uid] rc 0
[select * from t3 order by uid -- should have no record.] rc 0
