(rows inserted=1)
[insert into t1 values (1234, 1234, 1234, 1234)] rc 0
(rows inserted=1)
[insert into t1 values (4321, 4321, 1234, 1234)] rc 0
(rows inserted=1)
[insert into t1 values (1321, 1321, 1234, null) -- Non default, no NULL contraint.] rc 0
(rows inserted=1)
[insert into t4 values (1234, 1121)] rc 0
(rows updated=1)
[update t1 set uuid = 566 where value = 1234 -- Foreign key contraint, cascade update.] rc 0
(uuid=566, value=1234, dup_value=1234, allowed_null_value=1234)
(uuid=1321, value=1321, dup_value=1234, allowed_null_value=NULL)
(uuid=4321, value=4321, dup_value=1234, allowed_null_value=1234)
[select * from t1 order by uuid] rc 0
(uuid=566, value=1121)
[select * from t4 order by uuid -- should have updated the t4 entries.] rc 0
