(rows inserted=1)
[insert into t1 values (1, 1234, 1234, null)] rc 0
(rows inserted=1)
[insert into t1 values (2, 4321, 1234, null)] rc 0
(rows inserted=1)
[insert into t4 values (1, 1121)] rc 0
(rows inserted=1)
[insert into t4 values (2, 2221)] rc 0
[set transaction read committed] rc 0
[begin] rc 0
[update t1 set uid = 3 where uid = 1] rc 0
[update t1 set uid = 1 where uid = 2] rc 0
[update t1 set uid = 2 where uid = 3] rc 0
[commit] rc 0
(uid=1, value=4321, dup_value=1234, allowed_null_value=NULL)
(uid=2, value=1234, dup_value=1234, allowed_null_value=NULL)
[select * from t1 where uid in (1,2,3)] rc 0
(uid=1, value=1121)
(uid=2, value=2221)
[select * from t4 where uid in (1,2,3)] rc 0
