(rows inserted=1)
[insert into t1(uid, value, dup_value) values(8888, 1, 1)] rc 0
(rows inserted=1)
[insert into t4(uid, value) values(8888, 2)] rc 0
(rows updated=1)
[update t1 set uid = 8887 where uid = 8888] rc 0
(uid=8887, value=1)
[select uid, value from t1 where uid > 8000 and uid < 9000] rc 0
(uid=8887, value=2)
[select uid, value from t4 where uid > 8000 and uid < 9000] rc 0
[rebuild t1] rc 0
(rows updated=1)
[update t1 set uid = 8889 where uid = 8887] rc 0
(uid=8889, value=1)
[select uid, value from t1 where uid > 8000 and uid < 9000] rc 0
(uid=8889, value=2)
[select uid, value from t4 where uid > 8000 and uid < 9000] rc 0
(rows inserted=1)
[insert into t1(uid, value, dup_value) values(8886, 3, 1)] rc 0
(rows inserted=1)
[insert into t3(uid, value) values(8886, 3)] rc 0
(rows deleted=1)
[delete from t1 where uid = 8886] rc 0
[select uid, value from t3] rc 0
