[create table t5  { schema
{
  int uid
  int uida
  int uidb
  int uidc
  int uidd
  int uide
  int value
}

keys
{
    "UID1"      = uid
    "UID2"      = uida
    "UID3"      = uidb
    "UID4"      = uidc
    "UID5"      = uidd
    "UID6"      = uide
}

constraints
{
    "UID1" -> <"t1":"UID"> on delete cascade
    "UID1" -> "t2":"UID1"
    UID1 -> t2:UID1
    "UID2" -> "t1":"UID" on update cascade on delete restrict
    "UID2" -> <"t2":"UID1">
    "UID3" -> <"t1":"UID"> <"t2":"UID1">
    "UID4" -> <"t1":"UID"> <"t2":"UID1"> on delete cascade
    //Need to add tbl first then alter with this line : "UID5" -> "t5":"UID6"
}
}] rc 0
[insert into t5(uid, uida, uidb, uidc, uidd, uide, value) values(1,1,1,1,1,1,1)] failed with rc 3 Transaction violates foreign key constraint t5(uid) -> t2(uid): key value does not exist in parent table
(rows inserted=1)
[insert into t2(uid, value) values(1,1)] rc 0
(rows inserted=1)
[insert into t5(uid, uida, uidb, uidc, uidd, uide, value) values(1,1,1,1,1,1,1)] rc 0
[insert into t5(uid, uida, uidb, uidc, uidd, uide, value) values(1,2,1,1,1,1,1)] failed with rc 299 add key constraint duplicate key 'UID1' on table 't5' index 0
(rows deleted=1)
[delete from t5 where uid = 1] rc 0
[insert into t5(uid, uida, uidb, uidc, uidd, uide, value) values(1,2,1,1,1,1,1)] failed with rc 3 Transaction violates foreign key constraint t5(uida) -> t2(uid): key value does not exist in parent table
[create table t6  { schema
{
  int uid
  int uida
  int uidb
  int uidc
  int uidd
  int uide
  int value
}

keys
{
    "UID1"      = uid
    "UID2"      = uida
    "UID3"      = uidb
    "UID4"      = uidc
    "UID5"      = uidd
    "UID6"      = uide
}

constraints
{
    "UID1" -> <"t1":"UID"> on delete cascade
    "UID1" -> "t2":"UID1"
    UID1 -> t2:UID1
    "UID2" -> "t1":"UID" on update cascade on delete restrict
    "UID2" -> <"t2":"UID1">
    "UID3" -> "t1":"UID" "t2":"UID1" //no angle brackets -- should fail
}
}] failed with rc 240 ERROR at line  28: syntax error: :
