[create table m {schema{int i}}] rc 0
[alter table m {schema{int i}}] rc 0
[alter table m {schema{int i}}] rc 0
[drop table m] rc 0
[create table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[alter table c {schema{int i}}] rc 0
[drop table c] rc 0
("transactional create (bad case)"='transactional create (bad case)')
[select "transactional create (bad case)"] rc 0
[begin] rc 0
[create table c {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[create table m {schema{int i} keys{"pk" = i}}] rc 0
[commit] failed with rc 240 constraint error for table "c" key "key" -> <"m":"pk">: foreign table not found
("transactional create"='transactional create')
[select "transactional create"] rc 0
[begin] rc 0
[create table m {schema{int i} keys{"pk" = i}}] rc 0
[create table c {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[commit] rc 0
[insert into c values (1)] failed with rc 3 verify key constraint cannot resolve constraint table 'c' key 'key' -> table 'm' index '0' key 'pk'
(rows inserted=1)
[insert into m values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(i=1)
[select * from m] rc 0
(i=1)
(i=1)
(i=1)
[select * from c] rc 0
[truncate m] failed with rc 240 Can't fastinit tables with foreign constraints
[drop table m] failed with rc 240 Can't drop tables with foreign constraints
(i=1)
[select * from m] rc 0
(i=1)
(i=1)
(i=1)
[select * from c] rc 0
("transactional truncate"='transactional truncate')
[select "transactional truncate"] rc 0
[begin] rc 0
[truncate c] rc 0
[truncate m] rc 0
[commit] rc 0
[select * from m] rc 0
[select * from c] rc 0
(rows inserted=1)
[insert into m values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
("transactional drop & truncate (bad case)"='transactional drop & truncate (bad case)')
[select "transactional drop & truncate (bad case)"] rc 0
[begin] rc 0
[truncate c] rc 0
[drop table m] rc 0
[commit] failed with rc 240 Can't drop tables with foreign constraints
(i=1)
[select * from m] rc 0
(i=1)
(i=1)
(i=1)
[select * from c] rc 0
("transactional drop & truncate (good case)"='transactional drop & truncate (good case)')
[select "transactional drop & truncate (good case)"] rc 0
[begin] rc 0
[drop table c] rc 0
[truncate m] rc 0
[commit] rc 0
[select * from m] rc 0
[select * from c] failed with rc -3 no such table: c
[begin] rc 0
[drop table if exists c] rc 0
[drop table if exists m] rc 0
[commit] rc 0
[begin] rc 0
[create table m {schema{int i} keys{"pk" = i}}] rc 0
[create table c {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[commit] rc 0
("transactional drop (bad case)"='transactional drop (bad case)')
[select "transactional drop (bad case)"] rc 0
[begin] rc 0
[drop table m] rc 0
[drop table c] rc 0
[commit] failed with rc 240 Can't drop tables with foreign constraints
(1=1)
[select 1] rc 0
[select * from m] rc 0
[select * from c] rc 0
("transactional drop (good case)"='transactional drop (good case)')
[select "transactional drop (good case)"] rc 0
[begin] rc 0
[drop table c] rc 0
[drop table m] rc 0
[commit] rc 0
[select * from m] failed with rc -3 no such table: m
[select * from c] failed with rc -3 no such table: c
[begin] rc 0
[create table m {schema{int i} keys{"pk" = i}}] rc 0
[create table c {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[create table d {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[commit] rc 0
("transactional alter (bad case 1)"='transactional alter (bad case 1)')
[select "transactional alter (bad case 1)"] rc 0
[alter table m {schema{int i}}] failed with rc 240 constraint error for table "d" key "key" -> <"m":"pk">: foreign key not found
("transactional alter (bad case 2)"='transactional alter (bad case 2)')
[select "transactional alter (bad case 2)"] rc 0
[begin] rc 0
[alter table m {schema{int i}}] rc 0
[alter table c {schema{int i} keys{dup "key" = i}}] rc 0
[commit] failed with rc 240 constraint error for table "d" key "key" -> <"m":"pk">: foreign key not found
("transactional alter (bad case 3)"='transactional alter (bad case 3)')
[select "transactional alter (bad case 3)"] rc 0
[begin] rc 0
[alter table c {schema{int i} keys{dup "key" = i}}] rc 0
[alter table m {schema{int i}}] rc 0
[commit] failed with rc 240 constraint error for table "d" key "key" -> <"m":"pk">: foreign key not found
("transactional alter (bad case 4)"='transactional alter (bad case 4)')
[select "transactional alter (bad case 4)"] rc 0
[begin] rc 0
[alter table c {schema{int i} keys{dup "key" = i}}] rc 0
[alter table m {schema{int i}}] rc 0
[alter table d {schema{int i} keys{dup "key" = i}}] rc 0
[commit] failed with rc 240 constraint error for table "d" key "key" -> <"m":"pk">: foreign key not found
("transactional alter (good case)"='transactional alter (good case)')
[select "transactional alter (good case)"] rc 0
[begin] rc 0
[alter table c {schema{int i} keys{dup "key" = i}}] rc 0
[alter table d {schema{int i} keys{dup "key" = i}}] rc 0
[alter table m {schema{int i}}] rc 0
[commit] rc 0
("transactional alter & add (good case)"='transactional alter & add (good case)')
[select "transactional alter & add (good case)"] rc 0
[begin] rc 0
[alter table m {schema{int i} keys{"pk" = i}}] rc 0
[alter table c {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[alter table d {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[create table e {schema{int i} keys{dup "key" = i} constraints{"key" -> <"m" : "pk">}}] rc 0
[commit] rc 0
("transactional alter & drop (bad case)"='transactional alter & drop (bad case)')
[select "transactional alter & drop (bad case)"] rc 0
[begin] rc 0
[drop table c] rc 0
[drop table d] rc 0
[alter table m {schema{int i}}] rc 0
[drop table e] rc 0
[commit] failed with rc 240 constraint error for table "e" key "key" -> <"m":"pk">: foreign key not found
("transactional alter & drop (good case)"='transactional alter & drop (good case)')
[select "transactional alter & drop (good case)"] rc 0
[begin] rc 0
[drop table c] rc 0
[drop table d] rc 0
[drop table e] rc 0
[alter table m {schema{int i}}] rc 0
[commit] rc 0
("tests for self referenced schema"='tests for self referenced schema')
[select "tests for self referenced schema"] rc 0
("add self-referenced bad 1"='add self-referenced bad 1')
[select "add self-referenced bad 1"] rc 0
[create table s {schema{int i int j} keys{dup "i" = i dup "j" = j} constraints{"k" -> <"s" : "i">}}] failed with rc 240 constraint error for table "s" key "k" -> <"s":"i">: local key not found
("add self-referenced bad 2"='add self-referenced bad 2')
[select "add self-referenced bad 2"] rc 0
[create table s {schema{int i int j} keys{dup "i" = i dup "j" = j} constraints{"j" -> <"s" : "k">}}] failed with rc 240 constraint error for table "s" key "j" -> <"s":"k">: foreign key not found
("add self-referenced good"='add self-referenced good')
[select "add self-referenced good"] rc 0
[create table s {schema{int i int j} keys{dup "i" = i dup "j" = j} constraints{"j" -> <"s" : "i">}}] rc 0
("truncate self-referenced"='truncate self-referenced')
[select "truncate self-referenced"] rc 0
[truncate s] rc 0
("alter self-referenced drop constraints"='alter self-referenced drop constraints')
[select "alter self-referenced drop constraints"] rc 0
[alter table s {schema{int i int j}}] rc 0
("alter self-referenced bad 1"='alter self-referenced bad 1')
[select "alter self-referenced bad 1"] rc 0
[alter table s {schema{int i int j} keys{dup "i" = i dup "j" = j} constraints{"k" -> <"s" : "i">}}] failed with rc 240 constraint error for table "s" key "k" -> <"s":"i">: local key not found
("alter self-referenced bad 2"='alter self-referenced bad 2')
[select "alter self-referenced bad 2"] rc 0
[alter table s {schema{int i int j} keys{dup "i" = i dup "j" = j} constraints{"j" -> <"s" : "k">}}] failed with rc 240 constraint error for table "s" key "j" -> <"s":"k">: foreign key not found
("alter self-referenced good"='alter self-referenced good')
[select "alter self-referenced good"] rc 0
[alter table s {schema{int i int j} keys{dup "i" = i dup "j" = j} constraints{"j" -> <"s" : "i">}}] rc 0
("drop self-referenced table"='drop self-referenced table')
[select "drop self-referenced table"] rc 0
[drop table s] rc 0
