[drop table if exists c] rc 0
[drop table if exists p] rc 0
[create table p {schema{int i} keys{"pki" = i}}] rc 0
[create table c {schema{int i} keys{"cki" = i} constraints{"cki" -> <"p" : "pki"> on update cascade on delete cascade }}] rc 0
(rows inserted=1)
[insert into p values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(comment='the following transacion should fail with dup on c.key')
[select "the following transacion should fail with dup on c.key" as comment] rc 0
[begin] rc 0
[insert into c values (1)] rc 0
[delete from p where i = 1] rc 0
[commit] failed with rc 299 add key constraint duplicate key 'CKI' on table 'c' index 0
(i=1)
[select * from c] rc 0
(i=1)
[select * from p] rc 0
(comment='the following transacion should fail with dup on c.key')
[select "the following transacion should fail with dup on c.key" as comment] rc 0
[begin] rc 0
[insert into c values (1)] rc 0
[update p set i = i+i where i = 1] rc 0
[commit] failed with rc 299 add key constraint duplicate key 'CKI' on table 'c' index 0
(i=1)
[select * from c] rc 0
(i=1)
[select * from p] rc 0
