[drop table if exists p] rc 0
[drop table if exists c] rc 0
[create table p {schema{int i} keys{"pki" = i}}] rc 0
[create table c {schema{int i} keys{"cki" = i} constraints{"cki" -> <"p" : "pki"> on update cascade on delete cascade }}] rc 0
(rows inserted=1)
[insert into p values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(comment='the following transacion should fail with dup on c.key')
[select "the following transacion should fail with dup on c.key" as comment] rc 0
[begin] rc 0
[insert into c values (1)] rc 0
[delete from p where i = 1] rc 0
[commit] failed with rc 299 add key constraint duplicate key 'CKI' on table 'c' index 0
(i=1)
[select * from c] rc 0
(i=1)
[select * from p] rc 0
(comment='the following transacion should fail with dup on c.key')
[select "the following transacion should fail with dup on c.key" as comment] rc 0
[begin] rc 0
[insert into c values (1)] rc 0
[update p set i = i+i where i = 1] rc 0
[commit] failed with rc 299 add key constraint duplicate key 'CKI' on table 'c' index 0
(i=1)
[select * from c] rc 0
(i=1)
[select * from p] rc 0
[drop table c] rc 0
[drop table p] rc 0
(comment='the following transacions should succeed because c has non dup key')
[select "the following transacions should succeed because c has non dup key" as comment] rc 0
[create table p {schema{int i} keys{"pki" = i}}] rc 0
[create table c {schema{int i} keys{dup "cki" = i} constraints{"cki" -> <"p" : "pki"> on update cascade on delete cascade }}] rc 0
(rows inserted=1)
[insert into p values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(comment='the following transacion will fail because the cascade will delete the newly inserted row, and verify add constraits cant load it to check constraints')
[select "the following transacion will fail because the cascade will delete the newly inserted row, and verify add constraits cant load it to check constraints" as comment] rc 0
[begin] rc 0
[insert into c values (1)] rc 0
[delete from p where i = 1] rc 0
[commit] failed with rc 304 verify key constraint: record not found in table c
(i=1)
[select * from c] rc 0
(i=1)
[select * from p] rc 0
(comment='the following transacion should result in all rows including the inserted to c within the transaction being updated to 2')
[select "the following transacion should result in all rows including the inserted to c within the transaction being updated to 2" as comment] rc 0
[begin] rc 0
[insert into c values (1)] rc 0
[update p set i = i+i where i = 1] rc 0
[commit] rc 0
(i=2)
(i=2)
[select * from c] rc 0
(i=2)
[select * from p] rc 0
(rows inserted=1)
[insert into p values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(comment='the following transacion should delete all i=1 content on both tables, the delet from c happens as cascade at the very end of the transaction')
[select "the following transacion should delete all i=1 content on both tables, the delet from c happens as cascade at the very end of the transaction" as comment] rc 0
[begin] rc 0
[insert into c values (1)] rc 0
[delete from p where i = 1] rc 0
[commit] rc 0
(i=2)
(i=2)
[select * from c order by i] rc 0
(i=2)
[select * from p order by i] rc 0
