[drop table if exists c] rc 0
[drop table if exists p] rc 0
[create table p {schema{int i} keys{"pki" = i}}] rc 0
[create table c {schema{int i} keys{dup "cki" = i} constraints{"cki" -> <"p" : "pki"> on update cascade on delete cascade }}] rc 0
(rows inserted=1)
[insert into p values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(comment='test #1')
[select "test #1" as comment] rc 0
[begin] rc 0
[delete from p where i = 1] rc 0
[insert into c values (1)] rc 0
[commit] rc 0
[select * from c] rc 0
[select * from p] rc 0
(comment='test #2')
[select "test #2" as comment] rc 0
(rows inserted=1)
[insert into p values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
[begin] rc 0
[update p set i = i+i where i = 1] rc 0
[insert into c values (1)] rc 0
[commit] rc 0
(i=2)
(i=2)
[select * from c] rc 0
(i=2)
[select * from p] rc 0
(out='Verify succeeded.')
[exec procedure sys.cmd.verify("p")] rc 0
(out='Verify succeeded.')
[exec procedure sys.cmd.verify("c")] rc 0
(comment='test #3')
[select "test #3" as comment] rc 0
(rows deleted=2)
[delete from c] rc 0
(rows deleted=1)
[delete from p] rc 0
(rows inserted=1)
[insert into p values (1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
[begin] rc 0
[delete from p where i = 1] rc 0
[insert into c values (1)] rc 0
[commit] rc 0
[select * from c order by i] rc 0
[select * from p order by i] rc 0
(out='Verify succeeded.')
[exec procedure sys.cmd.verify("p")] rc 0
(out='Verify succeeded.')
[exec procedure sys.cmd.verify("c")] rc 0
