[drop table if exists c] rc 0
[drop table if exists p] rc 0
[create table p {schema{int i int j} keys{"pki" = i "pkj" = j}}] rc 0
[create table c {schema{int i} keys{"cki" = i} constraints{"cki" -> <"p" : "pki">} constraints{"cki" -> <"p" : "pkj">}}] rc 0
(rows inserted=1)
[insert into p values (1, 1)] rc 0
(rows inserted=1)
[insert into c values (1)] rc 0
(rows inserted=1)
[insert into p values (2, 3)] rc 0
[insert into c values (2)] failed with rc 3 Transaction violates foreign key constraint c(i) -> p(j): key value does not exist in parent table
[insert into c values (3)] failed with rc 3 Transaction violates foreign key constraint c(i) -> p(i): key value does not exist in parent table
(rows inserted=1)
[insert into p values (3, 2)] rc 0
(rows inserted=1)
[insert into c values (2)] rc 0
(rows inserted=1)
[insert into c values (3)] rc 0
(i=1)
(i=2)
(i=3)
[select * from c order by i] rc 0
(i=1, j=1)
(i=2, j=3)
(i=3, j=2)
[select * from p order by i] rc 0
