[drop table if exists c] rc 0
[drop table if exists p] rc 0
[create table p {schema{int i int j} keys{"pki" = i "pkj" = j "pkij" = i+j }}] rc 0
[create table c1 {schema{int i null=yes} keys{dup "pki" = i} constraints{"pki" -> <"p":"pki"> on delete null on update cascade}}] rc 0
[create table c2 {schema{int i} keys{dup "pki" = i} constraints{"pki" -> <"p":"pki"> on delete null on update cascade}}] rc 0
[create table c3 {schema{int i null=yes int j null=yes} keys{dup "pki" = i dup "pkij" = i+j} constraints{"pkij" -> <"p":"pkij"> on delete null on update cascade}}] rc 0
(rows inserted=4)
[insert into p values (1,2),(3,4),(5,6),(6,7)] rc 0
(rows inserted=2)
[insert into c1 values (1),(3)] rc 0
(rows inserted=1)
[insert into c2 values (5)] rc 0
(rows inserted=1)
[insert into c3 values (6,7)] rc 0
(rows deleted=1)
[delete from p where i=1] rc 0
(i=NULL)
[select * from c1 where i is null] rc 0
[delete from p where i=5] failed with rc 4 Null constraint violation for column 'i' on table 'c2'. verify key constraint cannot null on delete table 'c2' rc 318
(rows deleted=1)
[delete from p where i=6] rc 0
(i=NULL, j=NULL)
[select * from c3 where i is null] rc 0