[drop table if exists foo] rc 0
[drop table if exists bar] rc 0
[drop table if exists baz] rc 0
[create table bar {schema{int i int j} keys{"pk" = i+j}}] rc 0
[begin] rc 0
[create table foo {schema{int i int j} keys{dup "key" = i+j} constraints{"key" -> "bar":"pk" on delete cascade }}] rc 0
[alter table bar rename to baz] rc 0
[commit] failed with rc 240 Cannot rename a table referenced by a foreign key
