[drop table if exists foo] rc 0
[drop table if exists bar] rc 0
[create table bar {schema{int i int j} keys{"pk" = i+j}}] rc 0
[create table foo {schema{int i int j} keys{dup "key" = i+j} constraints{"key" -> "bar":"pk" on delete cascade }}] rc 0
[begin] rc 0
[alter table bar {schema{int i} keys{"pk" = i}}] rc 0
[alter table foo {schema{int i} keys{dup "key" = i} constraints{"key" -> "bar":"pk" on delete cascade }}] rc 0
[commit] rc 0
