#!/bin/bash
bash -n "$0" | exit 1

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

for testreq in `ls t*.sql` ; do
    testname=`echo $testreq | cut -d "." -f 1`
    cmd="cdb2sql -s -f $testreq ${CDB2_OPTIONS} $dbname default "
    echo $cmd "> $testname.output"
    $cmd 2>&1 | sed 's/genid 0x[[:alnum:]]\+/genid 0x0000/' > $testname.output

    diff $testname.expected $testname.output > /dev/null

    if [[  $? -eq 0 ]]; then
        echo "passed $testname"
    else
        echo "failed $testname"
        echo "see diffs here: $HOSTNAME"
        echo "> diff ${PWD}/{$testname.expected,$testname.output}"
        echo
        exit 1
    fi
done
echo
exit 0
