#!/usr/bin/env bash
bash -n "$0" | exit 1

### Pulsed workload test to verify that queue metrics don't report false positives ###

dbnm=$1
host=`cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'SELECT comdb2_host()'`

echo testing against $host ...

cdb2sql $dbnm --host $host 'PUT TUNABLE track_weighted_queue_metrics_separately 1'

#### Short-lived bursts: Run five SELECT-1 processes for 5 seconds, and sleep 25 seconds.
####  This *should not* be considered to have a standing queue
for i in `seq 1 4`; do
  for j in `seq 1 5`; do
    yes "SELECT 1" | cdb2sql $dbnm --host $host - >/dev/null &
  done
  sleep 5
  jobs -p | xargs kill -9
  sleep 25
done

cdb2sql --admin $dbnm --host $host 'select * from comdb2_metrics where name like "%queue_depth%" or name like "%standing_queue%"'

weighted_queue_depth=`cdb2sql --tabs --admin $dbnm --host $host 'select cast(value as integer) * 1000 from comdb2_metrics where name = "weighted_queue_depth"'`
queue_depth=`cdb2sql --tabs --admin $dbnm --host $host 'select cast(value as integer) * 1000 from comdb2_metrics where name = "queue_depth"'`

let qddiff=$queue_depth-$weighted_queue_depth
if [  $qddiff -le 0 ]; then
    echo weighted queue depth is less than queue depth??? >&2
    exit 1
fi

#### Real queuing - this *should* be considered to have a standing queue
for i in `seq 1 4`; do
  yes "SELECT 1" | cdb2sql $dbnm --host $host - >/dev/null &
done
sleep 60 
jobs -p | xargs kill -9 >/dev/null 2>&1
cdb2sql --admin $dbnm --host $host 'select * from comdb2_metrics where name like "%queue_depth%" or name like "%standing_queue%"'

weighted_queue_depth=`cdb2sql --tabs --admin $dbnm --host $host 'select cast(value as integer) * 1000 from comdb2_metrics where name = "weighted_queue_depth"'`
queue_depth=`cdb2sql --tabs --admin $dbnm --host $host 'select cast(value as integer) * 1000 from comdb2_metrics where name = "queue_depth"'`

let qddiff=$queue_depth-$weighted_queue_depth
if [  $qddiff -le 0 ]; then
    echo weighted queue depth is less than queue depth??? >&2
    exit 1
fi

#### Verify that when track_weighted_queue_metrics_separately is off we report only weighted queue metrics
cdb2sql $dbnm --host $host 'PUT TUNABLE track_weighted_queue_metrics_separately 0'
samemetric=`cdb2sql --tabs --admin $dbnm --host $host 'select count(distinct value) from comdb2_metrics where name = "standing_queue_time" or name = "weighted_standing_queue_time"'`
if [ "$samemetric" -ne "1" ]; then
    echo Should keep track of only 1 metric! >&2
    exit 1
fi
samemetric=`cdb2sql --tabs --admin $dbnm --host $host 'select count(distinct value) from comdb2_metrics where name = "queue_depth" or name = "weighted_queue_depth"'`
if [ "$samemetric" -ne "1" ]; then
    echo Should keep track of only 1 metric! >&2
    exit 1
fi

echo Success!
exit 0
