#!/usr/bin/env bash
bash -n "$0" | exit 1
source ${TESTSROOTDIR}/tools/runit_common.sh

# args
# <dbname>
DBN=$1

OUT="run.log"
C="cdb2sql ${CDB2_OPTIONS} ${DBN} default"
CT="cdb2sql --tabs ${CDB2_OPTIONS} ${DBN} default"
master=`getmaster`
CM="cdb2sql ${CDB2_OPTIONS} ${DBN} --host ${master}"

rm $OUT 2>/dev/null
touch $OUT

delayed_writes()
{
    $CM "exec procedure sys.cmd.send('debg 500')"
    $CM "exec procedure sys.cmd.send('ndebg 500')"
    echo "Sleeping 10 seconds"
    sleep 10
    $C "delete from t where a between 1 and 5 or a between 11 and 15"
    echo "Sleeping 10 more seconds"
    sleep 10
    $C "update t set a = a + 1000 where a between 21 and 25 or a between 41 and 45"
    sleep 10
    echo "Sleeping 10 more seconds finally"
    $C "insert into t(a) select * from generate_series(2001, 2010)"
}

function timepart_stats
{
    dbn=$1
    # check the current partitions
    echo $CT "exec procedure sys.cmd.send('partitions')" | egrep -v "STARTTIME|LOW|HIGH|SOURCE_ID"
    $CT "exec procedure sys.cmd.send('partitions')" | egrep -v "STARTTIME|LOW|HIGH|SOURCE_ID" >> $OUT
    if (( $? != 0 )) ; then
        echo "FAILURE"
            exit 1
    fi

    echo $C "select name, period, retention, nshards, version,shard0name from comdb2_timepartitions "
    $C "select name, period, retention, nshards, version,shard0name from comdb2_timepartitions " >> $OUT
    if (( $? != 0 )) ; then
        echo "FAILURE"
            exit 1
    fi

    echo $C "select name, shardname from comdb2_timepartshards"
    $C "select name, shardname from comdb2_timepartshards" >> $OUT
    if (( $? != 0 )) ; then
        echo "FAILURE"
        exit 1
    fi
}

echo "Creating a 7 days time partition"
echo $C "alter table t partitioned by time period 'daily' retention 7 start '2026-01-01T'"
$C "alter table t partitioned by time period 'daily' retention 7 start '2026-01-01T'" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE partitioning the table"
   exit 1
fi

timepart_stats

#"$0_F64CD191",
#"$1_A2620AE4",
#"$2_C429139B",
#"$3_8A26EC5C",
#"$4_3FDAE1EA",
#"$5_9FEC23C1",
#"$6_93A67B48",

echo "Time `${CT} 'select now()'`"

#The idea is to populate shard 0 with some new rows;
#These rows will be processed as part of shard 0 alter in the first 10 seconds
#At this point the delayed delete triggers and try to delete them from both
#source and new table
#if sc_genids are properly set, delete should notice that the rows it deletes
#are already processed by schema change and they need to be removed from new table too

echo "Populating shard 0 first half \$0_F64CD191"
$C "insert into '\$0_F64CD191' (a) select * from generate_series(6, 10)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 0 first half"
   exit 1
fi
echo "Populating shard 1 \$1_A2620AE4"
$C "insert into '\$1_A2620AE4' (a) select * from generate_series(11, 20)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 1"
   exit 1
fi
echo "Populating shard 2 \$2_C429139B"
$C "insert into '\$2_C429139B' (a) select * from generate_series(21, 30)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 2"
   exit 1
fi
echo "Populating shard 3 \$3_8A26EC5C"
$C "insert into '\$3_8A26EC5C' (a) select * from generate_series(31, 40)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 3"
   exit 1
fi
echo "Populating shard 4 \$4_3FDAE1EA"
$C "insert into '\$4_3FDAE1EA' (a) select * from generate_series(41, 50)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 4"
   exit 1
fi
echo "Populating shard 5 \$5_9FEC23C1"
$C "insert into '\$5_9FEC23C1' (a) select * from generate_series(51, 60)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 5"
   exit 1
fi
echo "Populating shard 6 \$6_93A67B48"
$C "insert into '\$6_93A67B48' (a) select * from generate_series(61, 70)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 6"
   exit 1
fi
echo "Populating shard 0 second half \$0_F64CD191"
$C "insert into '\$0_F64CD191' (a) select * from generate_series(1, 5)" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE populating shard 0 second half"
   exit 1
fi

echo "Slow down the schema change"
$CM "exec procedure sys.cmd.send('bdb setattr SC_FORCE_DELAY 1')"
if (( $? != 0 )) ; then
   echo "FAILURE to setattr sc_force_delay"
   exit 1
fi
$CM "exec procedure sys.cmd.send('scdelay 1000')"
if (( $? != 0 )) ; then
   echo "FAILURE to scdelay"
   exit 1
fi

echo "Launching delayed writes"
delayed_writes &

echo "Time `${CT} 'select now()'`"

echo "Partitioning the table"
$C "ALTER TABLE T PARTITIONED BY NONE" 
if (( $? != 0 )) ; then
   echo "FAILURE to launch schema change"
   exit 1
fi

echo "Waiting for delayed writers to finish"
wait

timepart_stats

$C "select count(*) from t" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE to count total rows"
   exit 1
fi
$C "select * from t order by 1" >> $OUT
if (( $? != 0 )) ; then
   echo "FAILURE to select rows"
   exit 1
fi


testcase_output=$(cat $OUT)
expected_output=$(cat output.log)
if [[ "$testcase_output" != "$expected_output" ]]; then

   # print message 
   echo "  ^^^^^^^^^^^^"
   echo "The above testcase (${testcase}) has failed!!!" 
   echo " "
   echo "Use 'diff <expected-output> <my-output>' to see why:"
   echo "> diff ${PWD}/{output.log,run.log}"
   echo " "
   diff output.log $OUT
   echo " "

   # quit
   exit 1
fi

echo "SUCCESS"
