#!/bin/sh

bash -n "$0" | exit 1
dbnm=$1
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'EXEC PROCEDURE sys.cmd.send("memstat debug on sqlite")'
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'EXEC PROCEDURE sys.cmd.send("memstat debug start")'
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'SELECT 1'
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'EXEC PROCEDURE sys.cmd.send("memstat debug stop")'
stacks=`cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'EXEC PROCEDURE sys.cmd.send("memstat debug dump sqlite")'`
for stack in $stacks; do
  addr2line -fsp -e $COMDB2_EXE $stack | grep sql_statement_done
  if [ $? = 0 ]; then
    exit 0
  fi
done
exit 1
