(rows inserted=1)
(rows inserted=1)
[create temp index temp_idx on temp_tbl_test(i)] failed with rc -3 comdb2: not authorized
(rows inserted=1)
[create temp table temp_tbl(i int)] failed with rc -3 comdb2: not authorized
[insert into temp_tbl values(10)] failed with rc -3 no such table: temp_tbl
[create temp index temp_idx on temp_tbl(i)] failed with rc -3 comdb2: not authorized
[insert into temp_tbl values(20)] failed with rc -3 no such table: temp_tbl
(i=1)
(i=2)
(i=3)
[select * from temp_tbl] failed with rc -3 no such table: temp_tbl
