(test='== Unsupported sqlite syntax ==')
(rows inserted=1)
[INSERT OR ROLLBACK INTO t1 VALUES(1)] failed with rc -3 near "ROLLBACK": syntax error
[INSERT OR ABORT INTO t1 VALUES(1)] failed with rc -3 near "ABORT": syntax error
[INSERT OR FAIL INTO t1 VALUES(1)] failed with rc -3 near "FAIL": syntax error
[UPDATE OR ROLLBACK t1 SET i=i+1] failed with rc -3 near "OR": syntax error
[UPDATE OR ABORT t1 SET i=i+1] failed with rc -3 near "OR": syntax error
[UPDATE OR FAIL t1 SET i=i+1] failed with rc -3 near "OR": syntax error
[UPDATE OR IGNORE t1 SET i=i+1] failed with rc -3 near "OR": syntax error
[UPDATE OR REPLACE t1 SET i=i+1] failed with rc -3 near "OR": syntax error
(passed=1)
