done
(rows inserted=1)
done
(rows inserted=1)
done
(rows inserted=1)
done
(rows inserted=1)
done
(rows inserted=1)
done
done
(a=2, b=20)
done
done
(rows updated=1)
done
done
[commit] failed with rc -103 constraints error, no genid
done
done
(a=2, b=21)
done
done
done
(rows updated=1)
done
[commit] failed with rc -103 constraints error, no genid
done
done
done
done
(a=2, b=22)
done
(rows updated=1)
done
[commit] failed with rc -103 constraints error, no genid
done
done
(a=2, b=23)
done
done
done
[commit] failed with rc 304 no such table "t7"
done
