#!/bin/bash

#out=$1
#shift

case $(uname) in
    Linux)
        OSLEVEL=$(uname)
        [[ -r /etc/redhat-release ]] && OSLEVEL=$(cat /etc/redhat-release)
        arch=$(arch)
    ;;
    AIX)
        # AIX ibm1 1 7 00F81A2D4C00 powerpc 00F81A2D4C00 AIX
        set $(uname -a)
        OSLEVEL="${4}.${3}"
        arch=powerpc
    ;;
esac

GIT_BRANCH=${GIT_BRANCH:=$(git rev-parse --abbrev-ref HEAD)}
GIT_REMOTE=$(git config branch.$GIT_BRANCH.remote)
GIT_URL=$(git config remote.$GIT_REMOTE.url)
SVNINFOTAG=${SVNINFOTAG:=$(git describe 2> /dev/null)}
GIT_LOG=$(git log --pretty=%s -1 | sed -e 's:\":\\\":g')

cat <<EOF
static char s0___[] = "@(#)plink [comdb2] TIME    : $(date)";
static char s1___[] = "@(#)plink [comdb2] LOGNAME : $(whoami)";
static char s2___[] = "@(#)plink [comdb2] HOSTNAME: $(hostname)";
static char s3___[] = "@(#)plink [comdb2] TASK    : comdb2";
static char s4___[] = "@(#)plink [comdb2] SNAME   : ";
static char s5___[] = "@(#)plink [comdb2] MAKEFILE: Makefile";
static char s6___[] = "@(#)plink [comdb2] BUILD_DIR: $(pwd)";
static char s7___[] = "@(#)plink [comdb2] VPATH   : ";
static char s8___[] = "@(#)plink [comdb2] BRANCH_TAG: $GIT_BRANCH";
static char s9___[] = "@(#)plink [comdb2] BBBIG   : ";
static char s10___[] = "@(#)plink [comdb2] BBHDR   : ";
static char s11___[] = "@(#)plink [comdb2] BBLIB   : ";
static char s12___[] = "@(#)plink [comdb2] BBSTPTAG: ";
static char s13___[] = "@(#)plink [comdb2] BBSTPHDR: ";
static char s14___[] = "@(#)plink [comdb2] BBSTPLIB: ";
static char s15___[] = "@(#)plink [comdb2] BBDISTRO: ";
static char s16___[] = "@(#)plink [comdb2] LD_PATH : $(echo $CC)";
static char s17___[] = "@(#)plink [comdb2] LD_TAG  : ";
static char s18___[] = "@(#)plink [comdb2] OSNAME  : $(uname)";
static char s19___[] = "@(#)plink [comdb2] OSRELEASE: $(uname -r)";
static char s20___[] = "@(#)plink [comdb2] OSARCH  : $arch";
static char s21___[] = "@(#)plink [comdb2] OSPLATFORM: $arch";
static char s22___[] = "@(#)plink [comdb2] OSLEVEL : $OSLEVEL";
static char s23___[] = "@(#)plink [comdb2] RS_VERSION: ";
static char s24___[] = "@(#)plink [comdb2] SVNINFO : git@github.com/bloomberg/comdb2 ($GIT_BRANCH) tag $SVNINFOTAG ($(git rev-parse --short HEAD))";
static char s25___[] = "@(#)plink [comdb2] BUILDID : ";
static char s26___[] = "@(#)plink [comdb2] GUID    : ";
static char s27___[] = "@(#)plink [comdb2] LOG0001 : $GIT_LOG";
char *___plink_constants[]={
s0___,
s1___,
s2___,
s3___,
s4___,
s5___,
s6___,
s7___,
s8___,
s9___,
s10___,
s11___,
s12___,
s13___,
s14___,
s15___,
s16___,
s17___,
s18___,
s19___,
s20___,
s21___,
s22___,
s23___,
s24___,
s25___,
s26___,
s27___,
0};
EOF
