#!/usr/bin/env bash
bash -n "$0" | exit 1
set -x

set -x
# Grab my database name.
dbnm=$1

# Verify that the user at least supplied a dbname
if [[ -z "$dbnm" ]]; then

    echo "Testcase requires <dbname> argument."
    exit 1

fi

# Enable or disable debugging.
debug=0

# Enable background-debugging.
bgdebug=0

# Set the maximum number of added records for t1.
maxt1=200

# Set to 0 to disable t1 inserts.
ins_t1=1

# Set to 0 to disable t1 updates.
upd_t1=1

# Set to 0 to disable t1 no-blob updates.
upd_noblob_t1=1

# Set to 0 to disable only-blob t1 updates
upd_onlyblob_t1=1

# Set to 0 to disable t1 deletes.
del_t1=1

# Does t1 have any writes- calculated at end.
wr_t1=1

# 'Background' tmpfile.
bgtmpfl=${TMPDIR}/cdb2tst_bg.$$.tmp

# Counter.
ii=0

# Number of background writers.
nwrts=5

# Enable or disable a hello-message from the bg writers.
bghlo=0

# Variable to maintain the pids of the bkground writes.
bkpid=-1

# Set to 1 to make all blobs NULL originally
allnull_blob=0

# Set the background pids to -1.
while [[ $ii -lt $nwrts ]]; do

    # Reset to -1.
    bkpid[$ii]=-1

    # Increment.
    let ii=ii+1

done

# Error/quit function.
function errquit
{
    typeset msg=$1
    typeset cnt=0

    # Enable debugging.
    [[ "$debug" == "1" ]] && set -x

    echo "ERROR: $msg"
    echo "Testcase failed."

    # Check for the background writer.
    while [[ $cnt -lt $nwrts ]]; do

        # Kill each pid
        [[ ${bkpid[$cnt]} != "-1" ]] && kill -9 ${bkpid[$cnt]} >/dev/null 2>&1

        # Reset to -1
        bkpid[$cnt]=-1

        let cnt=cnt+1

    done

    # Exit test.
    exit 1
}

# Generate insert statements for t1.
function gent1insert
{
    typeset max=$1
    typeset fl=$2
    typeset ii=0
    typeset nullblob=0

    # Enable debugging if necessary
    [[ "$debug" == "1" ]] && set -x

    # Clear my file
    >$fl

    # Start a loop
    while [[ $ii -lt $max ]] ; do

        # Insert a NULL blob once every 2 records
        if [[ "0" == $(( ii % 2 )) ]]; then

            nullblob=1

        else

            nullblob=0

        fi

        # Set all blobs to NULL initially if allnull_blob is set.
        if [[ "$allnull_blob" == "1" ]]; then

            nullblob=1

        fi

        if [[ "1" == "$nullblob" ]]; then

            # Print a line of trace
            echo "insert into t1(id) values ($ii)" >> $fl

        else

            # Print a line of trace
            echo "insert into t1(id, b1) values ($ii, x'aa')" >> $fl

        fi

        # Increment ii
        let ii=ii+1

    done

    return 0
}


hexarr=(0 1 2 3 4 5 6 7 8 9 A B C D E F)

# Create a random blob 
function randbl
{
    typeset sz=$1
    local i=0
    res=""
    while [ $i -lt $sz ] ; do
        res="$res${hexarr[$((RANDOM % 16))]}"
        let i=i+1
    done
    echo $res

    return 0
}
# Insert a random record into t1
function insert_rand_t1
{
    typeset db=$1
    typeset id
    typeset bl
    typeset out
    typeset bsz

    # Enable debugging if necessary
    [[ "$debug" == "1" ]] && set -x

    # Create a random id for t1
    id=$(( RANDOM % (maxt1 * 2) ))

    # Create a random blob for t1
    bsz=$(( (RANDOM % 17) * 2 ))
    bl=$(randbl $bsz)

    # Insert the record
    if [[ "1" == "$debug" ]]; then
        echo "cdb2sql ${CDB2_OPTIONS} $db default \"insert into t1(id, b1) values ($id, x'$bl')\""
        cdb2sql ${CDB2_OPTIONS} $db default "insert into t1(id, b1) values ($id, x'$bl')"
    else
        out=$(cdb2sql ${CDB2_OPTIONS} $db default "insert into t1(id, b1) values ($id, x'$bl')" 2>&1)
    fi
    if [[ $? != 0 ]]; then
        echo "insert_rand_t1 failed, $out"
        exit 1
    fi

    # If the 'bgdebug' flag is set, write this to a file. */
    if [[ "1" == "$bgdebug" ]]; then
        
        echo "cdb2sql ${CDB2_OPTIONS} $db default \"insert into t1(id, b1) values ($id, x'$bl')\"" >> $bgtmpfl
    fi

    return 0
}

function update_noblob_rand_t1
{
    typeset db=$1
    typeset id
    typeset upid
    typeset x
    typeset out

    # Enable debugging if necessary
    [[ "$debug" == "1" ]] && set -x

    # Create a random id for t1
    id=$(( RANDOM % ( maxt1 * 2) )) ; upid=$(( RANDOM % (maxt1 * 2) ))

    # Update a record, discard the result
    if [[ "1" == "$debug" ]]; then
        echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set id=$upid where id=$id\""
        cdb2sql ${CDB2_OPTIONS} $db default "update t1 set id=$upid where id=$id"
    else
        out=$(cdb2sql ${CDB2_OPTIONS} $db default "update t1 set id=$upid where id=$id" 2>&1)
    fi
    if [[ $? != 0 ]]; then
        echo "update_noblob_rand_t1 failed, $out"
        exit 1
    fi

    # If the 'bgdebug' flag is set, write this to a file. */
    if [[ "1" == "$bgdebug" ]]; then
        
        echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set id=$upid where id=$id\"" >> $bgtmpfl
    fi

    return 0
}

# Update a random record in t1
function update_onlyblob_rand_t1
{
    typeset db=$1
    typeset id
    typeset nullblob=0
    typeset x
    typeset out
    typeset bsz

    # Enable debugging if necessary
    [[ "$debug" == "1" ]] && set -x

    # Create a random id for t1
    x=$RANDOM ; id=$(( x % ( maxt1 * 2) ))

    # Create a random blob for t1
    bsz=$(( (RANDOM % 17) * 2 ))
    bl=$(randbl $bsz)

    # Make the blob a NULL once every 5 times
    if [[ "0" == $((RANDOM % 5 )) ]]; then
        nullblob=1
    fi

    # Update a record, discard the result
    if [[ "1" == "$debug" ]]; then

        if [[ "1" == "$nullblob" ]]; then

            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set b1=NULL where id=$id\""
            cdb2sql ${CDB2_OPTIONS} $db default "update t1 set b1=NULL where id=$id"

        else

            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set b1=x'$bl' where id=$id\""
            cdb2sql ${CDB2_OPTIONS} $db default "update t1 set b1=x'$bl' where id=$id"

        fi

    else
        if [[ "1" == "$nullblob" ]]; then
            out=$(cdb2sql ${CDB2_OPTIONS} $db default "update t1 set b1=NULL where id=$id" 2>&1)
        else
            out=$(cdb2sql ${CDB2_OPTIONS} $db default "update t1 set b1=x'$bl' where id=$id" 2>&1)
        fi
    fi
    if [[ $? != 0 ]]; then
        echo "update_onlyblob_rand_t1 failed, $out"
        exit 1
    fi

    # If the 'bgdebug' flag is set, write this to a file. */
    if [[ "1" == "$bgdebug" ]]; then
        
        if [[ "1" == "$nullblob" ]]; then
            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set b1=NULL where id=$id\"" >> $bgtmpfl
        else
            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set b1=x'$bl' where id=$id\"" >> $bgtmpfl
        fi
    fi

    return 0
}


# Update a random record in t1
function update_rand_t1
{
    typeset db=$1
    typeset id
    typeset upid
    typeset nullblob=0
    typeset out
    typeset bsz

    # Enable debugging if necessary
    [[ "$debug" == "1" ]] && set -x

    # Create a random id for t1
    id=$(( RANDOM % (maxt1 * 2) )) ; upid=$(( RANDOM % (maxt1 * 2) ))

    # Create a random blob for t1
    bsz=$(( (RANDOM % 17) * 2 ))
    bl=$(randbl $bsz)

    # Make the blob a NULL once every 5 times
    if [[ "0" == $(( RANDOM % 5 )) ]]; then
        nullblob=1
    fi

    # Update a record, discard the result
    if [[ "1" == "$debug" ]]; then

        if [[ "1" == "$nullblob" ]]; then

            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set id=$upid, b1=NULL where id=$id\""
            cdb2sql ${CDB2_OPTIONS} $db default "update t1 set id=$upid, b1=NULL where id=$id"

        else

            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set id=$upid, b1=x'$bl' where id=$id\""
            cdb2sql ${CDB2_OPTIONS} $db default "update t1 set id=$upid, b1=x'$bl' where id=$id"

        fi

    else
        if [[ "1" == "$nullblob" ]]; then
            out=$(cdb2sql ${CDB2_OPTIONS} $db default "update t1 set id=$upid, b1=NULL where id=$id" 2>&1)
        else
            out=$(cdb2sql ${CDB2_OPTIONS} $db default "update t1 set id=$upid, b1=x'$bl' where id=$id" 2>&1)
        fi
    fi
    if [[ $? != 0 ]]; then
        echo "update_rand_t1 failed, $out"
        exit 1
    fi

    # If the 'bgdebug' flag is set, write this to a file. */
    if [[ "1" == "$bgdebug" ]]; then
        
        if [[ "1" == "$nullblob" ]]; then
            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set id=$upid, b1=NULL where id=$id\"" >> $bgtmpfl
        else
            echo "cdb2sql ${CDB2_OPTIONS} $db default \"update t1 set id=$upid, b1=x'$bl' where id=$id\"" >> $bgtmpfl
        fi

    fi

    return 0
}

# Delete a random record in t1
function delete_rand_t1
{
    typeset db=$1
    typeset id
    typeset x
    typeset out

    # Enable debugging if necessary
    [[ "$debug" == "1" ]] && set -x

    # Create a random id for t1
    x=$RANDOM ; id=$(( x % (maxt1 * 2) ))

    # Delete a record, discard the result
    if [[ "1" == "$debug" ]]; then
        echo "cdb2sql ${CDB2_OPTIONS} $db default \"delete from t1 where id=$id\""
        cdb2sql ${CDB2_OPTIONS} $db default "delete from t1 where id=$id"
    else
        out=$(cdb2sql ${CDB2_OPTIONS} $db default "delete from t1 where id=$id" 2>&1)
    fi
    if [[ $? != 0 ]]; then
        echo "delete_rand_t1 failed, $out"
        exit 1
    fi

    # If the 'bgdebug' flag is set, write this to a file. */
    if [[ "1" == "$bgdebug" ]]; then
        
        echo "cdb2sql ${CDB2_OPTIONS} $db default \"delete from t1 where id=$id\"" >> $bgtmpfl

    fi

    return 0
}

# Perform some random writes
function randomwrites
{
    # Say 'hello'.
    [[ "1" == "$bghlo" ]] && echo "Background writer executing."

    # Perform some random writes in a loop
    while true; do

        # Insert a record into t1 
        [[ "1" == "$ins_t1" ]] && insert_rand_t1 $dbnm

        # Update a random record in t1
        [[ "1" == "$upd_t1" ]] && update_rand_t1 $dbnm

        # Update a random record in t1 without touching the blob
        [[ "1" == "$upd_noblob_t1" ]] && update_noblob_rand_t1 $dbnm

        # Update a random records blob without touching id
        [[ "1" == "$upd_onlyblob_t1" ]] && update_onlyblob_rand_t1 $dbnm

        # Delete a record from t1
        [[ "1" == "$del_t1" ]] && delete_rand_t1 $dbnm

        sleep 0.3

    done

    return 0
}

function do_verify
{
    typeset cnt=0

    cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure sys.cmd.verify('t1')" &> verify.out

    if ! grep succeeded verify.out > /dev/null ; then

        errquit "Verify failed."

    fi

    # Check for the background writer.
    while [[ $cnt -lt $nwrts ]]; do

        if [[ "-1" != ${bkpid[$cnt]} ]]; then

            ps -p ${bkpid[$cnt]} >/dev/null 2>&1

            if [[ $? != 0 ]] ; then

                errquit "Background writers failed"

            fi

        fi

        let cnt=cnt+1

    done
}

function do_schemachange
{
do_verify
sleep 2
do_verify
echo "Add int index"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
echo "do_verify after first schema change"
do_verify

sleep 2
echo "Change int index to <DESCEND>"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = <DESCEND>id
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
echo "do_verify after second schema change"
do_verify

sleep 2
echo "Change int index back to <ASCEND>"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi

do_verify
sleep 2
echo "Add partial index"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "PARTIAL"  = id {where id > 100}
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Change partial index"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "PARTIAL"  = id {where id > 10}
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Change partial index (blob)"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "PARTIAL"  = id {where length(b1) > 5}
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Drop partial index"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Add expression index (sum)"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "EXPR"  = (int)"id + id"
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Add expression index (blob)"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "EXPR"  = (int)"id + id"
   dup "EXPR2"  = (int)"length(b1)"
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Add compound expression index"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "EXPR"  = (int)"id + id"
   dup "EXPR2"  = (int)"length(b1)"
   dup "EXPR3"  = (int)"length(b1)" + (int)"id + length(b1)"
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Add condition to expression index"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "EXPR"  = (int)"id + id"
   dup "EXPR2"  = (int)"length(b1)" {where b1 is not null}
   dup "EXPR3"  = (int)"length(b1)" + (int)"id + length(b1)"
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

sleep 2
echo "Change expression index to <DESCEND>"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
keys
{
   dup "ID"  = id
   dup "EXPR"  = <DESCEND>(int)"id + id"
   dup "EXPR2"  = (int)"length(b1)" {where b1 is not null}
   dup "EXPR3"  = (int)"length(b1)" + (int)"id + length(b1)"
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify
}

# Trap to errquit if the user presses Ctrl-C
trap "errquit \"Cancelling test on INT EXIT\"" INT EXIT

cdb2sql ${CDB2_OPTIONS} $dbnm default - <<EOF
drop table if exists t1
create table t1 {
schema
{
   int  id
   blob b1 null=yes
}
}\$\$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed for short tablename"
fi


# If bgdebugging is enabled, print the filename.
if [[ "1" == "$bgdebug" ]]; then

    # Clear it out.
    > $bgtmpfl

    echo "Enabled 'background' debugging for writes in file '$bgtmpfl'."
fi

# Create an insert_t1.cfg 
echo "Generating insert_t1.cfg."
gent1insert $maxt1 insert_t1.cfg

# Insert records into t1.k
echo "Inserting records into t1."
cdb2sql -s ${CDB2_OPTIONS} $dbnm default - < insert_t1.cfg >/dev/null

# Select t1 back.
echo "Selecting t1."
cdb2sql ${CDB2_OPTIONS} $dbnm default "select id, b1 from t1 order by id" > select_t1.txt

ii=0
# Print status message.
echo "Writing random records from $nwrts background processes."
# Start my background writers
while [[ $ii -lt $nwrts ]]; do

    # Start a loop of random-writes.
    randomwrites &

    # Retrieve the pid.
    bkpid[$ii]=$!

    echo "Background write $ii pid ${bkpid[$ii]}"

    # Increment.
    let ii=ii+1

done

echo "Starting schemachange"
cdb2sql ${CDB2_OPTIONS} $dbnm default "PUT SCHEMACHANGE COMMITSLEEP 3"
cdb2sql ${CDB2_OPTIONS} $dbnm default "PUT SCHEMACHANGE CONVERTSLEEP 3"

do_schemachange

echo "Drop all indexes"
cdb2sql ${CDB2_OPTIONS} $dbnm default - <<"EOF"
alter table t1 {
schema
{
   int  id
   blob b1 null=yes
}
}$$
EOF
if [[ $? != 0 ]]; then
    errquit "Schemachange has failed."
fi
do_verify

# delay key adds
cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure sys.cmd.send('goslow')"

# do schemachange test again
do_schemachange

# Reset counter.
ii=0

# Check my writer-pids in a loop.
while [[ $ii -lt $nwrts ]]; do

    # Check the writer pid again
    if [[ "-1" != ${bkpid[$ii]} ]]; then

        # kill it
        kill -9 ${bkpid[$ii]}
    fi

    # Go to next pid
    let ii=ii+1

done

# Remove trap-command.
trap - INT EXIT

# Select t1 back.
echo "Selecting t1."
cdb2sql ${CDB2_OPTIONS} $dbnm default "select id, b1 from t1 order by id" > select_t1_final.txt

# See if t1 was updated during this test.
wr_t1=$(( upd_t1 + del_t1 + ins_t1 ))

# Diff the current t1 against the original snapshot.
diff ./select_t1.txt $select_t1_final >/dev/null 2>&1

# If this is the same, something went wrong.
if [[ "0" != "$wr_t1" && $? == 0 ]]; then

    # echo testcase is broken message.
    echo "Testcase is broken: the post-commit t1 should have changed."

    # Tell the user how to see this.
    echo "Run 'diff ${PWD}/{select_t1.txt,select_t1_final.txt}' to see the error."

    exit 1

fi

echo "Testcase passed."
rm $TMPDIR/cdb2tst_*$$*

exit 0
