CREATE TABLE t1(a int, b int)$$

CREATE LUA AUDIT TRIGGER t1_audit ON (table t1 FOR INSERT AND UPDATE AND DELETE) 

CREATE LUA AUDIT TRIGGER t1_audit ON (table t1 FOR INSERT AND UPDATE AND DELETE) 

DROP LUA TRIGGER t1_audit

CREATE LUA AUDIT TRIGGER t1_audit ON (table t1 FOR INSERT AND UPDATE AND DELETE) 

DROP TABLE '$audit_t1'

CREATE LUA AUDIT TRIGGER shoutout_to_alexw ON (table t1 FOR INSERT AND UPDATE AND DELETE) 

SELECT * FROM comdb2_tables ORDER BY tablename

DROP LUA TRIGGER t1_audit
DROP LUA TRIGGER shoutout_to_alexw 
DROP TABLE '$audit_t1'
DROP TABLE '$audit_t1$2'
DROP TABLE t1