testing missing comdb2_logical_cron table
[put counter testcounter1 increment] failed with rc -3 no such table: comdb2_logical_cron
[put counter testcounter1 set 0] failed with rc -3 no such table: comdb2_logical_cron
creating comdb2_logical_cron table
(name='testcounter1', value=0)
(name='testcounter1', value=0)
(name='testcounter2', value=0)
(name='testcounter1', value=0)
(name='testcounter2', value=1000)
[put counter testcounter2 set -1] failed with rc -3 near "-": syntax error
(name='testcounter1', value=0)
(name='testcounter2', value=1000)
(name='testcounter1', value=0)
(name='testcounter2', value=1001)
(name='testcounter1', value=1)
(name='testcounter2', value=1001)
