#!/usr/bin/env bash
bash -n "$0" | exit 1

set -x

dbnm=$1

if [ "x$dbnm" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

output=run.log
echo "testing missing comdb2_logical_cron table"
echo "testing missing comdb2_logical_cron table" > $output
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter1 increment" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter1 set 0" >> $output 2>&1

echo "creating comdb2_logical_cron table"
echo "creating comdb2_logical_cron table" >> $output
cdb2sql ${CDB2_OPTIONS} $dbnm default "create table comdb2_logical_cron (name cstring(128) primary key, value int)" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from comdb2_logical_cron" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter1 increment" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from comdb2_logical_cron" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter2 set 0" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from comdb2_logical_cron" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter2 set 1000" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from comdb2_logical_cron" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter2 set -1" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from comdb2_logical_cron" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter2 increment" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from comdb2_logical_cron" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "put counter testcounter1 increment" >> $output 2>&1
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from comdb2_logical_cron" >> $output 2>&1

testcase_output=$(cat $output)

# get expected output
expected_output=$(cat $output.exp)

# verify 
if [[ "$testcase_output" != "$expected_output" ]]; then

    echo "  ^^^^^^^^^^^^"
    echo "The testcase has failed!!!"
    echo " "
    echo "Use 'diff <expected-output> <my-output>' to see why:"
    echo "> diff ${PWD}/{$output.exp,$output}"
    echo " "
    diff $output.exp $output
    echo " "
    exit 1

fi

echo "Testcase passed."
