#!/usr/bin/env bash
bash -n "$0" | exit 1

vars="TESTCASE DBNAME DBDIR TESTSROOTDIR TESTDIR CDB2_OPTIONS CDB2_CONFIG SECONDARY_DBNAME SECONDARY_DBDIR SECONDARY_CDB2_CONFIG SECONDARY_CDB2_OPTIONS"
for required in $vars; do
    q=${!required}
    echo "$required=$q" 
    if [[ -z "$q" ]]; then
        echo "$required not set" >&2
        exit 1
    fi
done

function verify_node () {
	src_table=$1
	dst_table=$2
	exp_records=$3
	exp_schemas=$4
	tier=$5
	rc=0

	res_records=$(cdb2sql ${SECONDARY_CDB2_OPTIONS} -tabs $SECONDARY_DBNAME $tier "select * from $dst_table")
	if [[ "$res_records" != "$exp_records" ]];
	then
		echo "record mismatch between src and dst tables"
		echo "src records ------------"
		echo "$exp_records"
		echo "dst records ------------"
		echo "$res_records"
		rc=1
	fi

	res_schemas=$(cdb2sql ${SECONDARY_CDB2_OPTIONS} -tabs $SECONDARY_DBNAME $tier "select version, csc2 from comdb2_schemaversions where tablename='$dst_table'")
	if [[ "$res_schemas" != "$exp_schemas" ]];
	then
		echo "schema mismatch between src and dst tables"
		echo "src schemas ------------"
		echo "$exp_schemas"
		echo "dst schemas ------------"
		echo "$res_schemas"
		rc=1
	fi

	return $rc
}

function verify_import () {
	src_table=$1
	dst_table=$2
	rc=0

	exp_records=$(cdb2sql ${CDB2_OPTIONS} -tabs $DBNAME default "select * from $src_table")
	exp_schemas=$(cdb2sql ${CDB2_OPTIONS} -tabs $DBNAME default "select version, csc2 from comdb2_schemaversions where tablename='$src_table'")

	if [[ -z "$CLUSTER" ]];
	then
		verify_node "$src_table" "$dst_table" "$exp_records" "$exp_schemas" default
		rc=$?
	else
		for node in $CLUSTER;
		do
			verify_node "$src_table" "$dst_table" "$exp_records" "$exp_schemas" "--host $node"
			rc=$?
			if (( rc != 0 ));
			then
				break
			fi
		done
	fi

	return $rc
}

function failexit () {
	rc=$1
	msg=$2

	if (( rc != 0 ));
	then
		echo $msg
		exit $rc
	fi
}

# Setup source table

cdb2sql ${CDB2_OPTIONS} $DBNAME default "create table t(i int)"
cdb2sql ${CDB2_OPTIONS} $DBNAME default "insert into t values(1)"

cdb2sql ${CDB2_OPTIONS} $DBNAME default "create table q(b blob)"
cdb2sql ${CDB2_OPTIONS} $DBNAME default "insert into q values(x'f00f')"

# Import table with the same schema

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "create table t(i int)"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "import t from $DBNAME to t" && verify_import t t
failexit $? "Failed to import a table with the same schema."

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "drop table t"

# Import table with a different schema

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "create table t(i int, j int)"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "import t from $DBNAME to t" && verify_import t t
failexit $? "Failed to import a table with a different schema"

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "drop table t"

# Import noblob table over blob table

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "create table t(b blob)"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "import t from $DBNAME to t" && verify_import t t
failexit $? "Failed to import a table over a table with different blob options"

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "drop table t"

# Import table over a table with a different name

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "create table q(b blob)"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "import t from $DBNAME to q" && verify_import t q
failexit $? "Failed to import a table with a different name"

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "drop table q"

# Import blob table over noblob table

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "create table t(i int)"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "import q from $DBNAME to t" && verify_import q t
failexit $? "Failed to import a table over a table with different blob options"

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "drop table t"

# Import table that has been schema changed

cdb2sql ${CDB2_OPTIONS} $DBNAME default "alter table t add column j int"
cdb2sql ${CDB2_OPTIONS} $DBNAME default "insert into t values(2, 3)"
cdb2sql ${CDB2_OPTIONS} $DBNAME default "alter table t add column b blob"
cdb2sql ${CDB2_OPTIONS} $DBNAME default "insert into t values(4, 5, x'f00f')"

cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "create table t(i int)"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "import t from $DBNAME to t" && verify_import t t
failexit $? "Failed to import a table that has been schema changed"

exit 0
