done
done
done
done
(rows inserted=1)
done
done
done
done
done
done
(a=2)
done
(a=1)
done
done
[commit] failed with rc 240 cannot add new field without dbstore or null
done
done
(a=1)
done
(a=1)
done
done
done
done
(a=10)
done
done
(a=20)
done
done
done
done
[commit] failed with rc 240 stale version for table:t70 master:1 replicant:0
done
(a=10)
done
(csc2='schema {int a int b null=yes}')
done
done
done
done
[select * from t7] failed with rc -3 no such table: t7
done
done
done
done
done
done
(a=1, b=10)
(a=2, b=20)
done
done
done
done
done
[commit] failed with rc -3 table "t70" was schema changed
done
(a=1, b=10)
(a=2, b=20)
done
