#!/usr/bin/env bash
bash -n "$0" | exit 1

dbnm=pmuxsecure

# Use our own pmux in this test
${COMDB2_EXE} ${dbnm} --create --dir $TESTDIR/${dbnm} --tunable 'portmux_bind_path /tmp/pmux.secure.socket' --tunable 'portmux_port 5106' --tunable "ssl_cert_path $TESTDIR"
${PMUX_EXE} -f -b /tmp/pmux.secure.socket -p 5106 -s 5104 -r 20000:20001 &
pmuxpid=$!

${COMDB2_EXE} ${dbnm} --lrl $TESTDIR/${dbnm}/${dbnm}.lrl &
dbpid=$!
sleep 10;

cp $DBDIR/comdb2db.cfg $DBDIR/5104.cfg
echo 'comdb2_config:allow_pmux_route:true' >>$DBDIR/5104.cfg
echo 'comdb2_config:portmuxport=5104' >> $DBDIR/5104.cfg

cp $DBDIR/comdb2db.cfg $DBDIR/5106.cfg
echo 'comdb2_config:allow_pmux_route:true' >>$DBDIR/5106.cfg
echo 'comdb2_config:portmuxport=5106' >> $DBDIR/5106.cfg

# externalauth is disabled. connections routed from 5104 should be rejected
cdb2sql --cdb2cfg $DBDIR/5104.cfg $dbnm --host localhost "select 1" >output 2>&1
# now turn on externalauth, through the "insecure" pmux port
cdb2sql --cdb2cfg $DBDIR/5106.cfg $dbnm --host localhost "exec procedure sys.cmd.send('externalauth 1')"
# externalauth is enabled. connections routed from 5104 should be accepted
cdb2sql --cdb2cfg $DBDIR/5104.cfg $dbnm --host localhost "select 2" >>output 2>&1

kill -9 $dbpid
kill -9 $pmuxpid
diff expected output
