#!/usr/bin/env bash

source ${TESTSROOTDIR}/tools/runit_common.sh
source ${TESTSROOTDIR}/tools/cluster_utils.sh

set -ex

dbnm=$1

restart_cluster() {
	local -r restart_delay_secs=10

	set +e
	if [ -z $CLUSTER ];
	then
		kill_restart_node $1 ${restart_delay_secs} &
	else
		for node in ${CLUSTER} ; do
			kill_restart_node ${node} ${restart_delay_secs} &
		done
	fi

	sleep 2
	wait_for_cluster
	set -e
}

num_outstanding_scs() {
	cdb2sql --tabs ${CDB2_OPTIONS} ${dbnm} default "select count(*) from comdb2_sc_status where status!='COMMITTED'"
}

wait_for_outstanding_scs() {
	local num_scs

	num_scs=$(num_outstanding_scs)
	while (( num_scs > 0 )); do
		sleep 1
		num_scs=$(num_outstanding_scs)
	done
}

setup_table() {
	local -r tbl_name=$1 num_shards=$2 num_records_per_shard=$3

	local starttime
	starttime=$(get_timestamp 120)

	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "create table ${tbl_name}(a int) partitioned by time period 'daily' retention ${num_shards} start '${starttime}'"
	for i in $(seq 0 1 $((num_shards-1)));
	do
		local shard
		shard=$(cdb2sql --tabs ${CDB2_OPTIONS} ${dbnm} default "select shardname from comdb2_timepartshards limit 1 offset ${i}")
	  	for (( i=1; i<=${num_records_per_shard}; i+=10000 )); do
	      		local min="${i}"
			local max="$(( ((${i} + 9999) < ${num_records_per_shard}) ? (${i} + 9999) : ${num_records_per_shard}))"
	      		cdb2sql ${CDB2_OPTIONS} ${DBNAME} default "insert into '${shard}' select * from generate_series(${min}, ${max})"
	  	done
	done
}

test_partition_merge_resume() {
	# Given
	local -r num_shards=$1 num_records_per_shard=$2

	local master
	master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'SELECT host FROM comdb2_cluster WHERE is_master="Y"'`

	local -r tbl_name="t"
	setup_table ${tbl_name} ${num_shards} ${num_records_per_shard}

#	cdb2sql $dbnm --host $master "EXEC PROCEDURE sys.cmd.send('convert_record_sleep 1')"

	# When
	COMDB2_CONFIG_MIN_RETRIES=0 \
	COMDB2_CONFIG_MAX_RETRIES=0 \
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "alter table ${tbl_name} partitioned by none" &
	local -r waitpid=$!

	sleep 5

	restart_cluster ${master}

	# Then
	if wait ${waitpid};
	then
		echo "FAIL: Merge succeeded before cluster bounced. Test is buggy."
		return 1
	fi

	wait_for_outstanding_scs &> /dev/null

	local timepart
	timepart=$(cdb2sql --tabs ${CDB2_OPTIONS} ${dbnm} default "select * from comdb2_timepartitions where name='${tbl_name}'")
	if [[ -n ${timepart} ]];
	then
		echo "FAIL: Found time partition that should not exist"
		return 1
	fi

	local num_records
	num_records=$(cdb2sql --tabs ${CDB2_OPTIONS} ${dbnm} default "select count(*) from ${tbl_name}")
	if (( num_records != num_shards*num_records_per_shard ));
	then
		echo "FAIL: Unexpected number of records after partition merge"
		return 1
	fi

	# Cleanup
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "drop table ${tbl_name}"
}

main() {
	local num_shards=5 num_records_per_shard=1
	# test_partition_merge_resume ${num_shards} ${num_records_per_shard}

	num_records_per_shard=100000
	test_partition_merge_resume ${num_shards} ${num_records_per_shard}
}

main
