#!/usr/bin/env bash
bash -n "$0" | exit 1

${TESTSBUILDDIR}/cdb2api_setoptions ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_setoptions - fail" && exit 1
echo 'cdb2api_setoptions - pass'

CDB2_LOG_CALLS=1 ${TESTSBUILDDIR}/cdb2api_stmt_return_types ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_stmt_return_types - fail" && exit 1
echo 'cdb2api_stmt_return_types - pass'

${TESTSBUILDDIR}/cdb2api_string_escape
[[ $? -ne 0 ]] && echo "cdb2api_string_escape - fail" && exit 1
echo 'cdb2api_string_escape - pass'

${TESTSBUILDDIR}/cdb2api_txn ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_txn - fail" && exit 1
echo 'cdb2api_txn - pass'

exit 0
