#!/usr/bin/env bash
bash -n "$0" | exit 1
source ${TESTSROOTDIR}/tools/runit_common.sh
source ${TESTSROOTDIR}/tools/cluster_utils.sh

set -x

SQL="cdb2sql ${CDB2_OPTIONS} $DBNAME default"
SQLT="cdb2sql --tabs ${CDB2_OPTIONS} $DBNAME default"

function get_node
{
    $SQLT 'select comdb2_host()'
}


dbnm=$1


if [ "$dbnm" == "" ] ; then
    echo "need a DB name"
    exit 1
fi


echo $SQL "create table t1 (a int) "
$SQL "create table t1 (a int) "

echo $SQLT "select value from comdb2_tunables where name='dir'"
dir=`$SQLT "select value from comdb2_tunables where name='dir'"`
echo "Foundb dbdir $dir"

if [ "$dir" == "" ] ; then
    echo "Failed to find dir for $dbnm"
    exit 1
fi

echo rm "${dir}/t1*datas0"
rm "${dir}/t1*datas0"


sleep 5

node=`get_node`


echo "Using node $node"

#ssh -o StrictHostKeyChecking=no -tt $node "echo 'setattr ignore_bad_table 1' >> $DBDIR/${DBNAME}.lrl"

echo "Restarting node $node"
kill_restart_node $node 1

cdb2sql --tabs --host ${node} ${CDB2_OPTIONS} $DBNAME 'select 1'
if [ "$?" != "0" ] ; then
    echo "Failed to come up"
    exit 1
fi

found=$SQLT "select name from sqlite_master where name='t1'"
if [ "$found" != "" ] ; then
    echo "Deleting file failed; test failed"
    exit 1
fi

echo "Success"
