#!/bin/bash
set -x

# Grab my database name.
dbnm=$1

# Run the executable
exe=./serial

echo "Testing snapisol"
$exe -d $dbnm

ret=$?

if [[ $ret != 0 ]] ; then

    echo "Snapisol failed, ret=$ret."
    exit 1

else

    echo "Snapisol passed"
    exit 0
fi

