#!/usr/bin/env bash
bash -n "$0" | exit 1

# This test case is a collection of queries reported in various 
# tickets. As such each one will have different schemas.
# The driver will just add/alter tables as required.

${TESTSROOTDIR}/tools/compare_results.sh -s -d $1 -r req
[ $? -eq 0 ] || exit 1
exit 0
