/*
 * CDB2 IDENTITY
 *
 */

#ifndef INCLUDED_CDB2_IDENTITY_H
#define INCLUDED_CDB2_IDENTITY_H

enum cdb2_identity_flags { CDB2_USE_OPTIONAL_IDENTITY = 1, CDB2_NON_THREADED_IDENTITY = 1 << 1 };

#endif
