#!/usr/bin/env bash
bash -n "$0" | exit 1

set -e
#set -x

dbnm=$1

if [ "x$dbnm" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

failexit()
{
    echo "Failed $1"
    exit -1
}


echo "create t1"
cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t1 (a int) "
MAX=100000

if [ "${DEBUGGER}" == "callgrind" ] || [ "${DEBUGGER}" == "memcheck" ]; then 
   DEBUG_PREFIX="valgrind --tool=callgrind --instr-atstart=yes --dump-instr=yes --collect-jumps=yes --callgrind-out-file=$TESTDIR/$TESTCASE.cdb2sql.callgrind"
   MAX=2000
fi

# using timeout is not good because it will cause the 'select 1' string to be cut for the last command (when yes gets killed)
#timeout $((TEST_TIMEOUT-5)) yes 'select 1' | $DEBUG_PREFIX cdb2sql -s ${CDB2_OPTIONS} $dbnm default &> output1.txt

for i in `seq 1 $MAX` ; do echo 'select 1'; done > input1.txt

time $DEBUG_PREFIX cdb2sql -s ${CDB2_OPTIONS} -f input1.txt $dbnm default &> output1.txt

echo "Finished doing $MAX queries"

#while [ $SECONDS -lt $((TEST_TIMEOUT-5)) ] ; do
   #echo 'select 1' 
#done | cdb2sql -s ${CDB2_OPTIONS} $dbnm default &> output2.txt

echo "Success"
