#!/bin/bash
bash -n "$0" | exit 1

set -e
set -x

# Debug variable
debug=0

dbnm=$1

if [ "x$dbnm" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

# Number of insert_records function calls
nins=0


failexit()
{
    echo "Failed $1"
    exit -1
}


echo "create t1"
cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t1 (a int) "

set -e
if [[ ${DEBUGGER} == callgrind ]]; then 
   DEBUG_PREFIX="valgrind --tool=callgrind --instr-atstart=yes --dump-instr=yes --collect-jumps=yes --callgrind-out-file=$TESTDIR/$TESTCASE.cdb2sql.callgrind"
fi

timeout $((TEST_TIMEOUT-5)) yes 'select 1' | $DEBUG_PREFIX cdb2sql -s ${CDB2_OPTIONS} $dbnm default &> /dev/null

echo "Success"
