FROM centos:latest

RUN \
   yum install -y epel-release && \
   yum install -y gcc gcc-c++ protobuf-c libunwind libunwind-devel   \
   protobuf-c-devel byacc flex openssl openssl-devel openssl-libs         \
   readline-devel sqlite sqlite-devel libuuid libuuid-devel zlib-devel    \
   zlib lz4-devel gawk tcl lz4 rpm-build which

COPY . /build/

WORKDIR /build/

RUN make clean && make -j4 && make install

ENV PATH="/opt/bb/bin:${PATH}"
