#!/bin/bash

container=$1

try=1
while [[ $try -lt 30 ]] ; do 
    echo "Getting config"
    docker exec -i $container /bin/cdb2config > db.conf
    if [[ $? -eq 0 ]]; then
        grep -q comdb2_config:default_type db.conf
        if [[ $? -eq 0 ]]; then
            export CDB2_CONFIG_FILE=db.conf
            for db in $(seq 1 5); do
                echo "Trying db${db}"
                dbn=$(cdb2sql -tabs db${db} default 'select comdb2_dbname()')
                while [[ "$dbn" != "db$db" ]]; do
                    if [[ $try -eq 30 ]]; then
                        echo "Timed out!"
                        exit 1
                    fi
                    sleep 1
                    dbn=$(cdb2sql -tabs db${db} default 'select comdb2_dbname()')
                    try=$(($try+1))
                done
                echo "Ok."
            done
            exit 0
        fi
    fi

    sleep 1
    try=$(($try+1))
done
exit 1
