#!/usr/bin/env bash
bash -n "$0" | exit 1

. ${TESTSROOTDIR}/tools/runit_common.sh

debug=1
[[ $debug == "1" ]] && set -x

function exclude_test
{
    local n=""
    local fp=""
    local excluded=""
    local count=0
    local aftercnt=0

    # Grab the first cluster node
    if [[ -n "$CLUSTER" ]]; then
        n=$(echo "$CLUSTER" | cut -d' ' -f1)
    else
        n=$(hostname)
    fi

    # Create a long request
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $n "select sleep(15)"

    # Make sure that this appeared in the longreqs log
    log=$TESTDIR/logs/excludefp${TESTID}.${n}.db

    count=$(egrep -i -c "LONG REQUEST" $log)
    [[ "$count" == "0" ]] && failexit "long request not found in longreqs log"

    # Grab fingerprint for the sleep
    fp=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $n "select fingerprint from comdb2_fingerprints where normalized_sql like 'SELECT sleep%'")

    # Make sure we got something
    [[ -z "$fp" ]] && failexit "could not get fingerprint for sleep request"

    # Verify that this is not excluded from longreqs
    excluded=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $n "select excluded_from_longreqs from comdb2_fingerprints where fingerprint='$fp'")

    [[ "$excluded" == "N" ]] || failexit "fingerprint for sleep request is already marked as excluded_from_longreqs"

    # Exclude this fp from longreqs
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $n "exec procedure sys.cmd.send('reql excludefp $fp')"

    # Verify that it is now excluded
    excluded=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $n "select excluded_from_longreqs from comdb2_fingerprints where fingerprint='$fp'")

    [[ "$excluded" == "Y" ]] || failexit "fingerprint for sleep request is not marked as excluded_from_longreqs"

    # Run the same long request again
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $n "select sleep(15)"

    # Verify that the new request didn't occur as a LONGREQ
    aftercnt=$(egrep -i -c "LONG REQUEST" $log)

    [[ "$aftercnt" != "$count" ]] && failexit "long request found in longreqs log after excluding fingerprint"

    # Now remove the exclusion
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $n "exec procedure sys.cmd.send('reql unexcludefp $fp')"

    # Run the same long request again
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $n "select sleep(15)"

    # Verify that the request once again appears as a LONG REQUEST
    aftercnt=$(egrep -i -c "LONG REQUEST" $log)

    [[ "$aftercnt" == "$count" ]] && failexit "unexcluded long-request did not appear in longreqs log"
}

function run_tests
{
    exclude_test
}

run_tests
echo "Success!"
