#!/usr/bin/env bash

set -e
dbnm=$1

cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default - <<EOF
DROP TABLE IF EXISTS t_one_pass
CREATE TABLE t_one_pass(c0 integer, c1 integer, c2 integer, c3 integer)\$\$
INSERT INTO t_one_pass VALUES (0, 1, 2, 3)
CREATE INDEX t_one_pass_c0_c1_c2 on t_one_pass(c0, c1, c2)
EOF

index=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'EXPLAIN DELETE FROM t_one_pass WHERE c0 = 0 and c2 < 0' | grep OpenWrite | grep -i t_one_pass_c0_c1_c2 | awk '{print $3}'`
column=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'EXPLAIN DELETE FROM t_one_pass WHERE c0 = 0 and c2 < 0' | grep t_one_pass.c2 | awk '{print $3}'`

if [ "$index" != "$column" ]; then
    echo OP_Column not operating on the index! >&2
    exit 1
fi

cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'DELETE FROM t_one_pass WHERE c0 = 0 and c2 < 1'

cnt=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'SELECT COUNT(*) FROM t_one_pass'`

if [ "$cnt" != "1" ]; then
    echo Wrong entries deleted! >&2
    exit 1
fi
