#!/usr/bin/env bash
bash -n "$0" | exit 1

export debug=1
[[ $debug == "1" ]] && set -x

. ${TESTSROOTDIR}/tools/write_prompt.sh
. ${TESTSROOTDIR}/tools/ddl.sh
. ${TESTSROOTDIR}/tools/cluster_utils.sh

#export VALGRIND=valgrind
export stopfile=./stopfile.txt
export tablecount=50

function failexit
{
    touch $stopfile
    echo "Failed: $1"
    exit -1
}

function stop_cluster
{
    for node in $CLUSTER ; do
        $CDB2SQL_EXE $CDB2_OPTIONS --tabs $DBNAME --host $node "exec procedure sys.cmd.send(\"exit\")"
        sleep 1
        kill_by_pidfile ${TMPDIR}/${DBNAME}.${node}.pid
    done
}

function verify_up
{
    typeset func="verify_up"
    write_prompt $func "Running $func"
    typeset node=$1
    typeset count=0
    typeset r=1
    while [[ "$r" -ne "0" && "$count" -lt 30 ]]; do
        $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $node "select 1" >/dev/null 2>&1
        r=$?
        [[ $r != 0 ]] && sleep 1
        let count=count+1
    done
    [[ $r != 0 ]] && failexit "node $node did not recover in time"
}

function findmaster
{
    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default 'select host from comdb2_cluster where is_master="Y"'
}

function create_table
{
    typeset func="run_test"
    write_prompt $func "Creating t1"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "create table t1(a int)"
}

function check_blocked
{
    typeset func="check_blocked"
    typeset pid=$1
    sleep 5
    kill -0 $pid > /dev/null 2>&1
    r=$? ; [[ "$r" -ne "0" ]] && failexit "Pid $pid is not blocked on prepared txn"
    write_prompt $func "pid $pid is blocked"
    write_prompt $func "$(ps -ef | egrep $pid)"
}

function check_notblocked
{
    typeset func="check_notblocked"
    typeset pid=$1
    sleep 1
    kill -0 $pid > /dev/null 2>&1
    r=$? ; [[ "$r" -eq "0" ]] && failexit "Pid $pid is blocked on prepared txn"
    write_prompt $func "pid $pid is not blocked"
    write_prompt $func "$(ps -ef | egrep $pid)"
}

function wait_for_election
{
    typeset func="wait_for_election"
    typeset timeout=${1:-30}
    typeset j=0

    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "select 1" > /dev/null 2>&1
    while [[ $? != 0 && "$j" -le $timeout ]]; do
        let j=j+1
        sleep 1
        $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default "select 1" > /dev/null 2>&1
    done

    [[ "$j" -gt "$timeout" ]] && failexit "Cluster didn't come up in time"
}

#function restart_node
#{
#    typeset func="restart_node"
#}

function check_cluster
{
    typeset func="check_cluster"
    sleep 10
    for node in $CLUSTER ; do
        $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $node "select 1" > /dev/null 2>&1
        r=$?
        [[ "$r" != "0" ]] && failexit "Node $node is not up"
    done
}

function insert_t1
{
    typeset func="insert_t1"
    echo "set verifyretry off
insert into t1 select * from generate_series(1, 1000)" | $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME default -
}

function kill_cluster
{
    typeset func="kill_cluster"
    for node in $CLUSTER ; do
        kill_by_pidfile ${TMPDIR}/${DBNAME}.${node}.pid
    done
}

function start_cluster
{
    typeset func="start_cluster"
    for node in $CLUSTER ; do
        PARAMS="--no-global-lrl --lrl $DBDIR/${DBNAME}.lrl --pidfile ${TMPDIR}/${DBNAME}.${node}.pid"
        CMD="cd ${DBDIR}; source ${REP_ENV_VARS} ; ${VALGRIND} $COMDB2_EXE ${DBNAME} ${PARAMS} 2>&1 | tee $TESTDIR/${DBNAME}.db"
        ssh -n -o StrictHostKeyChecking=no -tt $node ${CMD} &> $LOGDIR/${DBNAME}.${node}.db &
        echo $! > ${TMPDIR}/${DBNAME}.${node}.pid
    done
}

function prepare_and_commit
{
    typeset func="prepare_and_commit"
    typeset master=$(findmaster)

    write_prompt $func "Inserting records"
    insert_t1

    # TODO this will change when bdb-hooks are done
    write_prompt $func "Tell master to prepare and leak"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "put tunable 'debug_all_prepare_leak' 1"

    write_prompt $func "Insert 1000 more records this should force master exit"
    insert_t1 &
    leaked_pid=$!

    write_prompt $func "Sleep a bit to make sure prepare record has propogated"
    sleep 4

    write_prompt $func "Kill the leaked pid so it's not retried"
    kill -9 $leaked_pid

    write_prompt $func "Explicitly kill old master, it should be exiting though"
    kill_restart_node $master

    write_prompt $func "Waiting for election / new master"
    wait_for_election

    write_prompt $func "Sleep for 5"
    sleep 5

    write_prompt $func "Performing another insert- this should block on the prepared insert"
    insert_t1 &
    insert_pid=$!
    write_prompt $func "Insert pid is $insert_pid"

    write_prompt $func "Verify that insert sql is blocked"
    check_blocked $insert_pid

    master=$(findmaster)
    write_prompt $func "Verify that replicant has seen prepared record"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Replicant did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED" ]] && failexit "Error locating prepared record"

    write_prompt $func "Verify that master has seen prepared record and has locks"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master  "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Master did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED|HAVELOCKS" ]] && failexit "Master prepared txn should have acquired locks"

    write_prompt $func "Verify that master has pagelocks, one for new insert should be waiting"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master  "select count(*) from comdb2_locks where mode='READ' and status='WAIT' and locktype='PAGE'")
    [[ "$x" -lt "1" ]] && failexit "Outstanding insert isn't blocked on prepared txn"
    x=$($CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master  "select * from comdb2_locks where mode='READ' and status='WAIT' and locktype='PAGE'")
    write_prompt $func "$x"

    write_prompt $func "Verify that reading on replicant is not blocked.. this will time-out if it is"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default  "select count(*) from t1")
    write_prompt $func "Make sure that there are only 1000 records on the replicant"
    write_prompt $func "Count is $x records"
    [[ "$x" -ne "1000" ]] && failexit "There should be 1000 records, not $x"

    write_prompt $func "Get the dist-txnid"
    dist_txnid=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select dist_txnid from comdb2_prepared")
    [[ -z "$dist_txnid" ]] && failexit "Master does not have dist-txnid"
    write_prompt $func "Dist-txnid is $dist_txnid"
    write_prompt $func "Commit prepared dist-txn:"
    write_prompt $func "send disttxn $dist_txnid commit"
    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "exec procedure sys.cmd.send('disttxn $dist_txnid commit')"

    sleep 5
    write_prompt $func "New insert should have resolved(1):"
    check_notblocked $insert_pid

    write_prompt $func "New insert is resolved: $(ps -ef | egrep $insert_pid)"
    write_prompt $func "Verify that t1 has 3000 records"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select count(*) from t1")
    write_prompt $func "Count is $x records"

    [[ "$x" -ne "3000" ]] && failexit "Found only $x records, should be 3000"

    write_prompt $func "Single-master bounce succeeded!"
    write_prompt $func "Checking cluster"
    check_cluster

    master=$(findmaster)
    write_prompt $func "Master is $master"
    
    write_prompt $func "Tell master to prepare and leak"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "put tunable 'debug_all_prepare_leak' 1"

    write_prompt $func "Insert 1000 more records"
    insert_t1 &
    leaked_pid=$!

    write_prompt $func "Sleep for 5"
    sleep 5

    write_prompt $func "Killing the cluster"
    kill_cluster

    write_prompt $func "Starting the cluster"
    start_cluster

    write_prompt $func "Waiting for election / new master"

    for node in $CLUSTER; do 
        verify_up $node
    done

    write_prompt $func "Sleep for 5"
    sleep 5

    write_prompt $func "Background insert after cluster bounce"
    write_prompt $func "This should block on leaked prepared we did before cluster bounce"
    insert_t1 &
    insert_pid=$!

    master=$(findmaster)

    write_prompt $func "Verify that insert sql is blocked after cluster bounce"
    check_blocked $insert_pid

    write_prompt $func "Verify that replicant has recovered prepared record"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Replicant did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED" ]] && failexit "Error locating prepared record"

    write_prompt $func "Verify that master has recovered & re-acquired prepared locks"
    flags=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select flags from comdb2_prepared")
    [[ -z "$flags" ]] && failexit "Master did not recover the prepared txn"
    [[ "$flags" -ne "RECOVERED|HAVELOCKS" ]] && failexit "Master did not reaquire locks"
    write_prompt $func "Select the locks"
    locks=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select * from comdb2_locks where locktype='PAGE'")
    write_prompt $func "$locks"

    write_prompt $func "Verify that select against replicant returns 3000 records"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default  "select count(*) from t1")
    [[ "$x" -ne "3000" ]] && failexit "There should be 3000 records, not $x"

    write_prompt $func "Get the dist-txnid"
    dist_txnid=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select dist_txnid from comdb2_prepared")

    write_prompt $func "Dist-txnid is $dist_txnid"

    check_blocked $insert_pid
    write_prompt $func "New insert is blocked:"

    write_prompt $func "Commit prepared dist-txn:"
    write_prompt $func "send disttxn $dist_txnid commit"
    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "exec procedure sys.cmd.send('disttxn $dist_txnid commit')"

    sleep 5
    write_prompt $func "New insert should have resolved(2):"
    #check_notblocked $leaked_pid
    check_notblocked $insert_pid

    write_prompt $func "New insert is resolved: $(ps -ef | egrep $insert_pid)"
    write_prompt $func "Verify that t1 has 3000 records"

    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select count(*) from t1")
    write_prompt $func "Count is $x records"

    [[ "$x" != "5000" ]] && failexit "Select returned incorrect number of records, $x vs 5000"

    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "truncate t1"
}

function recover_prepared_and_downgrade
{
    typeset func="recover_prepared_and_abort"
    typeset master=$(findmaster)
    typeset newmaster="unset"
    typeset dgcount=0

    write_prompt $func "Inserting records"
    insert_t1

    # TODO this will change when bdb-hooks are done
    write_prompt $func "Tell master to prepare and leak"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "put tunable 'debug_all_prepare_leak' 1"

    write_prompt $func "Insert 1000 more records this should force master exit"
    insert_t1 &
    leaked_pid=$!

    write_prompt $func "Sleep a bit to make sure prepare record has propogated"
    sleep 4

    write_prompt $func "Kill the leaked pid so it's not retried"
    kill -9 $leaked_pid

    write_prompt $func "Explicitly kill old master, it should be exiting though"
    kill_restart_node $master

    write_prompt $func "Waiting for election / new master"
    wait_for_election

    write_prompt $func "Sleep for 5"
    sleep 5

    write_prompt $func "Find new master"
    master=$(findmaster)

    write_prompt $func "Verify that new master has recovered prepared txn"
    flags=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select flags from comdb2_prepared")
    [[ -z "$flags" ]] && failexit "Master did not recover the prepared txn"
    [[ "$flags" -ne "RECOVERED|HAVELOCKS" ]] && failexit "Master did not reaquire locks"

    newmaster=$master
    while [[ "$newmaster" == "$master" ]]; do
        write_prompt $func "Downgrade new master"
        $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "exec procedure sys.cmd.send('downgrade')" > /dev/null 2>&1
        write_prompt $func "Sleep for 5"
        sleep 5

        write_prompt $func "Find new master"
        newmaster=$(findmaster)

        if [[ "$newmaster" == "$master" ]]; then
            write_prompt $func "Got same master, retrying"
            sleep 5
        fi
    done

    master=$(findmaster)

    write_prompt $func "Verify that new master has recovered prepared txn"
    flags=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select flags from comdb2_prepared")
    [[ -z "$flags" ]] && failexit "Master did not recover the prepared txn"
    [[ "$flags" -ne "RECOVERED|HAVELOCKS" ]] && failexit "Master did not reaquire locks"

    write_prompt $func "Insert records- these should block on the recovered prepare"
    insert_t1 &
    insert_pid=$!
    write_prompt $func "Insert pid is $insert_pid"

    write_prompt $func "Verify that insert sql is blocked"
    check_blocked $insert_pid

    master=$(findmaster)
    write_prompt $func "Verify that replicant has seen prepared record"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Replicant did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED" ]] && failexit "Error locating prepared record"

    write_prompt $func "Verify that master has seen prepared record and has locks"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master  "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Master did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED|HAVELOCKS" ]] && failexit "Master prepared txn should have acquired locks"

    write_prompt $func "Downgrade the master: elect code should abort txns waiting on prepared locks"

    newmaster=$master
    while [ "$newmaster" == "$master" -a "$dgcount" -lt 10 ]; do
        write_prompt $func "Downgrade new master"
        $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "exec procedure sys.cmd.send('downgrade')" > /dev/null 2>&1
        write_prompt $func "Sleep for 5"
        sleep 5

        write_prompt $func "Find new master"
        newmaster=$(findmaster)

        if [[ "$newmaster" == "$master" ]]; then
            write_prompt $func "Got same master, retrying"
            sleep 5
            let dgcount=dgcount+1
        fi
    done

    [[ "$master" == "$newmaster" ]] && failexit "Old master was unable to downgrade"
    master=$(findmaster)

    write_prompt $func "Get the dist-txnid"
    dist_txnid=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select dist_txnid from comdb2_prepared")
    [[ -z "$dist_txnid" ]] && failexit "Master does not have dist-txnid"


    write_prompt $func "Abort dist txn"

    write_prompt $func "Dist-txnid is $dist_txnid"
    write_prompt $func "Abort prepared dist-txn:"
    write_prompt $func "send disttxn $dist_txnid abort"
    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "exec procedure sys.cmd.send('disttxn $dist_txnid abort')"

    sleep 5
    write_prompt $func "insert should have resolved:"
    check_notblocked $insert_pid

    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "truncate t1"
}

function prepare_fail_on_non_utxnid
{
    typeset func="prepare_and_abort"
    typeset master=$(findmaster)

    # TODO this will change when bdb-hooks are done
    write_prompt $func "Change master to prepare-commit for all writes"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "put tunable 'debug_all_prepare_commit' 1"

    write_prompt $func "Insert records - this should succeed"
    insert_t1

    write_prompt $func "Disable utxnid logging"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "put tunable 'utxnid_log' 0"

    write_prompt $func "Verify that master is up"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "select 1" >/dev/null 2>&1
    r=$? ; [[ "$r" -ne "0" ]] && failexit "Master is not up"

    write_prompt $func "Insert more records - this should abort"
    insert_t1

    sleep 2
    write_prompt $func "Verify that master is down"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "select 1" >/dev/null 2>&1
    r=$? ; [[ "$r" -eq "0" ]] && failexit "Master did not crash"

    kill_restart_node $master
    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "truncate t1"
}

function prepare_and_abort
{
    typeset func="prepare_and_abort"
    typeset master=$(findmaster)

    write_prompt $func "Inserting records"
    insert_t1

    # TODO this will change when bdb-hooks are done
    write_prompt $func "Tell master to prepare and leak"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "put tunable 'debug_all_prepare_leak' 1"

    write_prompt $func "Insert 1000 more records this should force master exit"
    insert_t1 &
    leaked_pid=$!

    write_prompt $func "Sleep a bit to make sure prepare record has propogated"
    sleep 4

    write_prompt $func "Kill the leaked pid so it's not retried"
    kill -9 $leaked_pid

    write_prompt $func "Explicitly kill old master, it should be exiting though"
    kill_restart_node $master

    write_prompt $func "Waiting for election / new master"
    wait_for_election

    write_prompt $func "Sleep for 5"
    sleep 5

    write_prompt $func "Retrieve current LSN"
    lsn=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select lsn from comdb2_transaction_logs(NULL, NULL, 4) limit 1")
    write_prompt $func "Current lsn is $lsn"

    write_prompt $func "Performing another insert- this should block on the prepared insert"
    insert_t1 &
    insert_pid=$!
    write_prompt $func "Insert pid is $insert_pid"

    write_prompt $func "Verify that insert sql is blocked"
    check_blocked $insert_pid

    master=$(findmaster)
    write_prompt $func "Verify that replicant has seen prepared record"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Replicant did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED" ]] && failexit "Error locating prepared record"

    write_prompt $func "Verify that master has seen prepared record and has locks"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master  "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Master did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED|HAVELOCKS" ]] && failexit "Master prepared txn should have acquired locks"

    write_prompt $func "Verify that master has pagelocks, one for new insert should be waiting"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master  "select count(*) from comdb2_locks where mode='READ' and status='WAIT' and locktype='PAGE'")
    [[ "$x" -lt "1" ]] && failexit "Outstanding insert isn't blocked on prepared txn"
    x=$($CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master  "select * from comdb2_locks where mode='READ' and status='WAIT' and locktype='PAGE'")
    write_prompt $func "$x"

    write_prompt $func "Verify that we have acquired the tablelock"
    table_lock=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select * from comdb2_locks where locktype='TABLELOCK t1'")
    [[ -z "$table_lock" ]] && failexit "Master did not recover the tablelock"
    write_prompt $func "$table_lock"

    write_prompt $func "Verify that reading on replicant is not blocked.. this will time-out if it is"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default  "select count(*) from t1")
    write_prompt $func "Make sure that there are only 1000 records on the replicant"
    write_prompt $func "Count is $x records"
    [[ "$x" -ne "1000" ]] && failexit "There should be 1000 records, not $x"

    write_prompt $func "Get the dist-txnid"
    dist_txnid=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select dist_txnid from comdb2_prepared")
    [[ -z "$dist_txnid" ]] && failexit "Master does not have dist-txnid"
    write_prompt $func "Dist-txnid is $dist_txnid"
    write_prompt $func "Abort prepared dist-txn:"
    write_prompt $func "send disttxn $dist_txnid abort"
    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "exec procedure sys.cmd.send('disttxn $dist_txnid abort')"

    sleep 5
    write_prompt $func "New insert should have resolved(1):"
    check_notblocked $insert_pid

#   Limbo will orphan pages if a recovered-prepare's abort is the first dbp 
#   action on a new master because it's DB_AM_RECOVER flag is set.  The code
#   normally relies on dbreg_lazy_id to replace a non-logging dbp with a 
#   logging dbp in the ufid-hash.
#
#   Solutions all seem heavy-weight for a fringe condition ..
#
#    write_prompt $func "Verify that the aborted dist-txn freed pages"
#    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select count(*) from comdb2_transaction_logs(\"$lsn\", NULL, 0) where rectype=3050")
#    [[ "$x" -eq "0" ]] && failexit "Aborted dist-txn did not free pages"
#    write_prompt $func "Aborted disttxn produced $x pg-free records"

    write_prompt $func "New insert is resolved: $(ps -ef | egrep $insert_pid)"
    write_prompt $func "Verify that t1 has 2000 records"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select count(*) from t1")
    write_prompt $func "Count is $x records"

    [[ "$x" -ne "2000" ]] && failexit "Found only $x records, should be 2000"

    write_prompt $func "Single-master bounce succeeded!"
    write_prompt $func "Checking cluster"
    check_cluster

    master=$(findmaster)
    write_prompt $func "Master is $master"
    
    write_prompt $func "Tell master to prepare and leak"
    $CDB2SQL_EXE $CDB2_OPTIONS $DBNAME --host $master "put tunable 'debug_all_prepare_leak' 1"

    write_prompt $func "Insert 1000 more records"
    insert_t1 &
    leaked_pid=$!

    write_prompt $func "Sleep for 5"
    sleep 5

    write_prompt $func "Killing the cluster"
    kill_cluster

    write_prompt $func "Starting the cluster"
    start_cluster

    write_prompt $func "Waiting for election / new master"

    for node in $CLUSTER; do 
        verify_up $node
    done

    write_prompt $func "Sleep for 5"
    sleep 5

    write_prompt $func "Background insert after cluster bounce"
    write_prompt $func "This should block on leaked prepared we did before cluster bounce"
    insert_t1 &
    insert_pid=$!

    master=$(findmaster)

    write_prompt $func "Verify that insert sql is blocked after cluster bounce"
    check_blocked $insert_pid

    write_prompt $func "Verify that replicant has recovered prepared record"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select flags from comdb2_prepared")
    [[ -z "$x" ]] && failexit "Replicant did not recover the prepared txn"
    [[ "$x" -ne "RECOVERED" ]] && failexit "Error locating prepared record"

    write_prompt $func "Verify that master has recovered & re-acquired prepared locks"
    flags=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select flags from comdb2_prepared")
    [[ -z "$flags" ]] && failexit "Master did not recover the prepared txn"
    [[ "$flags" -ne "RECOVERED|HAVELOCKS" ]] && failexit "Master did not reaquire locks"
    write_prompt $func "Select the locks"
    locks=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select * from comdb2_locks where locktype='PAGE'")
    write_prompt $func "$locks"

    write_prompt $func "Verify that we have acquired the tablelock"
    table_lock=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select * from comdb2_locks where locktype='TABLELOCK t1'")
    [[ -z "$table_lock" ]] && failexit "Master did not recover the tablelock"
    write_prompt $func "$table_lock"

    write_prompt $func "Verify that select against replicant returns 2000 records"
    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default  "select count(*) from t1")
    [[ "$x" -ne "2000" ]] && failexit "There should be 2000 records, not $x"

    write_prompt $func "Get the dist-txnid"
    dist_txnid=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "select dist_txnid from comdb2_prepared")

    write_prompt $func "Dist-txnid is $dist_txnid"

    check_blocked $insert_pid
    write_prompt $func "New insert is blocked:"

    write_prompt $func "Abort prepared dist-txn:"
    write_prompt $func "send disttxn $dist_txnid abort"
    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME --host $master "exec procedure sys.cmd.send('disttxn $dist_txnid abort')"

    sleep 5
    write_prompt $func "New insert should have resolved(2):"
    #check_notblocked $leaked_pid
    check_notblocked $insert_pid

    write_prompt $func "New insert is resolved: $(ps -ef | egrep $insert_pid)"
    write_prompt $func "Verify that t1 has 3000 records"

    x=$($CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "select count(*) from t1")
    write_prompt $func "Count is $x records"

    [[ "$x" != "3000" ]] && failexit "Select returned incorrect number of records, $x vs 3000"

    $CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "truncate t1"
}

function run_test
{
    typeset func="run_test"
    typeset master=$(findmaster)

    write_prompt $func "Running $func"

    rm $stopfile >/dev/null 2>&1
    create_table

    prepare_and_abort
    prepare_and_commit
    recover_prepared_and_downgrade
    if [[ $TESTCASE != "blkseq_serial_generated" ]] ; then
        prepare_fail_on_non_utxnid
    fi
}

[[ -z "$CLUSTER" ]] && failexit "This test requires a cluster"

run_test
stop_cluster
wait
echo "Success"
