#!/bin/sh
bash -n "$0" | exit 1
dbnm=$1

#### Test resizing object pool at runtime ####
cat << EOF | cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default -
SELECT 1 UNION SELECT 2
EXEC PROCEDURE sys.cmd.send("bdb temptable capacity 1024")
SELECT 1 UNION SELECT 2
EOF
