ifeq ($(TESTSROOTDIR),)
  include ../testcase.mk
else
  include $(TESTSROOTDIR)/testcase.mk
endif
ifeq ($(TEST_TIMEOUT),)
	export TEST_TIMEOUT=30m
#else
#	$(shell echo "TEST_TIMEOUT IS ${TEST_TIMEOUT}")
endif
