#!/usr/bin/env bash
bash -n "$0" | exit 1
source ${TESTSROOTDIR}/tools/runit_common.sh
for test_file in `ls *timepart*.sql`; do
    TIMEPART_STARTTIME=$(get_timestamp 2)
    cat ${test_file} | sed "s/{{STARTTIME}}/${TIMEPART_STARTTIME}/" > ${test_file}.new
    mv ${test_file}.new ${test_file}
done

${TESTSROOTDIR}/tools/compare_results.sh -s -d $1
[ $? -eq 0 ] || exit 1
exit 0
