DROP TABLE IF EXISTS t14_1
SELECT '- CREATE A TIME PARTITION -' AS caption
CREATE TABLE t14_1 (a INT) PARTITIONED BY TIME PERIOD 'daily' RETENTION 7 start '2023-01-01T00:00:00 UTC'$$
EXEC PROCEDURE sys.cmd.send("partinfo")
SELECT '- INSERT DATA -' AS caption
INSERT INTO t14_1 VALUES(1)
SELECT 'ALTER PARTITIONED BY - THIS SHOULD FAIL' AS caption
ALTER TABLE t14_1 PARTITIONED BY TIME PERIOD 'monthly' RETENTION 6 start '2023-01-01T00:00:00 UTC'$$
SELECT 'ALTER REPARTITIONED BY - ADD A COLUMN, AND INCREASE RETENTION' AS caption
ALTER TABLE t14_1 ADD COLUMN b INT, REPARTITIONED BY TIME PERIOD 'daily' RETENTION 14 start '2023-01-01T00:00:00 UTC'$$
EXEC PROCEDURE sys.cmd.send("partinfo")
SELECT 'INSERT DATA' AS caption
INSERT INTO t14_1 VALUES(2)
INSERT INTO t14_1 VALUES(2, 2)
SELECT * FROM t14_1
SELECT 'ALTER REPARTITIONED BY - DROP A COLUMN, AND REDUCE RETENTION' AS caption
ALTER TABLE t14_1 DROP COLUMN b, REPARTITIONED BY TIME PERIOD 'monthly' RETENTION 6 start '2023-01-01T00:00:00 UTC'$$
SELECT 'INSERT DATA' AS caption
INSERT INTO t14_1 VALUES(3)
INSERT INTO t14_1 VALUES(3, 3)
SELECT * FROM t14_1
EXEC PROCEDURE sys.cmd.send("partinfo")
