DROP TABLE IF EXISTS t
CREATE TABLE t(a int)$$
CREATE UNIQUE INDEX ta ON t(a)
INSERT INTO t VALUES(NULL), (NULL)
SELECT count(*) FROM t

DROP TABLE IF EXISTS t
CREATE TABLE t(a int)$$
CREATE UNIQUE INDEX ta ON t(a DESC)
INSERT INTO t VALUES(NULL), (NULL)
SELECT count(*) FROM t
