#!/usr/bin/env bash
bash -n "$0" | exit 1

dbname=$1

echo "Starting snapisol tests"
echo "Using SP_OPTIONS: $SP_OPTIONS"
./test.sh $dbname
rc=$?
if (( $rc != 0 )) ; then
   echo "SNAPISOL FAILURE"
   exit 1
fi

echo "SNAPISOL SUCCESS"
