#!/usr/bin/env bash
bash -n "$0" | exit 1

source ${TESTSROOTDIR}/tools/runit_common.sh


gen() {
    IN=$SECONDS
    while [ $((SECONDS-IN)) -lt 30 ] ; do
        echo "begin"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "commit"
    done
}

do_verify()
{
    tbl=$1
    cdb2sql ${CDB2_OPTIONS} $DBNAME default "exec procedure sys.cmd.verify('$tbl')" &> verify.out

    if ! grep succeeded verify.out > /dev/null ; then
        failexit "verify $tbl failed"
    fi
}


export -f gen

cnt=0
while :; do
    let cnt=$cnt+1
    cdb2sql ${CDB2_OPTIONS} $DBNAME default "truncate t"
    cdb2sql ${CDB2_OPTIONS} $DBNAME default "exec procedure sys.cmd.send('delfiles t')"
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out1.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out2.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out3.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &

    wait

    do_verify t
    echo "done with run $cnt"
done
