#!/usr/bin/env bash
bash -n "$0" | exit 1


gen() {
    IN=$SECONDS
    while [ $((SECONDS-IN)) -lt 30 ] ; do
        echo "begin"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "insert into t values(0,0,0,0,0,0,0)"
        echo "commit"
    done
}

do_verify()
{
    tbl=$1
    cdb2sql ${CDB2_OPTIONS} $DBNAME default "exec procedure sys.cmd.verify('$tbl')" &> verify.out

    if ! grep succeeded verify.out > /dev/null ; then
        failexit "verify $tbl failed"
    fi
}


export -f gen

while :; do
    cdb2sql ${CDB2_OPTIONS} $DBNAME default "truncate t"
    cdb2sql ${CDB2_OPTIONS} $DBNAME default "exec procedure sys.cmd.send('delfiles t')"
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out1.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out2.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out3.txt &
    gen | cdb2sql ${CDB2_OPTIONS} $DBNAME default > out4.txt &

    wait

    set -e

    do_verify t
    for i in $(seq 1 4); do
        cdb2sql ${CDB2_OPTIONS} $DBNAME default "rebuild t"
        do_verify t
    done
    set +e
done
