#!/usr/bin/env bash

[[ $debug == 1 ]] && set -x
export db=$1
export exe=${TESTSBUILDDIR}/cdb2_close_early

set -e

echo "comdb2_feature:discard_unread_socket_data=on" >>$DBDIR/comdb2db.cfg

cdb2sql ${CDB2_OPTIONS} $db default "create table t1 (i int)"
cdb2sql ${CDB2_OPTIONS} $db default "insert into t1 select * from generate_series(1,100000)"

$exe -d $db -e > out.txt 2>&1
grep "Discarded socket 1 Discarded 1 Max 1 type 2" out.txt
grep "cdb2_close took [012] ms" out.txt

echo "Passed"
exit 0
