#!/usr/bin/env bash

[[ $debug == 1 ]] && set -x
export db=$1
export exe=${TESTSBUILDDIR}/cdb2_close_early

set -e

cdb2sql ${CDB2_OPTIONS} $db default "create table t1 (i int)"
cdb2sql ${CDB2_OPTIONS} $db default "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt LIMIT 200) insert into t1(i) SELECT x FROM cnt"

$exe -d $db -e > out.txt 2>&1

grep "auto consume 199 records" out.txt

echo "Passed"
exit 0
