#!/usr/bin/env bash

bash -n "$0" | exit 1

dbname=$1

set -e

rep=`cdb2sql --tabs ${CDB2_OPTIONS} $dbname default 'select comdb2_host()'`

cdb2sql --host $rep ${CDB2_OPTIONS} $dbname 'create table t(a int)'
cdb2sql --host $rep ${CDB2_OPTIONS} $dbname 'create default lua consumer test on (table t for insert)'

cdb2sql --host $rep ${CDB2_OPTIONS} $dbname - <<'EOF'
set transaction blocksql
set transaction chunk 100
begin
insert into t select value from generate_series(1, 1000000)
commit
EOF

yes "select * from comdb2_queues" | cdb2sql --host $rep ${CDB2_OPTIONS} $dbname - >/dev/null &
echo $pid
pid=$!
sleep 1

maxlocks=0

for i in {1..30}; do
    locks=$(cdb2sql --host $rep -tabs ${CDB2_OPTIONS} $dbname "select count(*) from comdb2_locks where locktype != 'HANDLE'")
    [[ $locks -gt $maxlocks ]] && maxlocks=$locks
    sleep 1
done

kill -9 $pid

if [[ $maxlocks -gt 10 ]]; then
    echo "Expected < 10 locks, got $maxlocks"
    exit 1
fi

echo maxlocks $maxlocks

exit 0
