#!/usr/bin/env bash

results=./results.txt
expected=./results.expected

$CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "create table t1(a int)" 
$CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default "insert into t1 select * from generate_series(1, 1000)"
$CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default - <<EOF &
@redirect $results
set transaction snapshot
begin
select count(*) from t1
select sleep(5)
select count(*) from t1
commit
EOF

$CDB2SQL_EXE --tabs $CDB2_OPTIONS $DBNAME default - <<EOF
select sleep(2)
delete from t1 where 1
EOF

wait

diff $results $expected
if [[ $? != 0 ]]; then
    echo "Testcase failed"
    exit 1
fi

echo "Testcase succeeded"
