#!/bin/bash
bash -n "$0" | exit 1

# This doesn't make much sense as a clustered test - get a free pass
[[ -n "$CLUSTER" ]] && exit 0

# Test case to verify client-side hooks.

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

./cdb2_client $dbname
if [ $? -ne 0 ]; then
  exit 1
fi

cdb2sql ${CDB2_OPTIONS} $dbname default "exec procedure sys.cmd.send('reql events roll')"

# Get the longreqs logs
pwd
zcat ../var/log/cdb2/clientcontext${TESTID}.events.* | grep context | grep -v cdb2sql | sed 's!.*"context": \[!context": \[!; s/\],.*/]/' > testcase.out

set +x
diff expected.out testcase.out

# Compare the longreqs logs.
if [ $? -ne 0 ]; then
    echo "  ^^^^^^^^^^^^"
    echo "The above testcase (${testcase}) has failed!!!"
    echo " "
    echo "Use 'diff <expected-output> <my-output>' to see why:"
    echo "> diff ${PWD}/{testcase.out,expected.out}"
    echo " "
    diff testcase.out expected.out
    echo " "
    exit 1

fi

exit 0
