#!/usr/bin/env bash
bash -n "$0" | exit 1

db=${DBNAME}
tier=default
CDB2_HOST_NAME=localhost

if [[ -n "$CLUSTER" ]]; then
    node=$(echo "$CLUSTER" | awk '{print $1}')
    ssh -o StrictHostKeyChecking=no $node "${TESTSBUILDDIR}/cdb2api_admin ${db} ${CDB2_HOST_NAME} ${tier}"
    [[ $? -ne 0 ]] && echo "admin connection to local host test failed" &&  echo "cdb2api_admin - fail" && exit 1
else
    ${TESTSBUILDDIR}/cdb2api_admin ${db} ${CDB2_HOST_NAME} ${tier}
    [[ $? -ne 0 ]] && echo "admin connection to local host test failed" &&  echo "cdb2api_admin - fail" && exit 1
fi

if [[ -n "$CLUSTER" ]]; then
    CDB2_HOST_NAME=$(${CDB2SQL_EXE} ${CDB2_OPTIONS} -tabs -s ${db} ${tier} "select comdb2_host()")
    ${TESTSBUILDDIR}/cdb2api_admin ${db} ${CDB2_HOST_NAME} ${tier} 
    [[ $? -ne 0 ]] && echo "admin connection to remote host test failed" && echo "cdb2api_admin - fail" && exit 1
fi

echo 'cdb2api_admin - pass'

${TESTSBUILDDIR}/cdb2api_hasql ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_hasql - fail" && exit 1
echo 'cdb2api_hasql - pass'

set -e

${TESTSBUILDDIR}/cdb2api_rte ${DBNAME}

# EXPECTED_PORTS='5105\|8125'
EXPECTED_PORTS='5105\|8125\|53'
if [[ $(uname) = "Linux" ]]; then
    set +e
    # what's port 0 on connect?
    strace ${TESTSBUILDDIR}/cdb2api_rte ${DBNAME} onlyrte 2>&1 | grep -w connect | grep AF_INET | sed "s/.*htons(//; s/).*//" | grep -v "0" | grep -v $EXPECTED_PORTS  > ports
    if [[ -s ports ]]; then
        echo 'Unexpected connection to following ports: '
        cat ports
        echo 'cdb2api_rte - failed'
        exit 1
    fi
fi
set +e

echo 'cdb2api_rte - pass'

${TESTSBUILDDIR}/cdb2api_setoptions ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_setoptions - fail" && exit 1
echo 'cdb2api_setoptions - pass'

${CDB2SQL_EXE} ${CDB2_OPTIONS} ${DBNAME} default 'create procedure sptrace version '"'cdb2api_test'"' {local function main() db:trace('"'hello, world\!'"') end}'
${CDB2SQL_EXE} ${CDB2_OPTIONS} ${DBNAME} default 'create procedure spdebug version '"'cdb2api_test'"' {local function main()
    db:debug(1)
    db:debug(2)
    db:debug(3)
end}'
${TESTSBUILDDIR}/cdb2api_sptrace ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_sptrace - fail" && exit 1
echo 'cdb2api_sptrace - pass'

CDB2_LOG_CALLS=1 ${TESTSBUILDDIR}/cdb2api_stmt_return_types ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_stmt_return_types - fail" && exit 1
echo 'cdb2api_stmt_return_types - pass'

${TESTSBUILDDIR}/cdb2api_string_escape
[[ $? -ne 0 ]] && echo "cdb2api_string_escape - fail" && exit 1
echo 'cdb2api_string_escape - pass'

if [[ -n "$CLUSTER" ]]; then
    CDB2_HOST_NAME=$(${CDB2SQL_EXE} ${CDB2_OPTIONS} -tabs -s ${db} ${tier} "select comdb2_host()")
    CDB2_CLASS=$(${CDB2SQL_EXE} ${CDB2_OPTIONS} -tabs -s ${db} ${tier} "select comdb2_sysinfo('class')")
    ${TESTSBUILDDIR}/cdb2api_direct ${DBNAME} ${CDB2_CLASS} ${CDB2_HOST_NAME}
    [[ $? -ne 0 ]] && echo "cdb2api_direct - fail" && exit 1
fi

echo 'cdb2api_direct - pass'

${TESTSBUILDDIR}/cdb2api_txn ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_txn - fail" && exit 1
echo 'cdb2api_txn - pass'

pgrep cdb2sockpool
if [ $? -ne 0 ]; then
    echo 'SOCKPOOL IS REQUIRED TO RUN THE TEST BUT IS NOT RUNNING.' >&2
    echo 'TRYING TO BRING IT UP'
    ${BUILDDIR}/tools/cdb2sockpool/cdb2sockpool
    sleep 1
    pgrep cdb2sockpool
    if [ $? -ne 0 ]; then
        echo 'FAILED BRINGING UP SOCKPOOL' >&2
        exit 1
    fi
fi

cfg=$DBDIR/comdb2db.cfg
echo 'comdb2_config:api_call_timeout=5000' >> ${cfg}
echo 'comdb2_config:enforce_api_call_timeout=on' >> ${cfg}
${TESTSBUILDDIR}/cdb2api_enforce_timeout ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_enforce_timeout - fail" && exit 1
sed -i '/comdb2_config:api_call_timeout=5000/d' "${cfg}"
sed -i '/comdb2_config:enforce_api_call_timeout=on/d' "${cfg}"
echo 'cdb2api_enforce_timeout - pass'

${TESTSBUILDDIR}/cdb2api_localcache_systable ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_localcache_systable - fail" && exit 1
echo 'cdb2api_localcache_systable - pass'

echo 'comdb2_feature:discard_unread_socket_data=on' >> ${cfg}
${TESTSBUILDDIR}/cdb2api_unread_data ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_unread_data - fail" && exit 1
sed -i '/comdb2_feature:discard_unread_socket_data=on/d' "${cfg}"
echo 'cdb2api_unread_data - pass'

comdb2db_cfg=api_tst_comdb2db.cfg
dbname_cfg=api_tst_${db}.cfg
for global_tier in local dev integration beta prod proxy; do
    echo "comdb2_config:default_type=${global_tier}" > ${comdb2db_cfg}
    for db_tier in local dev integration beta prod proxy; do
        cat > ${dbname_cfg} <<-EOF
                comdb2_config:default_type=${db_tier}
                comdb2_config:api_call_timeout=1
                comdb2_config:comdb2db_timeout=1
                comdb2_config:connect_timeout=1
                comdb2_config:socket_timeout=1
                comdb2_feature:use_bmsd=0
EOF
        exp="${global_tier}:${db_tier}"
        res=$(${TESTSBUILDDIR}/cdb2api_cfg ${db} default ${comdb2db_cfg} ${dbname_cfg} 2> /dev/null)
        if [[ "${res}" !=  "${exp}" ]] ; then
            echo >&2 "cfg expected:${exp} result:${res} - fail"
            exit 1
        else
            echo "${res} ok"
        fi
    done
done
echo "cfg - pass"

exit 0
