#!/usr/bin/env bash
bash -n "$0" | exit 1

# Test to verify COMDB2_USER & COMDB2_PASSWORD environment variables.

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

echo Create a user and enable the authentication.
cdb2sql -f init.req ${CDB2_OPTIONS} $dbname default &> init.out

echo The following should give rc -5 because authentication is already on
COMDB2_USER=foo COMDB2_PASSWORD=pass cdb2sql ${CDB2_OPTIONS} $dbname default "put authentication on"
if [ $? -ne 1 ]; then
    echo "should not be able to set auth again, rc=$?"
    exit 1
fi


echo The following should fail because not authenticated.
cdb2sql ${CDB2_OPTIONS} $dbname default "select * from t"
if [ $? -ne 1 ]; then
    exit 1
fi

echo Try with incorrect password, should fail
export COMDB2_USER=foo
export COMDB2_PASSWORD=bar
cdb2sql ${CDB2_OPTIONS} $dbname default "select * from t"
if [ $? -ne 1 ]; then
    exit 1
fi

export COMDB2_USER=foo
export COMDB2_PASSWORD=pass
echo Now try with correct password, should succeed
cdb2sql ${CDB2_OPTIONS} $dbname default "select * from t"
if [ $? -ne 0 ]; then
    exit 1
fi

exit 0
