find_path(PROTOBUF-C_INCLUDE_DIR NAMES protobuf-c/protobuf-c.h)
find_library(PROTOBUF-C_LIBRARY NAMES protobuf-c)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PROTOBUF-C DEFAULT_MSG PROTOBUF-C_INCLUDE_DIR)
find_package_handle_standard_args(libprotobuf-c DEFAULT_MSG PROTOBUF-C_LIBRARY)
