#!/usr/bin/env bash
bash -n "$0" | exit 1

dbnm=$1

if [ "x$dbnm" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

function failexit
{
    echo "Failed $1"
    exit -1
}

echo "create table t2, should succeed"
cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t2  { `cat t2_1.csc2 ` }" || failexit "create failed"
echo "alter table t2, should fail"
cdb2sql ${CDB2_OPTIONS} $dbnm default "alter table t2  { `cat t2_2.csc2 ` }" && failexit "should not be able to alter"


echo "create table t3, should fail"
cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t3  { `cat t1_1.csc2 ` }" && failexit "should not be able to create"

echo "rebuild table t1, should fail"
cdb2sql ${CDB2_OPTIONS} $dbnm default "rebuild t1" && failexit "should not rebuild"
echo "truncate table t1, should succeed"
cdb2sql ${CDB2_OPTIONS} $dbnm default "truncate t1" || failexit "should be able to truncate"
echo "alter table t1 to make it smaller, should succeed"
cdb2sql ${CDB2_OPTIONS} $dbnm default "alter table t1  { `cat t1_2.csc2 ` }" || failexit "should be able to alter to make it smaller"

echo "drop table t4, should succeed"
cdb2sql ${CDB2_OPTIONS} $dbnm default "drop table t4 " || failexit "should be able to drop table"

echo "Success"
