#!/bin/bash
bash -n "$0" | exit 1

set -x

COPYDIR=$DBDIR/copy
mkdir $COPYDIR
copycomdb2 -s ${DBDIR}/${DBNAME}.lrl $COPYDIR
cd $COPYDIR
grep -v name ${DBNAME}.lrl > tmp && mv tmp ${DBNAME}.lrl
NEWNAME="qcopy$$test"
echo "name $NEWNAME" >> ${DBNAME}.lrl
$comdb2task $NEWNAME --create --lrl ${DBNAME}.lrl
$comdb2task $NEWNAME --lrl ${DBNAME}.lrl &

trap "cdb2sql $NEWNAME \"exec procedure sys.cmd.send('exit')\"" EXIT

while :; do 
    out=$(cdb2sql -tabs $NEWNAME local 'select 1')
    [[ "$out" = "1" ]] && break
    sleep 1
done

exit 0
