#!/usr/bin/env bash
bash -n "$0" | exit 1

cdb2="cdb2sql --tabs -s ${CDB2_OPTIONS} $1 default "

function multi_chunk {
    echo "set transaction blocksql"
    echo "set transaction chunk $chunk"
    echo 'begin'
    from=1
    for ((i = 1; i <= $iterations; ++i)); do
        to=$(($from + $batch - 1))
        echo "insert into t select value from generate_series($from, $to)"
        from=$(($to + 1))
    done
    echo 'commit'
}

chunk=100
iterations=1000
batch=1000

$cdb2 "drop table if exists t"
$cdb2 "create table t(i int)"
multi_chunk | $cdb2 > /dev/null
count=$($cdb2 'select count(*) from t')
echo "table t row-count:$count"
if [[ $count -ne $(($iterations * $batch)) ]]; then
    echo "Failed."
    exit 1
fi
echo "Passed."
exit 0
