#!/usr/bin/env bash
bash -n "$0" | exit 1

# Debug variable
debug=0

# Grab my database name.
dbnm=$1
if [ "x$dbnm" == "x" ] ; then
    echo "need a DB name"
    exit 1
fi

rebuild=1
if [ "x$2" == "xnorebuild" ] ; then
    rebuild=0
fi

tbl=t6
tblver=0


# Number of records I will add.
nrecs=2000

# Max number of schema changes
max_nusc=1000

function failexit
{
    echo "Failed $1"
    exit -1
}

function assertcnt 
{
    target=$1
    cnt=$(cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select count(*) from $tbl")
    #echo "count is now $cnt"
    if [[ $cnt != $target ]] ; then
        failexit "count is now $cnt but should be $target"
    fi
}

assert_vers()
{
    local loc_tbl=$1
    local target=$2
    local newver=$(cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default "select table_version('$loc_tbl')")
    if [[ $newver != $target ]] ; then
        failexit "newver is now $newver but should be $target"
    fi
}

function do_verify
{
    cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure sys.cmd.verify('$tbl')" &> verify.out

    if ! grep succeeded verify.out > /dev/null ; then
        failexit "Verify"
    fi
}

function do_rebuild_track_pid
{
    typeset loc_dbnm=$1
    typeset loc_tbl=$2
    typeset track_pid=$3
    typeset scnt=0
    while `kill -0 $track_pid 2>/dev/null` && [[ $scnt -lt $max_nusc ]]; do

        echo "Running rebuild iteration $scnt"
        cdb2sql ${CDB2_OPTIONS} $loc_dbnm default "rebuild $loc_tbl"

        if [[ $? != 0 ]]; then
            echo "Error schema-changing on iteration $scnt"
            echo "Testcase failed"
            kill -9 $track_pid
            exit 1
        fi

        let scnt=scnt+1
        do_verify $loc_dbnm $loc_tbl
        assert_vers $loc_tbl $tblver
    done

    echo "Performed $scnt schema-changes."

    return 0
}






function delete_records
{
    j=1
    remaining=$nrecs
    echo
    echo "Deleting $nrecs records."
    echo "" > delete.out
    strt=$(date +%s)

    while [[ $j -le $nrecs ]]; do 
         cdb2sql ${CDB2_OPTIONS} $dbnm default "delete from $tbl where a = $j" >> delete.out 2>&1 || $(echo "ERROR DELETING"; exit -1)
         let j=j+1
	     let remaining=remaining-1
         #assertcnt $remaining
         #sleep 0.1
    done
    end=$(date +%s)
    echo "delete_records took $((end - strt)) sec."
}

function insert_records
{
    j=1
    echo
    echo "Inserting $nrecs records."
    strt=$(date +%s)

    while [[ $j -le $nrecs ]]; do 
        cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into $tbl(a,b,c,d,e,f) values ($j,'test1',x'1234',$((j*2)),$j,$j)"  >> insert.out 2>&1
        #assertcnt $j
        let j=j+1
        if [ $1 -gt 0 ] ; then
            sleep 0.1
        fi
    done
    end=$(date +%s)
    echo "insert_records took $((end - strt)) sec."
}




function run_test
{
    typeset ipid=''
    nrecs=$1
	echo 
	echo "run_test $nrecs"

    > insert.out
    insert_records 0 &
    ipid=$!

    if [ $rebuild -eq 1 ] ; then
        do_rebuild_track_pid $dbnm $tbl $ipid
    fi
    wait

    assertcnt $nrecs
    do_verify

    echo "deleting all records in background"
    delete_records &
    upid=$!

    if [ $rebuild -eq 1 ] ; then
        do_rebuild_track_pid $dbnm $tbl $upid
    fi
    wait

    assertcnt 0
}

echo 'Querying for nonexistent table should return NULL'
assert_vers nonexistent_table "NULL"


#cdb2sql ${CDB2_OPTIONS} $dbnm default "drop table $tbl"
assert_vers $tbl 0

#fastinit does not increase counter
cdb2sql ${CDB2_OPTIONS} $dbnm default "truncate $tbl"
assert_vers $tbl 0

g=100
while [ $g -lt 500 ] ; do 
	run_test $g
    let g=g+g
done

echo "Success"
