name: Basic Check

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  basic-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Basic validation
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"
          echo "✅ Basic check completed successfully"

      - name: Verify repository structure
        run: |
          echo "Checking repository structure..."
          ls -la
          echo "✅ Repository structure verified"
