name: clang-format

on:
  pull_request: { branches: ["main"] }

# If someone pushes a new commit to a branch, ensure that only the latest commit
# is built to avoid wasting runner minutes.
concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true


jobs:
  clang-format:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CLANG_FORMAT: "clang-format"
    defaults:
      run:
        # Make sure to fail any "run" step early on so that steps don't silently
        # pass even when errors may have occurred.
        shell: bash -o errexit -o nounset -o pipefail {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          $CLANG_FORMAT --version

      - name: Run format check
        run: |
          # Get the base branch name from the PR event
          base_branch="${GITHUB_BASE_REF}"

          # Get the number of commits in the PR (commits in HEAD not in base branch)
          num_commits=$(git rev-list --count HEAD ^origin/${base_branch})

          # Get the commit before all PR commits
          if [[ "$num_commits" -gt 0 ]]; then
            base_commit="HEAD~${num_commits}"
          else
            base_commit="HEAD^"
          fi

          echo "Running format checking against base commit ${base_commit}"

          format_flags=(--verbose --dry-run --compare-base "${base_commit}")
          if [[ "${RUNNER_DEBUG:-0}" == "1" ]]; then
            format_flags+=(--super-verbose)
          fi
          ./ci/scripts/format "${format_flags[@]}"
