#!/usr/bin/env bash
bash -n "$0" | exit 1

################################################################################

# debug=1

# args
DBN=$1
R="cdb2sql ${CDB2_OPTIONS} $DBN default"
O="log.txt"
T="t1"


COMDB2TZ="America/New_York" $R "insert into $T values (1, '9999-12-31T235959')" >$O 2>&1 
#if (( $? != 0 )) ; then EXPECTED
#    echo "Failure"
#fi

COMDB2TZ="GMT" $R "insert into $T values (2, '9999-12-31T235959')" >>$O 2>&1
if (( $? != 0 )) ; then
    echo "Failure"
    exit 1
fi

COMDB2TZ="GMT" $R "select * from $T" >>$O 2>&1
if (( $? != 0 )) ; then
    echo "Failure"
    exit 1
fi

COMDB2TZ="GMT" $R "insert into $T values (3, '9999-12-31T235959.999')" >>$O 2>&1
if (( $? != 0 )) ; then
    echo "Failure"
    exit 1
fi

COMDB2TZ="GMT" $R "select * from $T" >>$O 2>&1
if (( $? != 0 )) ; then
    echo "Failure"
    exit 1
fi

COMDB2TZ="Asia/Tokyo" $R "select * from $T" >>$O 2>&1
#if (( $? != 0 )) ; then EXPECTED
#    echo "Failure"
#fi

# get testcase output
testcase_output=$(cat $O)

# get expected output
expected_output=$(cat $O.expected)

# verify 
if [[ "$testcase_output" != "$expected_output"  ]]; then
        # print message 
        echo "  ^^^^^^^^^^^^"
        echo "The above testcase (${testcase}) has failed!!!" 
        echo " "
        echo "Use 'diff <expected-output> <my-output>' to see why:"
        echo "> diff $O $O.expected"
        echo " "
        diff $O $O.expected
        echo " "

        # quit
        exit 1
fi

print "Testcase passed."

exit 0
