#!/usr/bin/env bash
bash -n "$0" | exit 1

dbnm=$1

set -ex

# Make sure that all queries go to the same node.
mach=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'select comdb2_host()'`
echo "target machine is $mach"

cdb2sql -s --host $mach $dbnm "drop table if exists leak"
cdb2sql -s --host $mach $dbnm "create table leak (i int, t text)"

yes "insert into leak values (1, 'abcd')" | head -2000 | cdb2sql -s --host $mach $dbnm ->/dev/null
sleep 2
cdb2sql -s --host $mach $dbnm 'select i from leak where lower(t) in ("abcd") and i != 1'

cdb2sql --tabs -s --host $mach $dbnm 'exec procedure sys.cmd.send("memstat sqlite")' | grep SQLITE >expected

yes 'select i from leak where lower(t) in ("abcd") and i != 1' | head -500 | cdb2sql -s --host $mach $dbnm ->/dev/null

cdb2sql --tabs -s --host $mach $dbnm 'exec procedure sys.cmd.send("memstat sqlite")' | grep SQLITE >actual
diff actual expected
