#!/usr/bin/env bash
bash -n "$0" | exit 1

################################################################################

# debug=1

# args
a_dbn=$1

# find input files
files=$( find . -type f -name \*.req | sort )

TMPDIR=${TMPDIR:-/tmp}

# counter 
nfiles=0

# last batch
last_batch=

# post-process
pproc=cat

# testcase output
testcase_output=

# expected output
expected_output=

# fastinit
function fastinit
{
    # print debug trace
    [[ "$debug" == "1" ]] && set -x

    # args
    typeset db=$1
    typeset iter=$2
    typeset tbl

    # flagged?
    if [[ ! -f $iter.fastinit ]]; then
        return 0
    fi

    # fastinit
    for tbl in $(cat $iter.fastinit) ; do
        cdb2sql ${CDB2_OPTIONS} $db default "truncate $tbl"
    done

    return 0
}

# run tool
function runtool
{
    # print debug trace
    [[ "$debug" == "1" ]] && set -x

    # args
    typeset tool=$1
    typeset args=$2
    typeset db=$3
    typeset case=$4
    typeset output=$5

    # run
    echo "> $tool "$args" $db $case > $output 2>&1"
    $tool "$args" $db $case > $output 2>&1
}

# Iterate through input files
for testcase in $files ; do

    # increment counter
    let nfiles=nfiles+1

    # cleanup testcase
    testcase=${testcase##*/}
    
    # see if the prefix has changed
    new_batch=${testcase%%_*}

    # set output
    output=$testcase.res

    # full path 
    [[ "$output" == "${output#\/}" ]] && output=${PWD}/$output
    
    # fastinit if requested
    if [[ $new_batch != $last_batch ]] ; then

       fastinit $a_dbn $new_batch
        last_batch=$new_batch

    fi

    # Check for run-stepper
    if [[ -f $new_batch.tool ]] ; then

        tool=$( cat $new_batch.tool )
        args=$( cat $new_batch.args )
        runtool $tool "$args" $a_dbn $testcase $output
    else

        # Be verbose
        cmd="cdb2sql -s ${CDB2_OPTIONS} $a_dbn default - < $testcase > $output 2>&1"
        echo $cmd

        # run command
        eval $cmd

    fi

    # post-process
    if [[ -f $new_batch.post ]]; then

        # zap file
        > $output.postprocess

        # collect post-processing tool
        pproc=$(cat $new_batch.post)

        # post-process output
        $pproc $output >> $output.postprocess

        # copy post-processed output to original
        mv $output.postprocess $output
    fi

    # get testcase output
    testcase_output=$(cat $output)

    # get expected output
    if [[ "$(uname)" = "Linux" && -f $testcase.linux.expected ]]; then
        expected_output=$(cat $testcase.linux.expected)
    else
        expected_output=$(cat $testcase.expected)
    fi

    # get alternate output
    if [[ "$(uname)" = "Linux" && -f $testcase.linux.expected.alt ]]; then
        expected_output_alt=$(cat $testcase.linux.expected.alt)
    else
        expected_output_alt=$(cat $testcase.expected.alt 2>/dev/null)
    fi

    # verify 
    if [[ "$testcase_output" != "$expected_output" && "$testcase_output" != "$expected_output_alt" ]]; then
        echo "  ^^^^^^^^^^^^"
        echo "The above testcase (${testcase}) has failed!!!"
        echo " "
        echo "Use 'diff <expected-output> <my-output>' to see why:"
        echo "> diff $testcase.expected $output"
        echo " "
        diff $testcase.expected $output
        echo " "
        exit 1

    fi

done

echo "Testcase passed."
